export interface BannerCopy {
  bannerTitle: string
  bannerText: string
  chooseLanguage: string
  acceptAll: string
  rejectAll: string
  moreOptions: string
  savePreferences: string
  back: string
  saving: string
  viewFullNotice: string
  necessary: string
  necessaryDesc: string
  alwaysActive: string
  functional: string
  functionalDesc: string
  analytics: string
  analyticsDesc: string
  advertising: string
  advertisingDesc: string
  dataItemsLabel: string
  servicesLabel: string
  retentionLabel: string
  retentionDays: string
  consentLabel: string
  dpoLabel: string
  withdrawLink: string
  rightsLink: string
  grievanceLink: string
  boardComplaintLink: string
}

// Falls back to English whenever the visitor's chosen language has no entry here,
// so the banner never renders blank for an unsupported language.
export const BANNER_COPY: Record<string, BannerCopy> = {
  en: {
    bannerTitle: 'Your privacy matters at SkillLearn',
    bannerText:
      'We and our partners use cookies to keep your learning experience secure, remember your preferences and understand how courses are used.',
    chooseLanguage: 'Choose language',
    acceptAll: 'Accept All',
    rejectAll: 'Reject All',
    moreOptions: 'More Options',
    savePreferences: 'Save Preferences',
    back: 'Back',
    saving: 'Saving…',
    viewFullNotice: 'View full notice',
    necessary: 'Strictly necessary cookies',
    necessaryDesc: 'Always active. Required for the platform to work — sign-in, security and consent records.',
    alwaysActive: 'Always active',
    functional: 'Functional cookies',
    functionalDesc: 'Remember your language, enrolled courses and learning preferences.',
    analytics: 'Performance & analytics cookies',
    analyticsDesc: 'Help us understand how courses are used so we can improve the platform.',
    advertising: 'Advertising & social media cookies',
    advertisingDesc: 'Used by partners to show relevant course recommendations and ads.',
    dataItemsLabel: 'Data items',
    servicesLabel: 'Services enabled',
    retentionLabel: 'Retention',
    retentionDays: 'days',
    consentLabel: 'Consent',
    dpoLabel: 'Data Protection Officer',
    withdrawLink: 'Withdraw consent',
    rightsLink: 'Your rights',
    grievanceLink: 'Grievance',
    boardComplaintLink: 'Board complaint',
  },
  hi: {
    bannerTitle: 'SkillLearn पर आपकी गोपनीयता मायने रखती है',
    bannerText:
      'हम और हमारे भागीदार आपके सीखने के अनुभव को सुरक्षित रखने, आपकी प्राथमिकताओं को याद रखने और यह समझने के लिए कुकीज़ का उपयोग करते हैं कि पाठ्यक्रमों का उपयोग कैसे किया जाता है।',
    chooseLanguage: 'भाषा चुनें',
    acceptAll: 'सभी स्वीकार करें',
    rejectAll: 'सभी अस्वीकार करें',
    moreOptions: 'अधिक विकल्प',
    savePreferences: 'प्राथमिकताएं सहेजें',
    back: 'वापस',
    saving: 'सहेजा जा रहा है…',
    viewFullNotice: 'पूरा नोटिस देखें',
    necessary: 'कड़ाई से आवश्यक कुकीज़',
    necessaryDesc: 'हमेशा सक्रिय। प्लेटफ़ॉर्म के काम करने के लिए आवश्यक — साइन-इन, सुरक्षा और सहमति रिकॉर्ड।',
    alwaysActive: 'हमेशा सक्रिय',
    functional: 'कार्यात्मक कुकीज़',
    functionalDesc: 'आपकी भाषा, नामांकित पाठ्यक्रम और सीखने की प्राथमिकताएं याद रखें।',
    analytics: 'प्रदर्शन और विश्लेषण कुकीज़',
    analyticsDesc: 'यह समझने में मदद करें कि पाठ्यक्रमों का उपयोग कैसे किया जाता है ताकि हम प्लेटफ़ॉर्म को बेहतर बना सकें।',
    advertising: 'विज्ञापन और सोशल मीडिया कुकीज़',
    advertisingDesc: 'प्रासंगिक पाठ्यक्रम सिफारिशें और विज्ञापन दिखाने के लिए भागीदारों द्वारा उपयोग किया जाता है।',
    dataItemsLabel: 'डेटा आइटम',
    servicesLabel: 'सक्षम सेवाएं',
    retentionLabel: 'प्रतिधारण',
    retentionDays: 'दिन',
    consentLabel: 'सहमति',
    dpoLabel: 'डेटा संरक्षण अधिकारी',
    withdrawLink: 'सहमति वापस लें',
    rightsLink: 'आपके अधिकार',
    grievanceLink: 'शिकायत',
    boardComplaintLink: 'बोर्ड शिकायत',
  },
  ta: {
    bannerTitle: 'SkillLearn-இல் உங்கள் தனியுரிமை முக்கியம்',
    bannerText:
      'உங்கள் கற்றல் அனுபவத்தைப் பாதுகாப்பாக வைத்திருக்கவும், உங்கள் விருப்பங்களை நினைவில் வைக்கவும், படிப்புகள் எவ்வாறு பயன்படுத்தப்படுகின்றன என்பதைப் புரிந்துகொள்ளவும் நாங்களும் எங்கள் கூட்டாளர்களும் குக்கீகளைப் பயன்படுத்துகிறோம்.',
    chooseLanguage: 'மொழியைத் தேர்ந்தெடுக்கவும்',
    acceptAll: 'அனைத்தையும் ஏற்கவும்',
    rejectAll: 'அனைத்தையும் நிராகரிக்கவும்',
    moreOptions: 'மேலும் விருப்பங்கள்',
    savePreferences: 'விருப்பங்களைச் சேமிக்கவும்',
    back: 'பின்செல்',
    saving: 'சேமிக்கிறது…',
    viewFullNotice: 'முழு அறிவிப்பைக் காண்க',
    necessary: 'கண்டிப்பாகத் தேவையான குக்கீகள்',
    necessaryDesc: 'எப்போதும் செயலில். தளம் வேலை செய்ய தேவை — உள்நுழைவு, பாதுகாப்பு மற்றும் சம்மதப் பதிவுகள்.',
    alwaysActive: 'எப்போதும் செயலில்',
    functional: 'செயல்பாட்டு குக்கீகள்',
    functionalDesc: 'உங்கள் மொழி, சேர்ந்த படிப்புகள் மற்றும் கற்றல் விருப்பங்களை நினைவில் வைக்கும்.',
    analytics: 'செயல்திறன் & பகுப்பாய்வு குக்கீகள்',
    analyticsDesc: 'தளத்தை மேம்படுத்த படிப்புகள் எவ்வாறு பயன்படுத்தப்படுகின்றன என்பதைப் புரிந்துகொள்ள உதவுகிறது.',
    advertising: 'விளம்பர & சமூக ஊடக குக்கீகள்',
    advertisingDesc: 'பொருத்தமான படிப்பு பரிந்துரைகள் மற்றும் விளம்பரங்களைக் காட்ட கூட்டாளர்களால் பயன்படுத்தப்படுகிறது.',
    dataItemsLabel: 'தரவு உருப்படிகள்',
    servicesLabel: 'இயக்கப்பட்ட சேவைகள்',
    retentionLabel: 'தக்கவைப்பு',
    retentionDays: 'நாட்கள்',
    consentLabel: 'சம்மதம்',
    dpoLabel: 'தரவுப் பாதுகாப்பு அதிகாரி',
    withdrawLink: 'சம்மதத்தை விலக்கிக்கொள்',
    rightsLink: 'உங்கள் உரிமைகள்',
    grievanceLink: 'குறை தீர்வு',
    boardComplaintLink: 'குழு புகார்',
  },
  te: {
    bannerTitle: 'SkillLearnలో మీ గోప్యత ముఖ్యం',
    bannerText:
      'మీ అభ్యాస అనుభవాన్ని సురక్షితంగా ఉంచడానికి, మీ ప్రాధాన్యతలను గుర్తుంచుకోవడానికి మరియు కోర్సులు ఎలా ఉపయోగించబడుతున్నాయో అర్థం చేసుకోవడానికి మేము మరియు మా భాగస్వాములు కుకీలను ఉపయోగిస్తాము.',
    chooseLanguage: 'భాషను ఎంచుకోండి',
    acceptAll: 'అన్నింటినీ ఆమోదించండి',
    rejectAll: 'అన్నింటినీ తిరస్కరించండి',
    moreOptions: 'మరిన్ని ఎంపికలు',
    savePreferences: 'ప్రాధాన్యతలను సేవ్ చేయండి',
    back: 'వెనుకకు',
    saving: 'సేవ్ చేస్తోంది…',
    viewFullNotice: 'పూర్తి నోటీసును చూడండి',
    necessary: 'తప్పనిసరిగా అవసరమైన కుకీలు',
    necessaryDesc: 'ఎల్లప్పుడూ చురుకుగా ఉంటాయి. ప్లాట్‌ఫారమ్ పనిచేయడానికి అవసరం — సైన్-ఇన్, భద్రత మరియు సమ్మతి రికార్డులు.',
    alwaysActive: 'ఎల్లప్పుడూ చురుకుగా',
    functional: 'ఫంక్షనల్ కుకీలు',
    functionalDesc: 'మీ భాష, నమోదు చేసుకున్న కోర్సులు మరియు అభ్యాస ప్రాధాన్యతలను గుర్తుంచుకోండి.',
    analytics: 'పనితీరు & విశ్లేషణ కుకీలు',
    analyticsDesc: 'ప్లాట్‌ఫారమ్‌ను మెరుగుపరచడానికి కోర్సులు ఎలా ఉపయోగించబడుతున్నాయో అర్థం చేసుకోవడానికి సహాయపడుతుంది.',
    advertising: 'ప్రకటనలు & సోషల్ మీడియా కుకీలు',
    advertisingDesc: 'సంబంధిత కోర్సు సిఫార్సులు మరియు ప్రకటనలను చూపించడానికి భాగస్వాములు ఉపయోగిస్తారు.',
    dataItemsLabel: 'డేటా అంశాలు',
    servicesLabel: 'ప్రారంభించబడిన సేవలు',
    retentionLabel: 'నిలుపుదల',
    retentionDays: 'రోజులు',
    consentLabel: 'సమ్మతి',
    dpoLabel: 'డేటా రక్షణ అధికారి',
    withdrawLink: 'సమ్మతిని ఉపసంహరించుకోండి',
    rightsLink: 'మీ హక్కులు',
    grievanceLink: 'ఫిర్యాదు',
    boardComplaintLink: 'బోర్డు ఫిర్యాదు',
  },
  kn: {
    bannerTitle: 'SkillLearn ನಲ್ಲಿ ನಿಮ್ಮ ಗೌಪ್ಯತೆ ಮುಖ್ಯವಾಗಿದೆ',
    bannerText:
      'ನಿಮ್ಮ ಕಲಿಕೆಯ ಅನುಭವವನ್ನು ಸುರಕ್ಷಿತವಾಗಿಡಲು, ನಿಮ್ಮ ಆದ್ಯತೆಗಳನ್ನು ನೆನಪಿಡಲು ಮತ್ತು ಕೋರ್ಸ್‌ಗಳನ್ನು ಹೇಗೆ ಬಳಸಲಾಗುತ್ತದೆ ಎಂಬುದನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲು ನಾವು ಮತ್ತು ನಮ್ಮ ಪಾಲುದಾರರು ಕುಕೀಗಳನ್ನು ಬಳಸುತ್ತೇವೆ.',
    chooseLanguage: 'ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
    acceptAll: 'ಎಲ್ಲವನ್ನೂ ಸ್ವೀಕರಿಸಿ',
    rejectAll: 'ಎಲ್ಲವನ್ನೂ ತಿರಸ್ಕರಿಸಿ',
    moreOptions: 'ಹೆಚ್ಚಿನ ಆಯ್ಕೆಗಳು',
    savePreferences: 'ಆದ್ಯತೆಗಳನ್ನು ಉಳಿಸಿ',
    back: 'ಹಿಂದೆ',
    saving: 'ಉಳಿಸಲಾಗುತ್ತಿದೆ…',
    viewFullNotice: 'ಪೂರ್ಣ ಸೂಚನೆಯನ್ನು ವೀಕ್ಷಿಸಿ',
    necessary: 'ಕಟ್ಟುನಿಟ್ಟಾಗಿ ಅಗತ್ಯವಾದ ಕುಕೀಗಳು',
    necessaryDesc: 'ಯಾವಾಗಲೂ ಸಕ್ರಿಯ. ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಕಾರ್ಯನಿರ್ವಹಿಸಲು ಅಗತ್ಯ — ಸೈನ್-ಇನ್, ಸುರಕ್ಷತೆ ಮತ್ತು ಸಮ್ಮತಿ ದಾಖಲೆಗಳು.',
    alwaysActive: 'ಯಾವಾಗಲೂ ಸಕ್ರಿಯ',
    functional: 'ಕಾರ್ಯನಿರ್ವಹಣಾ ಕುಕೀಗಳು',
    functionalDesc: 'ನಿಮ್ಮ ಭಾಷೆ, ದಾಖಲಾದ ಕೋರ್ಸ್‌ಗಳು ಮತ್ತು ಕಲಿಕೆಯ ಆದ್ಯತೆಗಳನ್ನು ನೆನಪಿಡಿ.',
    analytics: 'ಕಾರ್ಯಕ್ಷಮತೆ ಮತ್ತು ವಿಶ್ಲೇಷಣೆ ಕುಕೀಗಳು',
    analyticsDesc: 'ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಅನ್ನು ಸುಧಾರಿಸಲು ಕೋರ್ಸ್‌ಗಳನ್ನು ಹೇಗೆ ಬಳಸಲಾಗುತ್ತದೆ ಎಂಬುದನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ.',
    advertising: 'ಜಾಹೀರಾತು ಮತ್ತು ಸಾಮಾಜಿಕ ಮಾಧ್ಯಮ ಕುಕೀಗಳು',
    advertisingDesc: 'ಸೂಕ್ತವಾದ ಕೋರ್ಸ್ ಶಿಫಾರಸುಗಳು ಮತ್ತು ಜಾಹೀರಾತುಗಳನ್ನು ತೋರಿಸಲು ಪಾಲುದಾರರು ಬಳಸುತ್ತಾರೆ.',
    dataItemsLabel: 'ಡೇಟಾ ಐಟಂಗಳು',
    servicesLabel: 'ಸಕ್ರಿಯಗೊಳಿಸಿದ ಸೇವೆಗಳು',
    retentionLabel: 'ಧಾರಣ',
    retentionDays: 'ದಿನಗಳು',
    consentLabel: 'ಸಮ್ಮತಿ',
    dpoLabel: 'ಡೇಟಾ ಸಂರಕ್ಷಣಾ ಅಧಿಕಾರಿ',
    withdrawLink: 'ಸಮ್ಮತಿಯನ್ನು ಹಿಂಪಡೆಯಿರಿ',
    rightsLink: 'ನಿಮ್ಮ ಹಕ್ಕುಗಳು',
    grievanceLink: 'ಕುಂದುಕೊರತೆ',
    boardComplaintLink: 'ಬೋರ್ಡ್ ದೂರು',
  },
  ml: {
    bannerTitle: 'SkillLearn-ൽ നിങ്ങളുടെ സ്വകാര്യത പ്രധാനമാണ്',
    bannerText:
      'നിങ്ങളുടെ പഠന അനുഭവം സുരക്ഷിതമായി സൂക്ഷിക്കാനും നിങ്ങളുടെ മുൻഗണനകൾ ഓർമ്മിക്കാനും കോഴ്‌സുകൾ എങ്ങനെ ഉപയോഗിക്കുന്നുവെന്ന് മനസ്സിലാക്കാനും ഞങ്ങളും ഞങ്ങളുടെ പങ്കാളികളും കുക്കികൾ ഉപയോഗിക്കുന്നു.',
    chooseLanguage: 'ഭാഷ തിരഞ്ഞെടുക്കുക',
    acceptAll: 'എല്ലാം സ്വീകരിക്കുക',
    rejectAll: 'എല്ലാം നിരസിക്കുക',
    moreOptions: 'കൂടുതൽ ഓപ്ഷനുകൾ',
    savePreferences: 'മുൻഗണനകൾ സംരക്ഷിക്കുക',
    back: 'തിരികെ',
    saving: 'സംരക്ഷിക്കുന്നു…',
    viewFullNotice: 'പൂർണ്ണ അറിയിപ്പ് കാണുക',
    necessary: 'കർശനമായി ആവശ്യമായ കുക്കികൾ',
    necessaryDesc: 'എപ്പോഴും സജീവം. പ്ലാറ്റ്‌ഫോം പ്രവർത്തിക്കാൻ ആവശ്യമാണ് — സൈൻ-ഇൻ, സുരക്ഷ, സമ്മത രേഖകൾ.',
    alwaysActive: 'എപ്പോഴും സജീവം',
    functional: 'ഫങ്ഷണൽ കുക്കികൾ',
    functionalDesc: 'നിങ്ങളുടെ ഭാഷ, എൻറോൾ ചെയ്ത കോഴ്‌സുകൾ, പഠന മുൻഗണനകൾ എന്നിവ ഓർമ്മിക്കുക.',
    analytics: 'പെർഫോമൻസ് & അനലിറ്റിക്സ് കുക്കികൾ',
    analyticsDesc: 'പ്ലാറ്റ്‌ഫോം മെച്ചപ്പെടുത്താൻ കോഴ്‌സുകൾ എങ്ങനെ ഉപയോഗിക്കുന്നുവെന്ന് മനസ്സിലാക്കാൻ സഹായിക്കുന്നു.',
    advertising: 'പരസ്യ & സോഷ്യൽ മീഡിയ കുക്കികൾ',
    advertisingDesc: 'പ്രസക്തമായ കോഴ്‌സ് ശുപാർശകളും പരസ്യങ്ങളും കാണിക്കാൻ പങ്കാളികൾ ഉപയോഗിക്കുന്നു.',
    dataItemsLabel: 'ഡാറ്റാ ഇനങ്ങൾ',
    servicesLabel: 'സജീവമാക്കിയ സേവനങ്ങൾ',
    retentionLabel: 'നിലനിർത്തൽ',
    retentionDays: 'ദിവസങ്ങൾ',
    consentLabel: 'സമ്മതം',
    dpoLabel: 'ഡാറ്റാ സംരക്ഷണ ഓഫീസർ',
    withdrawLink: 'സമ്മതം പിൻവലിക്കുക',
    rightsLink: 'നിങ്ങളുടെ അവകാശങ്ങൾ',
    grievanceLink: 'പരാതി',
    boardComplaintLink: 'ബോർഡ് പരാതി',
  },
  bn: {
    bannerTitle: 'SkillLearn-এ আপনার গোপনীয়তা গুরুত্বপূর্ণ',
    bannerText:
      'আপনার শেখার অভিজ্ঞতা সুরক্ষিত রাখতে, আপনার পছন্দ মনে রাখতে এবং কোর্সগুলি কীভাবে ব্যবহৃত হয় তা বুঝতে আমরা এবং আমাদের অংশীদাররা কুকি ব্যবহার করি।',
    chooseLanguage: 'ভাষা নির্বাচন করুন',
    acceptAll: 'সব গ্রহণ করুন',
    rejectAll: 'সব প্রত্যাখ্যান করুন',
    moreOptions: 'আরও বিকল্প',
    savePreferences: 'পছন্দগুলি সংরক্ষণ করুন',
    back: 'ফিরে যান',
    saving: 'সংরক্ষণ করা হচ্ছে…',
    viewFullNotice: 'সম্পূর্ণ নোটিশ দেখুন',
    necessary: 'কঠোরভাবে প্রয়োজনীয় কুকি',
    necessaryDesc: 'সর্বদা সক্রিয়। প্ল্যাটফর্ম কাজ করতে প্রয়োজন — সাইন-ইন, নিরাপত্তা এবং সম্মতি রেকর্ড।',
    alwaysActive: 'সর্বদা সক্রিয়',
    functional: 'ফাংশনাল কুকি',
    functionalDesc: 'আপনার ভাষা, নথিভুক্ত কোর্স এবং শেখার পছন্দ মনে রাখুন।',
    analytics: 'পারফরম্যান্স ও বিশ্লেষণ কুকি',
    analyticsDesc: 'প্ল্যাটফর্ম উন্নত করতে কোর্সগুলি কীভাবে ব্যবহৃত হয় তা বুঝতে সাহায্য করে।',
    advertising: 'বিজ্ঞাপন ও সোশ্যাল মিডিয়া কুকি',
    advertisingDesc: 'প্রাসঙ্গিক কোর্স সুপারিশ এবং বিজ্ঞাপন দেখাতে অংশীদারদের দ্বারা ব্যবহৃত হয়।',
    dataItemsLabel: 'ডেটা আইটেম',
    servicesLabel: 'সক্রিয় পরিষেবা',
    retentionLabel: 'সংরক্ষণকাল',
    retentionDays: 'দিন',
    consentLabel: 'সম্মতি',
    dpoLabel: 'ডেটা সুরক্ষা কর্মকর্তা',
    withdrawLink: 'সম্মতি প্রত্যাহার করুন',
    rightsLink: 'আপনার অধিকার',
    grievanceLink: 'অভিযোগ',
    boardComplaintLink: 'বোর্ড অভিযোগ',
  },
  mr: {
    bannerTitle: 'SkillLearn वर तुमची गोपनीयता महत्त्वाची आहे',
    bannerText:
      'तुमचा शिकण्याचा अनुभव सुरक्षित ठेवण्यासाठी, तुमच्या प्राधान्यांची आठवण ठेवण्यासाठी आणि अभ्यासक्रम कसे वापरले जातात हे समजून घेण्यासाठी आम्ही आणि आमचे भागीदार कुकीज वापरतो.',
    chooseLanguage: 'भाषा निवडा',
    acceptAll: 'सर्व स्वीकारा',
    rejectAll: 'सर्व नाकारा',
    moreOptions: 'अधिक पर्याय',
    savePreferences: 'प्राधान्ये जतन करा',
    back: 'मागे',
    saving: 'जतन करत आहे…',
    viewFullNotice: 'संपूर्ण सूचना पहा',
    necessary: 'कडक आवश्यक कुकीज',
    necessaryDesc: 'नेहमी सक्रिय. प्लॅटफॉर्म काम करण्यासाठी आवश्यक — साइन-इन, सुरक्षा आणि संमती नोंदी.',
    alwaysActive: 'नेहमी सक्रिय',
    functional: 'कार्यात्मक कुकीज',
    functionalDesc: 'तुमची भाषा, नोंदणीकृत अभ्यासक्रम आणि शिकण्याची प्राधान्ये लक्षात ठेवा.',
    analytics: 'कार्यप्रदर्शन आणि विश्लेषण कुकीज',
    analyticsDesc: 'प्लॅटफॉर्म सुधारण्यासाठी अभ्यासक्रम कसे वापरले जातात हे समजून घेण्यास मदत करते.',
    advertising: 'जाहिरात आणि सोशल मीडिया कुकीज',
    advertisingDesc: 'संबंधित अभ्यासक्रम शिफारसी आणि जाहिराती दाखवण्यासाठी भागीदार वापरतात.',
    dataItemsLabel: 'डेटा आयटम',
    servicesLabel: 'सक्रिय केलेल्या सेवा',
    retentionLabel: 'धारणा',
    retentionDays: 'दिवस',
    consentLabel: 'संमती',
    dpoLabel: 'डेटा संरक्षण अधिकारी',
    withdrawLink: 'संमती मागे घ्या',
    rightsLink: 'तुमचे हक्क',
    grievanceLink: 'तक्रार',
    boardComplaintLink: 'मंडळ तक्रार',
  },
  gu: {
    bannerTitle: 'SkillLearn પર તમારી ગોપનીયતા મહત્વપૂર્ણ છે',
    bannerText:
      'તમારા શીખવાના અનુભવને સુરક્ષિત રાખવા, તમારી પસંદગીઓ યાદ રાખવા અને અભ્યાસક્રમોનો ઉપયોગ કેવી રીતે થાય છે તે સમજવા માટે અમે અને અમારા ભાગીદારો કૂકીઝનો ઉપયોગ કરીએ છીએ.',
    chooseLanguage: 'ભાષા પસંદ કરો',
    acceptAll: 'બધું સ્વીકારો',
    rejectAll: 'બધું નકારો',
    moreOptions: 'વધુ વિકલ્પો',
    savePreferences: 'પસંદગીઓ સાચવો',
    back: 'પાછળ',
    saving: 'સાચવી રહ્યું છે…',
    viewFullNotice: 'સંપૂર્ણ સૂચના જુઓ',
    necessary: 'સખત જરૂરી કૂકીઝ',
    necessaryDesc: 'હંમેશા સક્રિય. પ્લેટફોર્મ કામ કરવા માટે જરૂરી — સાઇન-ઇન, સુરક્ષા અને સંમતિ રેકોર્ડ્સ.',
    alwaysActive: 'હંમેશા સક્રિય',
    functional: 'ફંક્શનલ કૂકીઝ',
    functionalDesc: 'તમારી ભાષા, નોંધાયેલા અભ્યાસક્રમો અને શીખવાની પસંદગીઓ યાદ રાખો.',
    analytics: 'પ્રદર્શન અને વિશ્લેષણ કૂકીઝ',
    analyticsDesc: 'પ્લેટફોર્મ સુધારવા માટે અભ્યાસક્રમોનો ઉપયોગ કેવી રીતે થાય છે તે સમજવામાં મદદ કરે છે.',
    advertising: 'જાહેરાત અને સોશિયલ મીડિયા કૂકીઝ',
    advertisingDesc: 'સંબંધિત અભ્યાસક્રમ ભલામણો અને જાહેરાતો બતાવવા માટે ભાગીદારો દ્વારા ઉપયોગ થાય છે.',
    dataItemsLabel: 'ડેટા આઇટમ્સ',
    servicesLabel: 'સક્રિય કરેલી સેવાઓ',
    retentionLabel: 'જાળવણી',
    retentionDays: 'દિવસો',
    consentLabel: 'સંમતિ',
    dpoLabel: 'ડેટા સંરક્ષણ અધિકારી',
    withdrawLink: 'સંમતિ પાછી ખેંચો',
    rightsLink: 'તમારા અધિકારો',
    grievanceLink: 'ફરિયાદ',
    boardComplaintLink: 'બોર્ડ ફરિયાદ',
  },
  pa: {
    bannerTitle: 'SkillLearn ਤੇ ਤੁਹਾਡੀ ਪਰਦੇਦਾਰੀ ਮਹੱਤਵਪੂਰਨ ਹੈ',
    bannerText:
      'ਤੁਹਾਡੇ ਸਿੱਖਣ ਦੇ ਤਜਰਬੇ ਨੂੰ ਸੁਰੱਖਿਅਤ ਰੱਖਣ, ਤੁਹਾਡੀਆਂ ਤਰਜੀਹਾਂ ਯਾਦ ਰੱਖਣ ਅਤੇ ਕੋਰਸ ਕਿਵੇਂ ਵਰਤੇ ਜਾਂਦੇ ਹਨ ਇਹ ਸਮਝਣ ਲਈ ਅਸੀਂ ਅਤੇ ਸਾਡੇ ਸਾਥੀ ਕੂਕੀਜ਼ ਦੀ ਵਰਤੋਂ ਕਰਦੇ ਹਾਂ।',
    chooseLanguage: 'ਭਾਸ਼ਾ ਚੁਣੋ',
    acceptAll: 'ਸਭ ਸਵੀਕਾਰ ਕਰੋ',
    rejectAll: 'ਸਭ ਰੱਦ ਕਰੋ',
    moreOptions: 'ਹੋਰ ਵਿਕਲਪ',
    savePreferences: 'ਤਰਜੀਹਾਂ ਸੰਭਾਲੋ',
    back: 'ਪਿੱਛੇ',
    saving: 'ਸੰਭਾਲਿਆ ਜਾ ਰਿਹਾ ਹੈ…',
    viewFullNotice: 'ਪੂਰਾ ਨੋਟਿਸ ਵੇਖੋ',
    necessary: 'ਸਖ਼ਤ ਲੋੜੀਂਦੀਆਂ ਕੁਕੀਜ਼',
    necessaryDesc: 'ਹਮੇਸ਼ਾ ਸਰਗਰਮ। ਪਲੇਟਫਾਰਮ ਦੇ ਕੰਮ ਕਰਨ ਲਈ ਲੋੜੀਂਦੀਆਂ — ਸਾਈਨ-ਇਨ, ਸੁਰੱਖਿਆ ਅਤੇ ਸਹਿਮਤੀ ਰਿਕਾਰਡ।',
    alwaysActive: 'ਹਮੇਸ਼ਾ ਸਰਗਰਮ',
    functional: 'ਕਾਰਜਸ਼ੀਲ ਕੁਕੀਜ਼',
    functionalDesc: 'ਤੁਹਾਡੀ ਭਾਸ਼ਾ, ਦਾਖਲ ਕੀਤੇ ਕੋਰਸ ਅਤੇ ਸਿੱਖਣ ਦੀਆਂ ਤਰਜੀਹਾਂ ਯਾਦ ਰੱਖੋ।',
    analytics: 'ਪ੍ਰਦਰਸ਼ਨ ਅਤੇ ਵਿਸ਼ਲੇਸ਼ਣ ਕੁਕੀਜ਼',
    analyticsDesc: 'ਪਲੇਟਫਾਰਮ ਨੂੰ ਬਿਹਤਰ ਬਣਾਉਣ ਲਈ ਕੋਰਸ ਕਿਵੇਂ ਵਰਤੇ ਜਾਂਦੇ ਹਨ ਇਹ ਸਮਝਣ ਵਿੱਚ ਮਦਦ ਕਰਦੀ ਹੈ।',
    advertising: 'ਵਿਗਿਆਪਨ ਅਤੇ ਸੋਸ਼ਲ ਮੀਡੀਆ ਕੁਕੀਜ਼',
    advertisingDesc: 'ਸੰਬੰਧਿਤ ਕੋਰਸ ਸਿਫਾਰਸ਼ਾਂ ਅਤੇ ਵਿਗਿਆਪਨ ਦਿਖਾਉਣ ਲਈ ਸਾਥੀਆਂ ਦੁਆਰਾ ਵਰਤਿਆ ਜਾਂਦਾ ਹੈ।',
    dataItemsLabel: 'ਡੇਟਾ ਆਈਟਮਾਂ',
    servicesLabel: 'ਸਰਗਰਮ ਸੇਵਾਵਾਂ',
    retentionLabel: 'ਧਾਰਨ',
    retentionDays: 'ਦਿਨ',
    consentLabel: 'ਸਹਿਮਤੀ',
    dpoLabel: 'ਡੇਟਾ ਸੁਰੱਖਿਆ ਅਧਿਕਾਰੀ',
    withdrawLink: 'ਸਹਿਮਤੀ ਵਾਪਸ ਲਵੋ',
    rightsLink: 'ਤੁਹਾਡੇ ਅਧਿਕਾਰ',
    grievanceLink: 'ਸ਼ਿਕਾਇਤ',
    boardComplaintLink: 'ਬੋਰਡ ਸ਼ਿਕਾਇਤ',
  },
}
