export interface BannerCopy {
  bannerTitle: string
  bannerText: string
  acceptAll: string
  rejectAll: string
  moreOptions: string
  modalTitle: string
  chooseLanguage: string
  languageNote: string
  necessary: string
  necessaryDesc: string
  functional: string
  functionalDesc: string
  analytics: string
  analyticsDesc: string
  advertising: string
  advertisingDesc: string
  save: string
  cancel: string
  close: string
  dataItemsLabel: string
  servicesLabel: string
  retentionLabel: string
  retentionDays: string
  consentLabel: string
  dpoLabel: string
  withdrawLink: string
  rightsLink: string
  grievanceLink: string
  boardComplaintLink: string
  viewFullNotice: string
}

const ALL_LANGUAGES_NOTE = 'Available in: English, Hindi, Kannada, Malayalam, Tamil, Telugu, Bengali, Gujarati, Marathi, Punjabi, Odia, Assamese, Nepali, Sindhi, Urdu, Dogri, Kashmiri, Konkani, Maithili, Bodo, Manipuri, Sanskrit, Santali'

export const BANNER_COPY: Record<string, BannerCopy> = {
  en: {
    bannerTitle: 'Your privacy is important to us',
    bannerText:
      'We and our partners use cookies to keep this portal secure, remember your preferences, and understand how it is used. Manage your choices below.',
    acceptAll: 'Accept consent',
    rejectAll: 'Reject all',
    moreOptions: 'More options',
    modalTitle: 'Consent preferences',
    chooseLanguage: 'Choose language',
    languageNote: ALL_LANGUAGES_NOTE,
    necessary: 'Strictly necessary cookies',
    necessaryDesc: 'Always active. Required for the portal to work — login, security and consent records.',
    functional: 'Functional cookies',
    functionalDesc: 'Remember your language and personal preferences.',
    analytics: 'Performance & analytics cookies',
    analyticsDesc: 'Help us understand how the portal is used so we can improve it.',
    advertising: 'Advertising & social media cookies',
    advertisingDesc: 'Used by partners to show relevant advertising.',
    save: 'Save preferences',
    cancel: 'Cancel',
    close: 'Close',
    dataItemsLabel: 'Data items',
    servicesLabel: 'Services enabled',
    retentionLabel: 'Retention',
    retentionDays: 'days',
    consentLabel: 'Consent',
    dpoLabel: 'Data Protection Officer',
    withdrawLink: 'Withdraw consent',
    rightsLink: 'Your rights',
    grievanceLink: 'Grievance',
    boardComplaintLink: 'Board complaint',
    viewFullNotice: 'View full notice',
  },
  ta: {
    bannerTitle: 'உங்கள் தனியுரிமை எங்களுக்கு முக்கியம்',
    bannerText:
      'இந்த போர்ட்டலைப் பாதுகாப்பாக வைத்திருக்கவும், உங்கள் விருப்பங்களை நினைவில் வைக்கவும், அது எவ்வாறு பயன்படுத்தப்படுகிறது என்பதைப் புரிந்துகொள்ளவும் நாங்கள் குக்கீகளைப் பயன்படுத்துகிறோம். உங்கள் தேர்வுகளை கீழே நிர்வகிக்கவும்.',
    acceptAll: 'சம்மதத்தை ஏற்கவும்',
    rejectAll: 'அனைத்தையும் நிராகரிக்கவும்',
    moreOptions: 'மேலும் விருப்பங்கள்',
    modalTitle: 'சம்மத விருப்பங்கள்',
    chooseLanguage: 'மொழியைத் தேர்ந்தெடுக்கவும்',
    languageNote: ALL_LANGUAGES_NOTE,
    necessary: 'கண்டிப்பாகத் தேவையான குக்கீகள்',
    necessaryDesc: 'எப்போதும் செயலில். போர்ட்டல் வேலை செய்ய தேவை — உள்நுழைவு, பாதுகாப்பு மற்றும் சம்மதப் பதிவுகள்.',
    functional: 'செயல்பாட்டு குக்கீகள்',
    functionalDesc: 'உங்கள் மொழி மற்றும் தனிப்பட்ட விருப்பங்களை நினைவில் வைக்கும்.',
    analytics: 'செயல்திறன் & பகுப்பாய்வு குக்கீகள்',
    analyticsDesc: 'போர்ட்டலை மேம்படுத்த அது எவ்வாறு பயன்படுத்தப்படுகிறது என்பதைப் புரிந்துகொள்ள உதவுகிறது.',
    advertising: 'விளம்பர & சமூக ஊடக குக்கீகள்',
    advertisingDesc: 'பொருத்தமான விளம்பரங்களைக் காட்ட கூட்டாளர்களால் பயன்படுத்தப்படுகிறது.',
    save: 'விருப்பங்களைச் சேமிக்கவும்',
    cancel: 'ரத்து செய்',
    close: 'மூடு',
    dataItemsLabel: 'தரவு உருப்படிகள்',
    servicesLabel: 'இயக்கப்பட்ட சேவைகள்',
    retentionLabel: 'தக்கவைப்பு',
    retentionDays: 'நாட்கள்',
    consentLabel: 'சம்மதம்',
    dpoLabel: 'தரவுப் பாதுகாப்பு அதிகாரி',
    withdrawLink: 'சம்மதத்தை விலக்கிக்கொள்',
    rightsLink: 'உங்கள் உரிமைகள்',
    grievanceLink: 'குறை தீர்வு',
    boardComplaintLink: 'குழு புகார்',
    viewFullNotice: 'முழு அறிவிப்பைக் காண்க',
  },
  hi: {
    bannerTitle: 'आपकी गोपनीयता हमारे लिए महत्वपूर्ण है',
    bannerText:
      'हम इस पोर्टल को सुरक्षित रखने, आपकी प्राथमिकताओं को याद रखने और यह समझने के लिए कुकीज़ का उपयोग करते हैं कि इसका उपयोग कैसे किया जाता है। अपनी पसंद नीचे प्रबंधित करें।',
    acceptAll: 'सहमति स्वीकार करें',
    rejectAll: 'सभी अस्वीकार करें',
    moreOptions: 'अधिक विकल्प',
    modalTitle: 'सहमति प्राथमिकताएं',
    chooseLanguage: 'भाषा चुनें',
    languageNote: ALL_LANGUAGES_NOTE,
    necessary: 'कड़ाई से आवश्यक कुकीज़',
    necessaryDesc: 'हमेशा सक्रिय। पोर्टल के काम करने के लिए आवश्यक — लॉगिन, सुरक्षा और सहमति रिकॉर्ड।',
    functional: 'कार्यात्मक कुकीज़',
    functionalDesc: 'आपकी भाषा और व्यक्तिगत प्राथमिकताओं को याद रखें।',
    analytics: 'प्रदर्शन और विश्लेषण कुकीज़',
    analyticsDesc: 'यह समझने में मदद करें कि पोर्टल का उपयोग कैसे किया जाता है ताकि इसे बेहतर बनाया जा सके।',
    advertising: 'विज्ञापन और सोशल मीडिया कुकीज़',
    advertisingDesc: 'प्रासंगिक विज्ञापन दिखाने के लिए भागीदारों द्वारा उपयोग किया जाता है।',
    save: 'प्राथमिकताएं सहेजें',
    cancel: 'रद्द करें',
    close: 'बंद करें',
    dataItemsLabel: 'डेटा आइटम',
    servicesLabel: 'सक्षम सेवाएं',
    retentionLabel: 'प्रतिधारण',
    retentionDays: 'दिन',
    consentLabel: 'सहमति',
    dpoLabel: 'डेटा संरक्षण अधिकारी',
    withdrawLink: 'सहमति वापस लें',
    rightsLink: 'आपके अधिकार',
    grievanceLink: 'शिकायत',
    boardComplaintLink: 'बोर्ड शिकायत',
    viewFullNotice: 'पूरा नोटिस देखें',
  },
  kn: {
    bannerTitle: 'ನಿಮ್ಮ ಗೌಪ್ಯತೆ ನಮಗೆ ಮುಖ್ಯ',
    bannerText:
      'ಈ ಪೋರ್ಟಲ್ ಅನ್ನು ಸುರಕ್ಷಿತವಾಗಿಡಲು, ನಿಮ್ಮ ಆದ್ಯತೆಗಳನ್ನು ನೆನಪಿಡಲು ಮತ್ತು ಅದನ್ನು ಹೇಗೆ ಬಳಸಲಾಗುತ್ತದೆ ಎಂಬುದನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲು ನಾವು ಕುಕೀಗಳನ್ನು ಬಳಸುತ್ತೇವೆ. ನಿಮ್ಮ ಆಯ್ಕೆಗಳನ್ನು ಕೆಳಗೆ ನಿರ್ವಹಿಸಿ.',
    acceptAll: 'ಸಮ್ಮತಿಯನ್ನು ಸ್ವೀಕರಿಸಿ',
    rejectAll: 'ಎಲ್ಲವನ್ನೂ ತಿರಸ್ಕರಿಸಿ',
    moreOptions: 'ಹೆಚ್ಚಿನ ಆಯ್ಕೆಗಳು',
    modalTitle: 'ಸಮ್ಮತಿ ಆದ್ಯತೆಗಳು',
    chooseLanguage: 'ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
    languageNote: ALL_LANGUAGES_NOTE,
    necessary: 'ಕಟ್ಟುನಿಟ್ಟಾಗಿ ಅಗತ್ಯವಾದ ಕುಕೀಗಳು',
    necessaryDesc: 'ಯಾವಾಗಲೂ ಸಕ್ರಿಯ. ಪೋರ್ಟಲ್ ಕಾರ್ಯನಿರ್ವಹಿಸಲು ಅಗತ್ಯ — ಲಾಗಿನ್, ಸುರಕ್ಷತೆ ಮತ್ತು ಸಮ್ಮತಿ ದಾಖಲೆಗಳು.',
    functional: 'ಕಾರ್ಯನಿರ್ವಹಣಾ ಕುಕೀಗಳು',
    functionalDesc: 'ನಿಮ್ಮ ಭಾಷೆ ಮತ್ತು ವೈಯಕ್ತಿಕ ಆದ್ಯತೆಗಳನ್ನು ನೆನಪಿಡಿ.',
    analytics: 'ಕಾರ್ಯಕ್ಷಮತೆ ಮತ್ತು ವಿಶ್ಲೇಷಣೆ ಕುಕೀಗಳು',
    analyticsDesc: 'ಪೋರ್ಟಲ್ ಅನ್ನು ಸುಧಾರಿಸಲು ಅದನ್ನು ಹೇಗೆ ಬಳಸಲಾಗುತ್ತದೆ ಎಂಬುದನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ.',
    advertising: 'ಜಾಹೀರಾತು ಮತ್ತು ಸಾಮಾಜಿಕ ಮಾಧ್ಯಮ ಕುಕೀಗಳು',
    advertisingDesc: 'ಸೂಕ್ತ ಜಾಹೀರಾತುಗಳನ್ನು ತೋರಿಸಲು ಪಾಲುದಾರರು ಬಳಸುತ್ತಾರೆ.',
    save: 'ಆದ್ಯತೆಗಳನ್ನು ಉಳಿಸಿ',
    cancel: 'ರದ್ದುಮಾಡಿ',
    close: 'ಮುಚ್ಚಿ',
    dataItemsLabel: 'ಡೇಟಾ ಐಟಂಗಳು',
    servicesLabel: 'ಸಕ್ರಿಯಗೊಳಿಸಿದ ಸೇವೆಗಳು',
    retentionLabel: 'ಧಾರಣ',
    retentionDays: 'ದಿನಗಳು',
    consentLabel: 'ಸಮ್ಮತಿ',
    dpoLabel: 'ಡೇಟಾ ಸಂರಕ್ಷಣಾ ಅಧಿಕಾರಿ',
    withdrawLink: 'ಸಮ್ಮತಿಯನ್ನು ಹಿಂಪಡೆಯಿರಿ',
    rightsLink: 'ನಿಮ್ಮ ಹಕ್ಕುಗಳು',
    grievanceLink: 'ಕುಂದುಕೊರತೆ',
    boardComplaintLink: 'ಬೋರ್ಡ್ ದೂರು',
    viewFullNotice: 'ಪೂರ್ಣ ಸೂಚನೆಯನ್ನು ವೀಕ್ಷಿಸಿ',
  },
  ml: {
    bannerTitle: 'നിങ്ങളുടെ സ്വകാര്യത ഞങ്ങൾക്ക് പ്രധാനമാണ്',
    bannerText:
      'ഈ പോർട്ടൽ സുരക്ഷിതമായി സൂക്ഷിക്കുന്നതിനും നിങ്ങളുടെ മുൻഗണനകൾ ഓർമ്മിക്കുന്നതിനും അത് എങ്ങനെ ഉപയോഗിക്കുന്നു എന്ന് മനസ്സിലാക്കുന്നതിനും ഞങ്ങൾ കുക്കികൾ ഉപയോഗിക്കുന്നു. നിങ്ങളുടെ തിരഞ്ഞെടുപ്പുകൾ ചുവടെ നിയന്ത്രിക്കുക.',
    acceptAll: 'സമ്മതം സ്വീകരിക്കുക',
    rejectAll: 'എല്ലാം നിരസിക്കുക',
    moreOptions: 'കൂടുതൽ ഓപ്ഷനുകൾ',
    modalTitle: 'സമ്മത മുൻഗണനകൾ',
    chooseLanguage: 'ഭാഷ തിരഞ്ഞെടുക്കുക',
    languageNote: ALL_LANGUAGES_NOTE,
    necessary: 'കർശനമായി ആവശ്യമായ കുക്കികൾ',
    necessaryDesc: 'എപ്പോഴും സജീവം. പോർട്ടൽ പ്രവർത്തിക്കാൻ ആവശ്യമാണ് — ലോഗിൻ, സുരക്ഷ, സമ്മത രേഖകൾ.',
    functional: 'ഫങ്ഷണൽ കുക്കികൾ',
    functionalDesc: 'നിങ്ങളുടെ ഭാഷയും വ്യക്തിഗത മുൻഗണനകളും ഓർമ്മിക്കുക.',
    analytics: 'പെർഫോമൻസ് & അനലിറ്റിക്സ് കുക്കികൾ',
    analyticsDesc: 'പോർട്ടൽ എങ്ങനെ ഉപയോഗിക്കുന്നു എന്ന് മനസ്സിലാക്കി അത് മെച്ചപ്പെടുത്താൻ സഹായിക്കുന്നു.',
    advertising: 'പരസ്യ & സോഷ്യൽ മീഡിയ കുക്കികൾ',
    advertisingDesc: 'പ്രസക്തമായ പരസ്യങ്ങൾ കാണിക്കാൻ പങ്കാളികൾ ഉപയോഗിക്കുന്നു.',
    save: 'മുൻഗണനകൾ സംരക്ഷിക്കുക',
    cancel: 'റദ്ദാക്കുക',
    close: 'അടയ്ക്കുക',
    dataItemsLabel: 'ഡാറ്റാ ഇനങ്ങൾ',
    servicesLabel: 'സജീവമാക്കിയ സേവനങ്ങൾ',
    retentionLabel: 'നിലനിർത്തൽ',
    retentionDays: 'ദിവസങ്ങൾ',
    consentLabel: 'സമ്മതം',
    dpoLabel: 'ഡാറ്റാ സംരക്ഷണ ഓഫീസർ',
    withdrawLink: 'സമ്മതം പിൻവലിക്കുക',
    rightsLink: 'നിങ്ങളുടെ അവകാശങ്ങൾ',
    grievanceLink: 'പരാതി',
    boardComplaintLink: 'ബോർഡ് പരാതി',
    viewFullNotice: 'പൂർണ്ണ അറിയിപ്പ് കാണുക',
  },
  te: {
    bannerTitle: 'మీ గోప్యత మాకు ముఖ్యం',
    bannerText:
      'ఈ పోర్టల్‌ను సురక్షితంగా ఉంచడానికి, మీ ప్రాధాన్యతలను గుర్తుంచుకోవడానికి మరియు దానిని ఎలా ఉపయోగిస్తున్నారో అర్థం చేసుకోవడానికి మేము కుకీలను ఉపయోగిస్తాము. మీ ఎంపికలను క్రింద నిర్వహించండి.',
    acceptAll: 'సమ్మతిని ఆమోదించండి',
    rejectAll: 'అన్నింటినీ తిరస్కరించండి',
    moreOptions: 'మరిన్ని ఎంపికలు',
    modalTitle: 'సమ్మతి ప్రాధాన్యతలు',
    chooseLanguage: 'భాషను ఎంచుకోండి',
    languageNote: ALL_LANGUAGES_NOTE,
    necessary: 'తప్పనిసరిగా అవసరమైన కుకీలు',
    necessaryDesc: 'ఎల్లప్పుడూ చురుకుగా ఉంటాయి. పోర్టల్ పనిచేయడానికి అవసరం — లాగిన్, భద్రత మరియు సమ్మతి రికార్డులు.',
    functional: 'ఫంక్షనల్ కుకీలు',
    functionalDesc: 'మీ భాష మరియు వ్యక్తిగత ప్రాధాన్యతలను గుర్తుంచుకోండి.',
    analytics: 'పనితీరు & విశ్లేషణ కుకీలు',
    analyticsDesc: 'పోర్టల్‌ను మెరుగుపరచడానికి దానిని ఎలా ఉపయోగిస్తున్నారో అర్థం చేసుకోవడానికి సహాయపడుతుంది.',
    advertising: 'ప్రకటనలు & సోషల్ మీడియా కుకీలు',
    advertisingDesc: 'సంబంధిత ప్రకటనలను చూపించడానికి భాగస్వాములు ఉపయోగిస్తారు.',
    save: 'ప్రాధాన్యతలను సేవ్ చేయండి',
    cancel: 'రద్దు చేయండి',
    close: 'మూసివేయండి',
    dataItemsLabel: 'డేటా అంశాలు',
    servicesLabel: 'ప్రారంభించబడిన సేవలు',
    retentionLabel: 'నిలుపుదల',
    retentionDays: 'రోజులు',
    consentLabel: 'సమ్మతి',
    dpoLabel: 'డేటా రక్షణ అధికారి',
    withdrawLink: 'సమ్మతిని ఉపసంహరించుకోండి',
    rightsLink: 'మీ హక్కులు',
    grievanceLink: 'ఫిర్యాదు',
    boardComplaintLink: 'బోర్డు ఫిర్యాదు',
    viewFullNotice: 'పూర్తి నోటీసును చూడండి',
  },
  bn: {
    bannerTitle: 'আপনার গোপনীয়তা আমাদের কাছে গুরুত্বপূর্ণ',
    bannerText:
      'এই পোর্টালকে নিরাপদ রাখতে, আপনার পছন্দগুলি মনে রাখতে এবং এটি কীভাবে ব্যবহৃত হয় তা বুঝতে আমরা এবং আমাদের অংশীদাররা কুকি ব্যবহার করি। নিচে আপনার পছন্দগুলি পরিচালনা করুন।',
    acceptAll: 'সম্মতি গ্রহণ করুন',
    rejectAll: 'সব প্রত্যাখ্যান করুন',
    moreOptions: 'আরও বিকল্প',
    modalTitle: 'সম্মতি পছন্দসমূহ',
    chooseLanguage: 'ভাষা নির্বাচন করুন',
    languageNote: ALL_LANGUAGES_NOTE,
    necessary: 'কঠোরভাবে প্রয়োজনীয় কুকি',
    necessaryDesc: 'সর্বদা সক্রিয়। পোর্টাল কাজ করতে প্রয়োজন — লগইন, নিরাপত্তা এবং সম্মতি রেকর্ড।',
    functional: 'ফাংশনাল কুকি',
    functionalDesc: 'আপনার ভাষা এবং ব্যক্তিগত পছন্দগুলি মনে রাখুন।',
    analytics: 'পারফরম্যান্স ও বিশ্লেষণ কুকি',
    analyticsDesc: 'পোর্টাল কীভাবে ব্যবহৃত হয় তা বুঝে এটি উন্নত করতে সাহায্য করে।',
    advertising: 'বিজ্ঞাপন ও সোশ্যাল মিডিয়া কুকি',
    advertisingDesc: 'প্রাসঙ্গিক বিজ্ঞাপন দেখাতে অংশীদারদের দ্বারা ব্যবহৃত হয়।',
    save: 'পছন্দগুলি সংরক্ষণ করুন',
    cancel: 'বাতিল করুন',
    close: 'বন্ধ করুন',
    dataItemsLabel: 'ডেটা আইটেম',
    servicesLabel: 'সক্রিয় পরিষেবা',
    retentionLabel: 'সংরক্ষণকাল',
    retentionDays: 'দিন',
    consentLabel: 'সম্মতি',
    dpoLabel: 'ডেটা সুরক্ষা কর্মকর্তা',
    withdrawLink: 'সম্মতি প্রত্যাহার করুন',
    rightsLink: 'আপনার অধিকার',
    grievanceLink: 'অভিযোগ',
    boardComplaintLink: 'বোর্ড অভিযোগ',
    viewFullNotice: 'সম্পূর্ণ নোটিশ দেখুন',
  },
  gu: {
    bannerTitle: 'તમારી ગોપનીયતા અમારા માટે મહત્વપૂર્ણ છે',
    bannerText:
      'આ પોર્ટલને સુરક્ષિત રાખવા, તમારી પસંદગીઓ યાદ રાખવા અને તેનો કેવી રીતે ઉપયોગ થાય છે તે સમજવા માટે અમે અને અમારા ભાગીદારો કૂકીઝનો ઉપયોગ કરીએ છીએ. નીચે તમારી પસંદગીઓ મેનેજ કરો.',
    acceptAll: 'સંમતિ સ્વીકારો',
    rejectAll: 'બધું નકારો',
    moreOptions: 'વધુ વિકલ્પો',
    modalTitle: 'સંમતિ પસંદગીઓ',
    chooseLanguage: 'ભાષા પસંદ કરો',
    languageNote: ALL_LANGUAGES_NOTE,
    necessary: 'સખત જરૂરી કૂકીઝ',
    necessaryDesc: 'હંમેશા સક્રિય. પોર્ટલ કામ કરવા માટે જરૂરી — લોગિન, સુરક્ષા અને સંમતિ રેકોર્ડ્સ.',
    functional: 'ફંક્શનલ કૂકીઝ',
    functionalDesc: 'તમારી ભાષા અને વ્યક્તિગત પસંદગીઓ યાદ રાખો.',
    analytics: 'પ્રદર્શન અને વિશ્લેષણ કૂકીઝ',
    analyticsDesc: 'પોર્ટલને સુધારવા માટે તેનો કેવી રીતે ઉપયોગ થાય છે તે સમજવામાં મદદ કરે છે.',
    advertising: 'જાહેરાત અને સોશિયલ મીડિયા કૂકીઝ',
    advertisingDesc: 'સંબંધિત જાહેરાતો બતાવવા માટે ભાગીદારો દ્વારા ઉપયોગ થાય છે.',
    save: 'પસંદગીઓ સાચવો',
    cancel: 'રદ કરો',
    close: 'બંધ કરો',
    dataItemsLabel: 'ડેટા આઇટમ્સ',
    servicesLabel: 'સક્રિય કરેલી સેવાઓ',
    retentionLabel: 'જાળવણી',
    retentionDays: 'દિવસો',
    consentLabel: 'સંમતિ',
    dpoLabel: 'ડેટા સંરક્ષણ અધિકારી',
    withdrawLink: 'સંમતિ પાછી ખેંચો',
    rightsLink: 'તમારા અધિકારો',
    grievanceLink: 'ફરિયાદ',
    boardComplaintLink: 'બોર્ડ ફરિયાદ',
    viewFullNotice: 'સંપૂર્ણ સૂચના જુઓ',
  },
  mr: {
    bannerTitle: 'तुमची गोपनीयता आमच्यासाठी महत्त्वाची आहे',
    bannerText:
      'या पोर्टलने सुरक्षित ठेवण्यासाठी, तुमच्या प्राधान्ये लक्षात ठेवण्यासाठी आणि त्याचा कसा वापर होतो हे समजून घेण्यासाठी आम्ही आणि आमचे भागीदार कुकीज वापरतो. खाली तुमच्या निवडी व्यवस्थापित करा.',
    acceptAll: 'संमती स्वीकारा',
    rejectAll: 'सर्व नाकारा',
    moreOptions: 'अधिक पर्याय',
    modalTitle: 'संमती प्राधान्ये',
    chooseLanguage: 'भाषा निवडा',
    languageNote: ALL_LANGUAGES_NOTE,
    necessary: 'कडक आवश्यक कुकीज',
    necessaryDesc: 'नेहमी सक्रिय. पोर्टल काम करण्यासाठी आवश्यक — लॉगिन, सुरक्षा आणि संमती नोंदी.',
    functional: 'कार्यात्मक कुकीज',
    functionalDesc: 'तुमची भाषा आणि वैयक्तिक प्राधान्ये लक्षात ठेवा.',
    analytics: 'कार्यप्रदर्शन आणि विश्लेषण कुकीज',
    analyticsDesc: 'पोर्टल कसा वापरला जातो हे समजून घेऊन त्यात सुधारणा करण्यास मदत करते.',
    advertising: 'जाहिरात आणि सोशल मीडिया कुकीज',
    advertisingDesc: 'संबंधित जाहिराती दाखवण्यासाठी भागीदार वापरतात.',
    save: 'प्राधान्ये जतन करा',
    cancel: 'रद्द करा',
    close: 'बंद करा',
    dataItemsLabel: 'डेटा आयटम',
    servicesLabel: 'सक्रिय केलेल्या सेवा',
    retentionLabel: 'धारणा',
    retentionDays: 'दिवस',
    consentLabel: 'संमती',
    dpoLabel: 'डेटा संरक्षण अधिकारी',
    withdrawLink: 'संमती मागे घ्या',
    rightsLink: 'तुमचे हक्क',
    grievanceLink: 'तक्रार',
    boardComplaintLink: 'मंडळ तक्रार',
    viewFullNotice: 'संपूर्ण सूचना पहा',
  },
  pa: {
    bannerTitle: 'ਤੁਹਾਡੀ ਪ੍ਰਾਈਵੇਸੀ ਸਾਡੇ ਲਈ ਮਹੱਤਵਪੂਰਣ ਹੈ',
    bannerText:
      'ਇਸ ਪੋਰਟਲ ਨੂੰ ਸੁਰੱਖਿਅਤ ਰੱਖਣ, ਤੁਹਾਡੀਆਂ ਤਰਜੀਹਾਂ ਯਾਦ ਰੱਖਣ ਅਤੇ ਇਸ ਦੀ ਵਰਤੋਂ ਕਿਵੇਂ ਹੁੰਦੀ ਹੈ ਇਹ ਸਮਝਣ ਲਈ ਅਸੀਂ ਅਤੇ ਸਾਡੇ ਸਾਥੀ ਕੁਕੀਜ਼ ਦੀ ਵਰਤੋਂ ਕਰਦੇ ਹਾਂ। ਹੇਠਾਂ ਆਪਣੀਆਂ ਚੋਣਾਂ ਦਾ ਪ੍ਰਬੰਧਨ ਕਰੋ।',
    acceptAll: 'ਸਹਿਮਤੀ ਸਵੀਕਾਰੋ',
    rejectAll: 'ਸਭ ਰੱਦ ਕਰੋ',
    moreOptions: 'ਹੋਰ ਵਿਕਲਪ',
    modalTitle: 'ਸਹਿਮਤੀ ਤਰਜੀਹਾਂ',
    chooseLanguage: 'ਭਾਸ਼ਾ ਚੁਣੋ',
    languageNote: ALL_LANGUAGES_NOTE,
    necessary: 'ਸਖ਼ਤ ਲੋੜੀਂਦੀਆਂ ਕੁਕੀਜ਼',
    necessaryDesc: 'ਹਮੇਸ਼ਾ ਸਰਗਰਮ। ਪੋਰਟਲ ਕੰਮ ਕਰਨ ਲਈ ਲੋੜੀਂਦੀਆਂ — ਲੌਗਿਨ, ਸੁਰੱਖਿਆ ਅਤੇ ਸਹਿਮਤੀ ਰਿਕਾਰਡ।',
    functional: 'ਕਾਰਜਸ਼ੀਲ ਕੁਕੀਜ਼',
    functionalDesc: 'ਤੁਹਾਡੀ ਭਾਸ਼ਾ ਅਤੇ ਨਿੱਜੀ ਤਰਜੀਹਾਂ ਯਾਦ ਰੱਖੋ।',
    analytics: 'ਪ੍ਰਦਰਸ਼ਨ ਅਤੇ ਵਿਸ਼ਲੇਸ਼ਣ ਕੁਕੀਜ਼',
    analyticsDesc: 'ਪੋਰਟਲ ਨੂੰ ਬਿਹਤਰ ਬਣਾਉਣ ਲਈ ਇਸ ਦੀ ਵਰਤੋਂ ਕਿਵੇਂ ਹੁੰਦੀ ਹੈ ਇਹ ਸਮਝਣ ਵਿੱਚ ਮਦਦ ਕਰਦੀ ਹੈ।',
    advertising: 'ਵਿਗਿਆਪਨ ਅਤੇ ਸੋਸ਼ਲ ਮੀਡੀਆ ਕੁਕੀਜ਼',
    advertisingDesc: 'ਸੰਬੰਧਿਤ ਵਿਗਿਆਪਨ ਦਿਖਾਉਣ ਲਈ ਸਾਥੀ ਵਰਤਦੇ ਹਨ।',
    save: 'ਤਰਜੀਹਾਂ ਸੰਭਾਲੋ',
    cancel: 'ਰੱਦ ਕਰੋ',
    close: 'ਬੰਦ ਕਰੋ',
    dataItemsLabel: 'ਡੇਟਾ ਆਈਟਮਾਂ',
    servicesLabel: 'ਸਰਗਰਮ ਸੇਵਾਵਾਂ',
    retentionLabel: 'ਧਾਰਨ',
    retentionDays: 'ਦਿਨ',
    consentLabel: 'ਸਹਿਮਤੀ',
    dpoLabel: 'ਡੇਟਾ ਸੁਰੱਖਿਆ ਅਧਿਕਾਰੀ',
    withdrawLink: 'ਸਹਿਮਤੀ ਵਾਪਸ ਲਵੋ',
    rightsLink: 'ਤੁਹਾਡੇ ਅਧਿਕਾਰ',
    grievanceLink: 'ਸ਼ਿਕਾਇਤ',
    boardComplaintLink: 'ਬੋਰਡ ਸ਼ਿਕਾਇਤ',
    viewFullNotice: 'ਪੂਰਾ ਨੋਟਿਸ ਵੇਖੋ',
  },
  or: {
    bannerTitle: 'ଆପଣଙ୍କ ଗୋପନୀୟତା ଆମ ପାଇଁ ଗୁରୁତ୍ୱପୂର୍ଣ୍ଣ',
    bannerText:
      'ଏହି ପୋର୍ଟାଲକୁ ସୁରକ୍ଷିତ ରଖିବା, ଆପଣଙ୍କ ପସନ୍ଦ ମନେ ରଖିବା ଏବଂ ଏହା କିପରି ବ୍ୟବହୃତ ହୁଏ ତାହା ବୁଝିବା ପାଇଁ ଆମେ ଏବଂ ଆମର ସାଥୀମାନେ କୁକି ବ୍ୟବହାର କରୁଛୁ। ତଳେ ଆପଣଙ୍କ ପସନ୍ଦ ପରିଚାଳନା କରନ୍ତୁ।',
    acceptAll: 'ସମ୍ମତି ଗ୍ରହଣ କରନ୍ତୁ',
    rejectAll: 'ସବୁ ପ୍ରତ୍ୟାଖ୍ୟାନ କରନ୍ତୁ',
    moreOptions: 'ଅଧିକ ବିକଳ୍ପ',
    modalTitle: 'ସମ୍ମତି ପସନ୍ଦ',
    chooseLanguage: 'ଭାଷା ବାଛନ୍ତୁ',
    languageNote: ALL_LANGUAGES_NOTE,
    necessary: 'କଡ଼ା ଆବଶ୍ୟକ କୁକି',
    necessaryDesc: 'ସର୍ବଦା ସକ୍ରିୟ। ପୋର୍ଟାଲ କାମ କରିବା ପାଇଁ ଆବଶ୍ୟକ — ଲଗଇନ୍, ସୁରକ୍ଷା ଏବଂ ସମ୍ମତି ରେକର୍ଡ।',
    functional: 'କାର୍ଯ୍ୟାତ୍ମକ କୁକି',
    functionalDesc: 'ଆପଣଙ୍କ ଭାଷା ଏବଂ ବ୍ୟକ୍ତିଗତ ପସନ୍ଦ ମନେ ରଖନ୍ତୁ।',
    analytics: 'ପ୍ରଦର୍ଶନ ଏବଂ ବିଶ୍ଳେଷଣ କୁକି',
    analyticsDesc: 'ପୋର୍ଟାଲକୁ ଉନ୍ନତ କରିବା ପାଇଁ ଏହା କିପରି ବ୍ୟବହୃତ ହୁଏ ତାହା ବୁଝିବାରେ ସାହାଯ୍ୟ କରେ।',
    advertising: 'ବିଜ୍ଞାପନ ଏବଂ ସୋସାଲ ମିଡିଆ କୁକି',
    advertisingDesc: 'ସମ୍ବନ୍ଧୀୟ ବିଜ୍ଞାପନ ଦେଖାଇବା ପାଇଁ ସାଥୀମାନେ ବ୍ୟବହାର କରନ୍ତି।',
    save: 'ପସନ୍ଦ ସଂରକ୍ଷଣ କରନ୍ତୁ',
    cancel: 'ବାତିଲ କରନ୍ତୁ',
    close: 'ବନ୍ଦ କରନ୍ତୁ',
    dataItemsLabel: 'ତଥ୍ୟ ବସ୍ତୁ',
    servicesLabel: 'ସକ୍ରିୟ ସେବା',
    retentionLabel: 'ସଂରକ୍ଷଣ',
    retentionDays: 'ଦିନ',
    consentLabel: 'ସମ୍ମତି',
    dpoLabel: 'ତଥ୍ୟ ସୁରକ୍ଷା ଅଧିକାରୀ',
    withdrawLink: 'ସମ୍ମତି ପ୍ରତ୍ୟାହାର କରନ୍ତୁ',
    rightsLink: 'ଆପଣଙ୍କ ଅଧିକାର',
    grievanceLink: 'ଅଭିଯୋଗ',
    boardComplaintLink: 'ବୋର୍ଡ ଅଭିଯୋଗ',
    viewFullNotice: 'ସମ୍ପୂର୍ଣ୍ଣ ବିଜ୍ଞପ୍ତି ଦେଖନ୍ତୁ',
  },
  as: {
    bannerTitle: 'আপোনাৰ গোপনীয়তা আমাৰ বাবে গুৰুত্বপূর্ণ',
    bannerText:
      'এই পোৰ্টালক সুৰক্ষিত ৰাখিবলৈ, আপোনাৰ প্ৰাথমিকতা মনত ৰাখিবলৈ আৰু ই কেনেকৈ ব্যৱহাৰ কৰা হয় তাক বুজিবলৈ আমি আৰু আমাৰ অংশীদাৰীসকলে কুকি ব্যৱহাৰ কৰো। তলত আপোনাৰ পছন্দ পৰিচালনা কৰক।',
    acceptAll: 'সন্মতি গ্ৰহণ কৰক',
    rejectAll: 'সকলো প্ৰত্যাখ্যান কৰক',
    moreOptions: 'অধিক বিকল্প',
    modalTitle: 'সন্মতি প্ৰাথমিকতা',
    chooseLanguage: 'ভাষা বাছনি কৰক',
    languageNote: ALL_LANGUAGES_NOTE,
    necessary: 'কঠোৰভাৱে প্ৰয়োজনীয় কুকি',
    necessaryDesc: 'সদায় সক্ৰিয়। পোৰ্টাল কাম কৰিবলৈ প্ৰয়োজন — লগিন, সুৰক্ষা আৰু সন্মতি ৰেকৰ্ড।',
    functional: 'কাৰ্যাত্মক কুকি',
    functionalDesc: 'আপোনাৰ ভাষা আৰু ব্যক্তিগত প্ৰাথমিকতা মনত ৰাখক।',
    analytics: 'কাৰ্যক্ষমতা আৰু বিশ্লেষণ কুকি',
    analyticsDesc: 'পোৰ্টাল উন্নত কৰিবলৈ ই কেনেকৈ ব্যৱহাৰ কৰা হয় তাক বুজিবলৈ সহায় কৰে।',
    advertising: 'বিজ্ঞাপন আৰু চ\u2019হেল মিডিয়া কুকি',
    advertisingDesc: 'প্ৰাসংগিক বিজ্ঞাপন দেখুৱাইবলৈ অংশীদাৰীসকলে ব্যৱহাৰ কৰে।',
    save: 'প্ৰাথমিকতা সংৰক্ষণ কৰক',
    cancel: 'বাতিল কৰক',
    close: 'বন্ধ কৰক',
    dataItemsLabel: 'ডেটা আইটেম',
    servicesLabel: 'সক্ৰিয় সেৱা',
    retentionLabel: 'সংৰক্ষণ',
    retentionDays: 'দিন',
    consentLabel: 'সন্মতি',
    dpoLabel: 'ডেটা সুৰক্ষা বিষয়া',
    withdrawLink: 'সন্মতি প্ৰত্যাহাৰ কৰক',
    rightsLink: 'আপোনাৰ অধিকাৰ',
    grievanceLink: 'অভিযোগ',
    boardComplaintLink: 'বৰ্ড অভিযোগ',
    viewFullNotice: 'সম্পূৰ্ণ জাননী চাওক',
  },
  ne: {
    bannerTitle: 'तपाईंको गोपनीयता हाम्रो लागि महत्त्वपूर्ण छ',
    bannerText:
      'यो पोर्टललाई सुरक्षित राख्न, तपाईंको रुचि सम्झन र यसको प्रयोग कसरी हुन्छ बुझ्न हामी र हाम्रा साझेदारहरूले कुकी प्रयोग गर्छौं। तल तपाईंको छनोटहरू व्यवस्थापन गर्नुहोस्।',
    acceptAll: 'सहमति स्वीकार गर्नुहोस्',
    rejectAll: 'सबै अस्वीकार गर्नुहोस्',
    moreOptions: 'थप विकल्पहरू',
    modalTitle: 'सहमति रुचिहरू',
    chooseLanguage: 'भाषा छान्नुहोस्',
    languageNote: ALL_LANGUAGES_NOTE,
    necessary: 'कडा आवश्यक कुकीहरू',
    necessaryDesc: 'सधैं सक्रिय। पोर्टल काम गर्न आवश्यक — लगइन, सुरक्षा र सहमति रेकर्ड।',
    functional: 'कार्यात्मक कुकीहरू',
    functionalDesc: 'तपाईंको भाषा र व्यक्तिगत रुचिहरू सम्झनुहोस्।',
    analytics: 'प्रदर्शन र विश्लेषण कुकीहरू',
    analyticsDesc: 'पोर्टललाई सुधार गर्न यसको प्रयोग कसरी हुन्छ बुझ्न सहयोग गर्छ।',
    advertising: 'विज्ञापन र सामाजिक सञ्जाल कुकीहरू',
    advertisingDesc: 'प्रासंगिक विज्ञापन देखाउन साझेदारहरूले प्रयोग गर्छन्।',
    save: 'रुचिहरू सेव गर्नुहोस्',
    cancel: 'रद्द गर्नुहोस्',
    close: 'बन्द गर्नुहोस्',
    dataItemsLabel: 'डाटा वस्तुहरू',
    servicesLabel: 'सक्रिय सेवाहरू',
    retentionLabel: 'प्रतिधारण',
    retentionDays: 'दिन',
    consentLabel: 'सहमति',
    dpoLabel: 'डाटा संरक्षण अधिकृत',
    withdrawLink: 'सहमति फिर्ता लिनुहोस्',
    rightsLink: 'तपाईंको अधिकार',
    grievanceLink: 'गुनासो',
    boardComplaintLink: 'बोर्ड गुनासो',
    viewFullNotice: 'पूरा सूचना हेर्नुहोस्',
  },
  sd: {
    bannerTitle: 'تهنجي خفIpAddress ھڪ ۾ ھڪ ۾ ۔۔۔',
    bannerText:
      'هندس پورٽل خفIpAddress رکڻ، تهنجي پسندياد ياد رکڻ ۽ هن جو کيئن ورتو ٿو سمجھڻ لاءِ اسان ۽ اسان جا ساتھي ڪڪيز استعمال ڪريون ٿا۔ هيٺ تهنجي выбор ڪيو۔',
    acceptAll: 'رضامندي قبول ڪريو',
    rejectAll: 'سڀ رد ڪريو',
    moreOptions: 'وڌيڪ اختيار',
    modalTitle: 'رضامندي پسندياد',
    chooseLanguage: 'ٻولي چونڊيو',
    languageNote: ALL_LANGUAGES_NOTE,
    necessary: 'سخت ضروري ڪڪيز',
    necessaryDesc: 'هميشه فعال۔ پورٽل ڪم ڪرڻ لاءِ ضروري — لاگ ان، حفاظت ۽ رضامندي رڪارڊ۔',
    functional: 'فيInTheDocumentل ڪڪيز',
    functionalDesc: 'تهنجي ٻولي ۽ ذاتي پسندياد ياد رکو۔',
    analytics: 'ڪارڪردگي ۽ تجزيي ڪڪيز',
    analyticsDesc: 'پورٽل ۾ سڌارو ڪرڻ لاءِ هن جو کيئن ورتو ٿو سمجھڻ ۾ مدد ڪري ٿو۔',
    advertising: 'اشتھارات ۽ سوشل ميڊيا ڪڪيز',
    advertisingDesc: 'متعلقه اشتھارات ڏيھارڻ لاءِ ساتھي استعمال ڪري ٿا۔',
    save: 'پسندياد حفظ ڪريو',
    cancel: 'رد ڪريو',
    close: 'بند ڪريو',
    dataItemsLabel: 'ڊيٽا شيون',
    servicesLabel: 'فعال سروسون',
    retentionLabel: 'برقرار رکڻ',
    retentionDays: 'ڏينهن',
    consentLabel: 'رضامندي',
    dpoLabel: 'ڊيٽا تحفظ آفيسر',
    withdrawLink: 'رضامندي واپس وٺو',
    rightsLink: 'توهان جا حق',
    grievanceLink: 'شڪايت',
    boardComplaintLink: 'بورڊ شڪايت',
    viewFullNotice: 'مڪمل نوٽيس ڏسو',
  },
  ks: {
    bannerTitle: 'تُہِند گوپنیاتھ ہاکِن لازم چھ',
    bannerText:
      'یہ پورٹل محفوظ رکھن، تُہِنٛد ترجیحات یاد رکھن تٔہِ یہ کیوٛن ورtdf چھ ہاکِن سمجھن، آسن تٔہِ آسن جٕ ساتھی گُکز یِوان چھ استعمال۔ بیَکھر تُہِنٛدChoices نالٕہ کُریو۔',
    acceptAll: 'رضامندی قبول کریو',
    rejectAll: 'Reject all',
    moreOptions: 'مزید آپشن',
    modalTitle: 'رضامندی ترجیحات',
    chooseLanguage: 'زبان چُنیو',
    languageNote: ALL_LANGUAGES_NOTE,
    necessary: 'سخت ضروری گُکز',
    necessaryDesc: 'ہمیشہ ایکٹو۔ پورٹل کام کرن لازم — لاگ ان، سیفٹی تٔہِ رضامندی ریکارڈ۔',
    functional: 'فعال گُکز',
    functionalDesc: 'تُہِنٛد زبان تٔہِ ذاتی ترجیحات یاد رکیو۔',
    analytics: 'کارکردگی تٔہِ تجزیہ گُکز',
    analyticsDesc: 'پورٹل بہتر بنون مدد گار چھ۔',
    advertising: 'اشتھارات تٔہِ سوشل میڈیا گُکز',
    advertisingDesc: 'متعلق اشتھارات دکھawn لگِ ساتھی استعمال چھ۔',
    save: 'ترجیحات محفوظ کریو',
    cancel: 'رد کریو',
    close: 'بند کریو',
    dataItemsLabel: 'Data items',
    servicesLabel: 'Services enabled',
    retentionLabel: 'Retention',
    retentionDays: 'days',
    consentLabel: 'Consent',
    dpoLabel: 'Data Protection Officer',
    withdrawLink: 'Withdraw consent',
    rightsLink: 'Your rights',
    grievanceLink: 'Grievance',
    boardComplaintLink: 'Board complaint',
    viewFullNotice: 'View full notice',
  },
  kok: {
    bannerTitle: 'तुमची गोपनीयता आमकांसाठी महत्त्वाची आहे',
    bannerText:
      'हा पोर्टल सुरक्षित ठेवण्यासाठी, तुमच्या प्राधान्या लक्षात ठेवण्यासाठी आणि त्याचा कशाने वापर होता हे समजून घेण्यासाठी आमी आणि आमचे भागीदार कुकीज वापरतात। खाली तुमच्या निवडी व्यवस्थापित करा।',
    acceptAll: 'संमती स्वीकारा',
    rejectAll: 'सगळें नाकारा',
    moreOptions: 'अधिक पर्याय',
    modalTitle: 'संमती प्राधान्या',
    chooseLanguage: 'भासा निवडा',
    languageNote: ALL_LANGUAGES_NOTE,
    necessary: 'कडक आवश्यक कुकीज',
    necessaryDesc: 'नेमकां सक्रिय। पोर्टल काम करण्यासाठी आवश्यक — लॉगिन, सुरक्षा आणि संमती नोंदी।',
    functional: 'कार्यात्मक कुकीज',
    functionalDesc: 'तुमची भासा आणि वैयक्तिक प्राधान्या लक्षात ठेवा।',
    analytics: 'कार्यप्रदर्शन आणि विश्लेषण कुकीज',
    analyticsDesc: 'पोर्टल कशाने वापरला जाता हे समजून घेऊन त्यात सुधारणा करण्यास मदत करते।',
    advertising: 'जाहिरात आणि सोशल मीडिया कुकीज',
    advertisingDesc: 'संबंधित जाहिराती दाखवण्यासाठी भागीदार वापरतात।',
    save: 'प्राधान्या जतन करा',
    cancel: 'रद्द करा',
    close: 'बंद करा',
    dataItemsLabel: 'डेटा आयटम',
    servicesLabel: 'सक्रिय केल्ल्या सेवा',
    retentionLabel: 'धारणा',
    retentionDays: 'दीस',
    consentLabel: 'संमती',
    dpoLabel: 'डेटा संरक्षण अधिकारी',
    withdrawLink: 'संमती परत घेवचे',
    rightsLink: 'तुमचे हक्क',
    grievanceLink: 'तक्रार',
    boardComplaintLink: 'मंडळ तक्रार',
    viewFullNotice: 'सगळी सूचना पळेवची',
  },
  mai: {
    bannerTitle: 'अहाँक गोपनीयता हमर लेल महत्वपूर्ण अछि',
    bannerText:
      'ई पोर्टल के सुरक्षित राखय लेल, अहाँक प्राथमिकता याद राखय लेल आउर एकर प्रयोग केना होइछ बुझय लेल हम आउर हमर साझेदार कुकीज प्रयोग करैत छैत। नीचे अहाँक छनोट प्रबंधित करू।',
    acceptAll: 'सहमति स्वीकार करू',
    rejectAll: 'सभ अस्वीकार करू',
    moreOptions: 'बेसी विकल्प',
    modalTitle: 'सहमति प्राथमिकता',
    chooseLanguage: 'भाषा चुनू',
    languageNote: ALL_LANGUAGES_NOTE,
    necessary: 'कड़ाई से जरूरी कुकीज',
    necessaryDesc: 'सदैव सक्रिय। पोर्टल काम करबाक लेल जरूरी — लॉगिन, सुरक्षा आउर सहमति रिकॉर्ड।',
    functional: 'कार्यात्मक कुकीज',
    functionalDesc: 'अहाँक भाषा आउर व्यक्तिगत प्राथमिकता याद राखू।',
    analytics: 'प्रदर्शन आउर विश्लेषण कुकीज',
    analyticsDesc: 'पोर्टल के बेहतर बनाबै लेल एकर प्रयोग केना होइछ बुझय में सहयोग करैत अछि।',
    advertising: 'विज्ञापन आउर सोशल मीडिया कुकीज',
    advertisingDesc: 'संबंधित विज्ञापन देखाबै लेल साझेदार प्रयोग करैत छैत।',
    save: 'प्राथमिकता सेव करू',
    cancel: 'रद्द करू',
    close: 'बंद करू',
    dataItemsLabel: 'डाटा वस्तु',
    servicesLabel: 'सक्षम सेवा',
    retentionLabel: 'प्रतिधारण',
    retentionDays: 'दिन',
    consentLabel: 'सहमति',
    dpoLabel: 'डाटा सुरक्षा अधिकारी',
    withdrawLink: 'सहमति वापस लिअ',
    rightsLink: 'अहाँक अधिकार',
    grievanceLink: 'शिकायत',
    boardComplaintLink: 'बोर्ड शिकायत',
    viewFullNotice: 'पूरा सूचना देखू',
  },
  doi: {
    bannerTitle: 'थाहरी गोपनीयता साडे लई ज़रूरी ऐ',
    bannerText:
      'एहं पोर्टल ने सुरक्षित राखने, थाहरी तरजीहां याद राखने ते इहं किवें वर्ता जांदा ऐ समझन लई असां ते साडे साथी कुकीज दी वरता करंदे आ। थल्लें थाहरी छनोट संभालो।',
    acceptAll: 'सहमती कबूल करो',
    rejectAll: 'सब अस्वीकार करो',
    moreOptions: 'बै विकल्प',
    modalTitle: 'सहमती तरजीहां',
    chooseLanguage: 'भासा चुनो',
    languageNote: ALL_LANGUAGES_NOTE,
    necessary: 'सख़्त लोड़ी दी कुकीज',
    necessaryDesc: 'हमेशा सक्रिय। पोर्टल कैं कम करन लई लोड़ी — लॉगिन, सुरक्षा ते सहमती रिकॉर्ड।',
    functional: 'कार्यात्मक कुकीज',
    functionalDesc: 'थाहरी भासा ते निजी तरजीहां याद राखो।',
    analytics: 'कार्यशीलता ते विश्लेषण कुकीज',
    analyticsDesc: 'पोर्टल ने बेहतर बनान लई इहं किवें वरता जांदा ऐ समझन लई मदद करंदा ऐ।',
    advertising: 'विज्ञापन ते सोशल मीडिया कुकीज',
    advertisingDesc: 'संबंधित विज्ञापन दिखान लई साथी वरतंदे आ।',
    save: 'तरजीहां सेव करो',
    cancel: 'रद्द करो',
    close: 'बंद करो',
    dataItemsLabel: 'डाटा आइटम',
    servicesLabel: 'सक्रिय सेवा',
    retentionLabel: 'धारण',
    retentionDays: 'दिन',
    consentLabel: 'सहमती',
    dpoLabel: 'डाटा सुरक्षा अधिकारी',
    withdrawLink: 'सहमती वापस लैओ',
    rightsLink: 'थाहरे हक',
    grievanceLink: 'शिकायत',
    boardComplaintLink: 'बोर्ड शिकायत',
    viewFullNotice: 'पूरा नोटिस दिक्खो',
  },
  brx: {
    bannerTitle: 'निं गोपनीय आमनि गै महत्वपूर्ण आ',
    bannerText:
       `एन पोर्टलखौ निरापत दं निं मन'नि सिफार आ बेनिखौ गिबि गिबियै गोल मिथिम आमोनि आ आमनि साफायखौनो कुकिज बाहाय मोन थायो। लाहाय निं गिबिखौ बिजারबाय।`,
    acceptAll: 'सिफारसिं बिबोन्थ',
    rejectAll: 'Reject all',
    moreOptions: 'गोबां बिबर',
    modalTitle: 'सिफारसिं गिबिफोर',
    chooseLanguage: 'गिबि सिनाय',
    languageNote: ALL_LANGUAGES_NOTE,
    necessary: 'दिदिम्लाबै कुकिज',
    necessaryDesc: 'सिं सिगुं सक्तिब। पोर्टल बिबोन्थनि थाखाय लाबों — लग-इन, निरापथ आ सिफारसिं रेकर्ड।',
    functional: 'बिबोन्थ बाहायनाय कुकिज',
    functionalDesc: 'निं गिबि आ बिबैयार गिबिफोर बिबोन्थ।',
    analytics: 'काराबोन आ मिथिफोन कुकिज',
    analyticsDesc: 'पोर्टलखौ गोबारदं थानाय थाखाय बेनिखौ गिबि गिबियै गोल मिथिनाय लाखिफोर सोंबथाय।',
    advertising: 'सोदबोन आ साउद-मिडिया कुकिज',
    advertisingDesc: 'बेसेबाइन सोदबोन दिन्थनाय थाखाय बाहाय मोन थायो।',
    save: 'गिबिफोर थिंनाय',
    cancel: 'नंगौ',
    close: 'बंद',
    dataItemsLabel: 'Data items',
    servicesLabel: 'Services enabled',
    retentionLabel: 'Retention',
    retentionDays: 'days',
    consentLabel: 'Consent',
    dpoLabel: 'Data Protection Officer',
    withdrawLink: 'Withdraw consent',
    rightsLink: 'Your rights',
    grievanceLink: 'Grievance',
    boardComplaintLink: 'Board complaint',
    viewFullNotice: 'View full notice',
  },
  sat: {
    bannerTitle: 'ᱤᱞᱦᱚᱨ ᱥᱟᱹᱜᱷᱟᱹᱨ ᱨᱮ ᱫᱟᱲᱮᱭᱟᱜ ᱛᱮᱦᱟᱨ ᱢᱮᱱᱟᱜᱼ',
    bannerText:
      'ᱱᱮᱭᱟᱜ ᱤᱞᱦᱚᱨ ᱫᱚᱨᱚᱲᱚ ᱠᱩᱴᱤ ᱵᱟᱹᱨᱚᱜᱚᱢ ᱨᱮ ᱞᱟᱹᱜᱚᱠᱟ ᱥᱚ ᱵᱟᱛᱟᱣᱚ ᱠᱚ ᱟᱢᱚᱱᱚ ᱞᱟᱹᱜᱚᱠᱟ ᱦᱮᱱᱚ ᱢᱮᱱᱟᱜᱼ ᱤᱚᱱ ᱫᱚᱨᱚᱲᱚ ᱥᱮ ᱫᱚᱨᱚᱲᱚ ᱥᱟᱹᱜᱷᱟᱹᱨ ᱞᱟᱹᱜᱚᱠᱟ ᱛᱮ ᱰᱩᱨᱤᱭᱚᱢ ᱦᱚᱸ',
    acceptAll: 'ᱥᱮᱹᱡᱚᱢᱰᱤ ᱥᱩᱠᱷᱟᱨᱚ',
    rejectAll: 'Reject all',
    moreOptions: 'ᱤᱧᱟᱢ ᱵᱤᱠᱚᱸ',
    modalTitle: 'ᱥᱮᱹᱡᱚᱢᱰᱤ ᱥᱟᱹᱜᱷᱟᱹᱨ',
    chooseLanguage: 'ᱯᱚᱨᱚᱢ ᱵᱟᱪᱷᱟᱨᱚᱢ',
    languageNote: ALL_LANGUAGES_NOTE,
    necessary: 'ᱥᱟᱨᱮᱡᱚ ᱠᱩᱴᱤ',
    necessaryDesc: 'ᱢᱟᱛᱟᱞᱚ ᱥᱟᱹᱜᱷᱟᱹᱨ ᱞᱟᱱᱟ — ᱞᱟᱜᱚᱠᱚᱢ, ᱥᱤᱢᱚᱱᱚᱜᱚ ᱟᱨ ᱥᱮᱹᱡᱚᱢᱰᱤ ᱨᱮᱠᱚᱨᱰᱚ',
    functional: 'ᱠᱟᱨᱮᱡᱚ ᱠᱩᱴᱤ',
    functionalDesc: 'ᱤᱞᱦᱚᱨ ᱟᱨ ᱵᱤᱠᱚᱸ ᱥᱟᱹᱜᱷᱟᱹᱨ ᱢᱩᱜᱚ ᱠᱚ',
    analytics: 'ᱠᱟᱨᱚᱣᱚᱢ ᱟᱨ ᱢᱤᱛᱚᱨᱚᱢ ᱠᱩᱴᱤ',
    analyticsDesc: 'ᱤᱞᱦᱚᱨ ᱢᱮᱱᱚᱠᱚᱢ ᱫᱚᱨᱚᱲᱚ ᱵᱟᱹᱨᱚᱜᱚᱢ ᱨᱮ ᱢᱩᱜᱚ ᱠᱚ',
    advertising: 'ᱥᱮᱨᱤᱢᱚᱱᱚᱜᱚ ᱟᱨ ᱥᱚᱣᱚᱥᱚ ᱤᱞᱦᱚᱨ ᱠᱩᱴᱤ',
    advertisingDesc: 'ᱚᱨᱚᱲᱚ ᱥᱮᱨᱤᱢᱚᱱᱚᱜᱚ ᱰᱮᱨᱟᱭᱚᱢ ᱨᱮ ᱵᱟᱹᱨᱚᱜᱚᱢ ᱞᱟᱱᱟ',
    save: 'ᱥᱟᱹᱜᱷᱟᱹᱨ ᱥᱟᱶᱨᱚ',
    cancel: 'ᱵᱟᱰᱚ',
    close: 'ᱵᱚᱨᱚᱢ',
    dataItemsLabel: 'Data items',
    servicesLabel: 'Services enabled',
    retentionLabel: 'Retention',
    retentionDays: 'days',
    consentLabel: 'Consent',
    dpoLabel: 'Data Protection Officer',
    withdrawLink: 'Withdraw consent',
    rightsLink: 'Your rights',
    grievanceLink: 'Grievance',
    boardComplaintLink: 'Board complaint',
    viewFullNotice: 'View full notice',
  },
  mni: {
    bannerTitle: 'নিংগী সেক্সিপার ঙমগী খং মহৎ ঙমদি',
    bannerText:
      'মই অমুক অমুকনা কুকী শিজিন্নরে, তমরী প্রেফারেন্স খুদম মরুফ্তাহনবা অমুক অমুকনা শক্তগন লৈরিবা ঙমশিন্নরে।',
    acceptAll: 'অমুকতা লৈরবা',
    rejectAll: 'Reject all',
    moreOptions: 'অহেনবা অপশন',
    modalTitle: 'অমুকতা প্রেফারেন্স',
    chooseLanguage: 'লুই খনবা',
    languageNote: ALL_LANGUAGES_NOTE,
    necessary: 'শত লোইরবা কুকী',
    necessaryDesc: 'যারেম শক্ত। পোর্টল শক্ত কাম তারিবা ঙমদি — লগইন, সেক্সিপার অমুকতা।',
    functional: 'কামতা কুকী',
    functionalDesc: 'তমরী লুই খুদম প্রেফারেন্স খুদম মরুফ্তাহনবা।',
    analytics: 'কামতা খুদম অনালাইসিস কুকী',
    analyticsDesc: 'পোর্টল অয়োম্বা শক্ত খুদম তারিবা খুদম ঙমশিন্নরে।',
    advertising: 'বিজ্ঞাপন খুদম সোশ্যাল মিডিয়া কুকী',
    advertisingDesc: 'পার্টনারনা লৈরে, বিজ্ঞাপন খুদম শক্তদা উইনবা।',
    save: 'প্রেফারেন্স খুদম মরুফ্তাহনবা',
    cancel: 'বাতিল',
    close: 'থিংবা',
    dataItemsLabel: 'Data items',
    servicesLabel: 'Services enabled',
    retentionLabel: 'Retention',
    retentionDays: 'days',
    consentLabel: 'Consent',
    dpoLabel: 'Data Protection Officer',
    withdrawLink: 'Withdraw consent',
    rightsLink: 'Your rights',
    grievanceLink: 'Grievance',
    boardComplaintLink: 'Board complaint',
    viewFullNotice: 'View full notice',
  },
  sa: {
    bannerTitle: 'भवतः गोपनीयता अस्माकं प्रति महत्त्वपूर्ण अस्ति',
    bannerText:
      'अस्माभिः सह भागिदारैः कुकीस् व्यवहृत्यन्ते — एतत् पोर्टलं सुरक्षितं कर्तुं, भवतः प्राथमिकताः स्मर्तुं, एतस्य प्रयोगं ज्ञातुं च। अधः स्वविकल्पान् प्रबन्धयतु।',
    acceptAll: 'सम्मतिं स्वीकुरुत',
    rejectAll: 'सर्वं अस्वीकुरुत',
    moreOptions: 'अधिक विकल्पाः',
    modalTitle: 'सम्मति प्राथमिकताः',
    chooseLanguage: 'भाषां वृणोतु',
    languageNote: ALL_LANGUAGES_NOTE,
    necessary: 'आवश्यकाः कुकीस्',
    necessaryDesc: 'सर्वदा सक्रियाः। पोर्टलस्य कर्तुं आवश्यकाः — लगिन्, सुरक्षा, सम्मति च।',
    functional: 'कार्यात्मकाः कुकीस्',
    functionalDesc: 'भवतः भाषां प्राथमिकताः च स्मरतु।',
    analytics: 'प्रदर्शनं विश्लेषणं च कुकीस्',
    analyticsDesc: 'पोर्टलं उत्तमं कर्तुं सहायतां करोति।',
    advertising: 'प्रचारः सामाजिकमाध्यमं च कुकीस्',
    advertisingDesc: 'सम्बन्धित प्रचारं दर्शयितुं भागिदारैः प्रयुज्यन्ते।',
    save: 'प्राथमिकताः सुरक्षयतु',
    cancel: 'परित्यजतु',
    close: 'पिधत्तु',
    dataItemsLabel: 'दत्तांशवस्तूनि',
    servicesLabel: 'सक्रियसेवाः',
    retentionLabel: 'धारणम्',
    retentionDays: 'दिनानि',
    consentLabel: 'सम्मतिः',
    dpoLabel: 'दत्तांश-सुरक्षा-अधिकारी',
    withdrawLink: 'सम्मतिं निवर्तयतु',
    rightsLink: 'भवतः अधिकाराः',
    grievanceLink: 'परिवेदना',
    boardComplaintLink: 'मण्डल-परिवेदना',
    viewFullNotice: 'सम्पूर्णं सूचनापत्रं पश्यतु',
  },
  ur: {
    bannerTitle: 'آپ کی رازداری ہمارے لیے اہم ہے',
    bannerText:
      'ہم اور ہمارے پارٹنر اس پورٹل کو محفوظ رکھنے، آپ کی ترجیحات یاد رکھنے اور اس کے استعمال کو سمجھنے کے لیے کوکیز استعمال کرتے ہیں۔ نیچے اپنے انتخابات کا انتظام کریں۔',
    acceptAll: 'رضا مندی قبول کریں',
    rejectAll: 'سب مسترد کریں',
    moreOptions: 'مزید اختیارات',
    modalTitle: 'رضا مندی کی ترجیحات',
    chooseLanguage: 'زبان منتخب کریں',
    languageNote: ALL_LANGUAGES_NOTE,
    necessary: 'سخت ضروری کوکیز',
    necessaryDesc: 'ہمیشہ فعال۔ پورٹل کے کام کرنے کے لیے ضروری — لاگ ان، سیکیورٹی اور رضا مندی کے ریکارڈ۔',
    functional: 'فعال کوکیز',
    functionalDesc: 'آپ کی زبان اور ذاتی ترجیحات یاد رکھیں۔',
    analytics: 'کارکردگی اور تجزیہ کوکیز',
    analyticsDesc: 'پورٹل کو بہتر بنانے میں مدد کرتی ہیں۔',
    advertising: 'اشتہارات اور سوشل میڈیا کوکیز',
    advertisingDesc: 'متعلقہ اشتہارات دکھانے کے لیے پارٹنرز استعمال کرتے ہیں۔',
    save: 'ترجیحات محفوظ کریں',
    cancel: 'منسوخ کریں',
    close: 'بند کریں',
    dataItemsLabel: 'ڈیٹا آئٹمز',
    servicesLabel: 'فعال کردہ خدمات',
    retentionLabel: 'برقراری',
    retentionDays: 'دن',
    consentLabel: 'رضامندی',
    dpoLabel: 'ڈیٹا پروٹیکشن آفیسر',
    withdrawLink: 'رضامندی واپس لیں',
    rightsLink: 'آپ کے حقوق',
    grievanceLink: 'شکایت',
    boardComplaintLink: 'بورڈ شکایت',
    viewFullNotice: 'مکمل نوٹس دیکھیں',
  },
}
