export interface BannerCopy {
  bannerTitle: string
  bannerText: string
  chooseLanguage: string
  acceptAll: string
  rejectAll: string
  moreOptions: string
  savePreferences: string
  saving: string
  viewFullNotice: string
  necessary: string
  necessaryDesc: string
  alwaysActive: string
  functional: string
  functionalDesc: string
  analytics: string
  analyticsDesc: string
  advertising: string
  advertisingDesc: string
  dataItemsLabel: string
  servicesLabel: string
  retentionLabel: string
  retentionDays: string
  consentLabel: string
  dpoLabel: string
  withdrawLink: string
  rightsLink: string
  grievanceLink: string
  boardComplaintLink: string
}

// Falls back to English whenever the visitor's chosen language has no entry here,
// so the banner never renders blank for an unsupported language.
export const BANNER_COPY: Record<string, BannerCopy> = {
  en: {
    bannerTitle: 'We value your privacy',
    bannerText:
      'Codex uses cookies to enhance your browsing experience, keep you signed in, and understand how the platform is used. You can accept all cookies or choose which categories to allow.',
    chooseLanguage: 'Choose language',
    acceptAll: 'Accept All',
    rejectAll: 'Reject All',
    moreOptions: 'More Options',
    savePreferences: 'Save Preferences',
    saving: 'Saving…',
    viewFullNotice: 'View full notice',
    necessary: 'Strictly Necessary',
    necessaryDesc: 'Essential for the site to function, such as keeping you signed in. These cannot be disabled.',
    alwaysActive: 'Always active',
    functional: 'Functional',
    functionalDesc: 'Remembers your preferences like editor theme, language and layout.',
    analytics: 'Analytics',
    analyticsDesc: 'Helps us understand how you use Codex so we can improve the platform.',
    advertising: 'Advertising',
    advertisingDesc: 'Used to show relevant coding challenges and measure campaign effectiveness.',
    dataItemsLabel: 'Data items',
    servicesLabel: 'Services enabled',
    retentionLabel: 'Retention',
    retentionDays: 'days',
    consentLabel: 'Consent',
    dpoLabel: 'Data Protection Officer',
    withdrawLink: 'Withdraw consent',
    rightsLink: 'Your rights',
    grievanceLink: 'Grievance',
    boardComplaintLink: 'Board complaint',
  },
  hi: {
    bannerTitle: 'हम आपकी गोपनीयता को महत्व देते हैं',
    bannerText:
      'Codex आपके ब्राउज़िंग अनुभव को बेहतर बनाने, आपको साइन इन रखने और यह समझने के लिए कुकीज़ का उपयोग करता है कि प्लेटफ़ॉर्म का उपयोग कैसे किया जाता है। आप सभी कुकीज़ स्वीकार कर सकते हैं या श्रेणियां चुन सकते हैं।',
    chooseLanguage: 'भाषा चुनें',
    acceptAll: 'सभी स्वीकार करें',
    rejectAll: 'सभी अस्वीकार करें',
    moreOptions: 'अधिक विकल्प',
    savePreferences: 'प्राथमिकताएं सहेजें',
    saving: 'सहेजा जा रहा है…',
    viewFullNotice: 'पूरा नोटिस देखें',
    necessary: 'अत्यंत आवश्यक',
    necessaryDesc: 'साइट के कार्य करने के लिए आवश्यक, जैसे आपको साइन इन रखना। इन्हें अक्षम नहीं किया जा सकता।',
    alwaysActive: 'हमेशा सक्रिय',
    functional: 'कार्यात्मक',
    functionalDesc: 'आपकी प्राथमिकताएं जैसे एडिटर थीम, भाषा और लेआउट याद रखता है।',
    analytics: 'विश्लेषण',
    analyticsDesc: 'यह समझने में मदद करता है कि आप Codex का उपयोग कैसे करते हैं ताकि हम प्लेटफ़ॉर्म को बेहतर बना सकें।',
    advertising: 'विज्ञापन',
    advertisingDesc: 'प्रासंगिक कोडिंग चुनौतियां दिखाने और अभियान प्रभावशीलता मापने के लिए उपयोग किया जाता है।',
    dataItemsLabel: 'डेटा आइटम',
    servicesLabel: 'सक्षम सेवाएं',
    retentionLabel: 'प्रतिधारण',
    retentionDays: 'दिन',
    consentLabel: 'सहमति',
    dpoLabel: 'डेटा संरक्षण अधिकारी',
    withdrawLink: 'सहमति वापस लें',
    rightsLink: 'आपके अधिकार',
    grievanceLink: 'शिकायत',
    boardComplaintLink: 'बोर्ड शिकायत',
  },
  ta: {
    bannerTitle: 'உங்கள் தனியுரிமையை நாங்கள் மதிக்கிறோம்',
    bannerText:
      'உங்கள் உலாவல் அனுபவத்தை மேம்படுத்தவும், உங்களை உள்நுழைந்த நிலையில் வைத்திருக்கவும், தளம் எவ்வாறு பயன்படுத்தப்படுகிறது என்பதைப் புரிந்துகொள்ளவும் Codex குக்கீகளைப் பயன்படுத்துகிறது. நீங்கள் அனைத்து குக்கீகளையும் ஏற்கலாம் அல்லது வகைகளைத் தேர்ந்தெடுக்கலாம்.',
    chooseLanguage: 'மொழியைத் தேர்ந்தெடுக்கவும்',
    acceptAll: 'அனைத்தையும் ஏற்கவும்',
    rejectAll: 'அனைத்தையும் நிராகரிக்கவும்',
    moreOptions: 'மேலும் விருப்பங்கள்',
    savePreferences: 'விருப்பங்களைச் சேமிக்கவும்',
    saving: 'சேமிக்கிறது…',
    viewFullNotice: 'முழு அறிவிப்பைக் காண்க',
    necessary: 'கண்டிப்பாக அவசியமானது',
    necessaryDesc: 'தளம் செயல்பட அவசியம், உங்களை உள்நுழைந்த நிலையில் வைத்திருப்பது போன்றவை. இவற்றை முடக்க முடியாது.',
    alwaysActive: 'எப்போதும் செயலில்',
    functional: 'செயல்பாட்டு',
    functionalDesc: 'எடிட்டர் தீம், மொழி மற்றும் தளவமைப்பு போன்ற உங்கள் விருப்பங்களை நினைவில் வைக்கும்.',
    analytics: 'பகுப்பாய்வு',
    analyticsDesc: 'தளத்தை மேம்படுத்த Codex-ஐ நீங்கள் எவ்வாறு பயன்படுத்துகிறீர்கள் என்பதைப் புரிந்துகொள்ள உதவுகிறது.',
    advertising: 'விளம்பரம்',
    advertisingDesc: 'பொருத்தமான கோடிங் சவால்களைக் காட்டவும் பிரச்சார செயல்திறனை அளவிடவும் பயன்படுத்தப்படுகிறது.',
    dataItemsLabel: 'தரவு உருப்படிகள்',
    servicesLabel: 'இயக்கப்பட்ட சேவைகள்',
    retentionLabel: 'தக்கவைப்பு',
    retentionDays: 'நாட்கள்',
    consentLabel: 'சம்மதம்',
    dpoLabel: 'தரவுப் பாதுகாப்பு அதிகாரி',
    withdrawLink: 'சம்மதத்தை விலக்கிக்கொள்',
    rightsLink: 'உங்கள் உரிமைகள்',
    grievanceLink: 'குறை தீர்வு',
    boardComplaintLink: 'குழு புகார்',
  },
  te: {
    bannerTitle: 'మేము మీ గోప్యతను గౌరవిస్తాము',
    bannerText:
      'మీ బ్రౌజింగ్ అనుభవాన్ని మెరుగుపరచడానికి, మిమ్మల్ని సైన్ ఇన్‌గా ఉంచడానికి మరియు ప్లాట్‌ఫారమ్ ఎలా ఉపయోగించబడుతుందో అర్థం చేసుకోవడానికి Codex కుకీలను ఉపయోగిస్తుంది. మీరు అన్ని కుకీలను ఆమోదించవచ్చు లేదా వర్గాలను ఎంచుకోవచ్చు.',
    chooseLanguage: 'భాషను ఎంచుకోండి',
    acceptAll: 'అన్నింటినీ ఆమోదించండి',
    rejectAll: 'అన్నింటినీ తిరస్కరించండి',
    moreOptions: 'మరిన్ని ఎంపికలు',
    savePreferences: 'ప్రాధాన్యతలను సేవ్ చేయండి',
    saving: 'సేవ్ చేస్తోంది…',
    viewFullNotice: 'పూర్తి నోటీసును చూడండి',
    necessary: 'తప్పనిసరిగా అవసరమైనవి',
    necessaryDesc: 'సైట్ పనిచేయడానికి అవసరం, మిమ్మల్ని సైన్ ఇన్‌గా ఉంచడం వంటివి. వీటిని నిలిపివేయలేరు.',
    alwaysActive: 'ఎల్లప్పుడూ చురుకుగా',
    functional: 'ఫంక్షనల్',
    functionalDesc: 'ఎడిటర్ థీమ్, భాష మరియు లేఅవుట్ వంటి మీ ప్రాధాన్యతలను గుర్తుంచుకుంటుంది.',
    analytics: 'విశ్లేషణ',
    analyticsDesc: 'ప్లాట్‌ఫారమ్‌ను మెరుగుపరచడానికి మీరు Codexను ఎలా ఉపయోగిస్తున్నారో అర్థం చేసుకోవడానికి సహాయపడుతుంది.',
    advertising: 'ప్రకటనలు',
    advertisingDesc: 'సంబంధిత కోడింగ్ సవాళ్లను చూపించడానికి మరియు ప్రచార ప్రభావాన్ని కొలవడానికి ఉపయోగించబడుతుంది.',
    dataItemsLabel: 'డేటా అంశాలు',
    servicesLabel: 'ప్రారంభించబడిన సేవలు',
    retentionLabel: 'నిలుపుదల',
    retentionDays: 'రోజులు',
    consentLabel: 'సమ్మతి',
    dpoLabel: 'డేటా రక్షణ అధికారి',
    withdrawLink: 'సమ్మతిని ఉపసంహరించుకోండి',
    rightsLink: 'మీ హక్కులు',
    grievanceLink: 'ఫిర్యాదు',
    boardComplaintLink: 'బోర్డు ఫిర్యాదు',
  },
  kn: {
    bannerTitle: 'ನಾವು ನಿಮ್ಮ ಗೌಪ್ಯತೆಯನ್ನು ಗೌರವಿಸುತ್ತೇವೆ',
    bannerText:
      'ನಿಮ್ಮ ಬ್ರೌಸಿಂಗ್ ಅನುಭವವನ್ನು ಹೆಚ್ಚಿಸಲು, ನಿಮ್ಮನ್ನು ಸೈನ್ ಇನ್ ಆಗಿ ಇರಿಸಲು ಮತ್ತು ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಅನ್ನು ಹೇಗೆ ಬಳಸಲಾಗುತ್ತದೆ ಎಂಬುದನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲು Codex ಕುಕೀಗಳನ್ನು ಬಳಸುತ್ತದೆ. ನೀವು ಎಲ್ಲಾ ಕುಕೀಗಳನ್ನು ಸ್ವೀಕರಿಸಬಹುದು ಅಥವಾ ವರ್ಗಗಳನ್ನು ಆಯ್ಕೆ ಮಾಡಬಹುದು.',
    chooseLanguage: 'ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
    acceptAll: 'ಎಲ್ಲವನ್ನೂ ಸ್ವೀಕರಿಸಿ',
    rejectAll: 'ಎಲ್ಲವನ್ನೂ ತಿರಸ್ಕರಿಸಿ',
    moreOptions: 'ಹೆಚ್ಚಿನ ಆಯ್ಕೆಗಳು',
    savePreferences: 'ಆದ್ಯತೆಗಳನ್ನು ಉಳಿಸಿ',
    saving: 'ಉಳಿಸಲಾಗುತ್ತಿದೆ…',
    viewFullNotice: 'ಪೂರ್ಣ ಸೂಚನೆಯನ್ನು ವೀಕ್ಷಿಸಿ',
    necessary: 'ಕಟ್ಟುನಿಟ್ಟಾಗಿ ಅಗತ್ಯವಾದ',
    necessaryDesc: 'ಸೈಟ್ ಕಾರ್ಯನಿರ್ವಹಿಸಲು ಅಗತ್ಯ, ನಿಮ್ಮನ್ನು ಸೈನ್ ಇನ್ ಆಗಿ ಇರಿಸುವಂತಹ. ಇವುಗಳನ್ನು ನಿಷ್ಕ್ರಿಯಗೊಳಿಸಲಾಗುವುದಿಲ್ಲ.',
    alwaysActive: 'ಯಾವಾಗಲೂ ಸಕ್ರಿಯ',
    functional: 'ಕಾರ್ಯನಿರ್ವಹಣಾ',
    functionalDesc: 'ಎಡಿಟರ್ ಥೀಮ್, ಭಾಷೆ ಮತ್ತು ಲೇಔಟ್‌ನಂತಹ ನಿಮ್ಮ ಆದ್ಯತೆಗಳನ್ನು ನೆನಪಿಡುತ್ತದೆ.',
    analytics: 'ವಿಶ್ಲೇಷಣೆ',
    analyticsDesc: 'ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಅನ್ನು ಸುಧಾರಿಸಲು ನೀವು Codex ಅನ್ನು ಹೇಗೆ ಬಳಸುತ್ತೀರಿ ಎಂಬುದನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ.',
    advertising: 'ಜಾಹೀರಾತು',
    advertisingDesc: 'ಸೂಕ್ತವಾದ ಕೋಡಿಂಗ್ ಸವಾಲುಗಳನ್ನು ತೋರಿಸಲು ಮತ್ತು ಪ್ರಚಾರ ಪರಿಣಾಮಕಾರಿತ್ವವನ್ನು ಅಳೆಯಲು ಬಳಸಲಾಗುತ್ತದೆ.',
    dataItemsLabel: 'ಡೇಟಾ ಐಟಂಗಳು',
    servicesLabel: 'ಸಕ್ರಿಯಗೊಳಿಸಿದ ಸೇವೆಗಳು',
    retentionLabel: 'ಧಾರಣ',
    retentionDays: 'ದಿನಗಳು',
    consentLabel: 'ಸಮ್ಮತಿ',
    dpoLabel: 'ಡೇಟಾ ಸಂರಕ್ಷಣಾ ಅಧಿಕಾರಿ',
    withdrawLink: 'ಸಮ್ಮತಿಯನ್ನು ಹಿಂಪಡೆಯಿರಿ',
    rightsLink: 'ನಿಮ್ಮ ಹಕ್ಕುಗಳು',
    grievanceLink: 'ಕುಂದುಕೊರತೆ',
    boardComplaintLink: 'ಬೋರ್ಡ್ ದೂರು',
  },
  ml: {
    bannerTitle: 'ഞങ്ങൾ നിങ്ങളുടെ സ്വകാര്യതയെ മാനിക്കുന്നു',
    bannerText:
      'നിങ്ങളുടെ ബ്രൗസിംഗ് അനുഭവം മെച്ചപ്പെടുത്താനും നിങ്ങളെ സൈൻ ഇൻ ആയി നിലനിർത്താനും പ്ലാറ്റ്‌ഫോം എങ്ങനെ ഉപയോഗിക്കുന്നുവെന്ന് മനസ്സിലാക്കാനും Codex കുക്കികൾ ഉപയോഗിക്കുന്നു. നിങ്ങൾക്ക് എല്ലാ കുക്കികളും സ്വീകരിക്കാം അല്ലെങ്കിൽ വിഭാഗങ്ങൾ തിരഞ്ഞെടുക്കാം.',
    chooseLanguage: 'ഭാഷ തിരഞ്ഞെടുക്കുക',
    acceptAll: 'എല്ലാം സ്വീകരിക്കുക',
    rejectAll: 'എല്ലാം നിരസിക്കുക',
    moreOptions: 'കൂടുതൽ ഓപ്ഷനുകൾ',
    savePreferences: 'മുൻഗണനകൾ സംരക്ഷിക്കുക',
    saving: 'സംരക്ഷിക്കുന്നു…',
    viewFullNotice: 'പൂർണ്ണ അറിയിപ്പ് കാണുക',
    necessary: 'കർശനമായി ആവശ്യമായത്',
    necessaryDesc: 'സൈറ്റ് പ്രവർത്തിക്കാൻ ആവശ്യമാണ്, നിങ്ങളെ സൈൻ ഇൻ ആയി നിലനിർത്തുന്നത് പോലുള്ളവ. ഇവ പ്രവർത്തനരഹിതമാക്കാൻ കഴിയില്ല.',
    alwaysActive: 'എപ്പോഴും സജീവം',
    functional: 'ഫങ്ഷണൽ',
    functionalDesc: 'എഡിറ്റർ തീം, ഭാഷ, ലേഔട്ട് പോലുള്ള നിങ്ങളുടെ മുൻഗണനകൾ ഓർമ്മിക്കുന്നു.',
    analytics: 'അനലിറ്റിക്സ്',
    analyticsDesc: 'പ്ലാറ്റ്‌ഫോം മെച്ചപ്പെടുത്താൻ നിങ്ങൾ Codex എങ്ങനെ ഉപയോഗിക്കുന്നുവെന്ന് മനസ്സിലാക്കാൻ സഹായിക്കുന്നു.',
    advertising: 'പരസ്യം',
    advertisingDesc: 'പ്രസക്തമായ കോഡിംഗ് വെല്ലുവിളികൾ കാണിക്കാനും കാമ്പെയ്ൻ ഫലപ്രാപ്തി അളക്കാനും ഉപയോഗിക്കുന്നു.',
    dataItemsLabel: 'ഡാറ്റാ ഇനങ്ങൾ',
    servicesLabel: 'സജീവമാക്കിയ സേവനങ്ങൾ',
    retentionLabel: 'നിലനിർത്തൽ',
    retentionDays: 'ദിവസങ്ങൾ',
    consentLabel: 'സമ്മതം',
    dpoLabel: 'ഡാറ്റാ സംരക്ഷണ ഓഫീസർ',
    withdrawLink: 'സമ്മതം പിൻവലിക്കുക',
    rightsLink: 'നിങ്ങളുടെ അവകാശങ്ങൾ',
    grievanceLink: 'പരാതി',
    boardComplaintLink: 'ബോർഡ് പരാതി',
  },
  bn: {
    bannerTitle: 'আমরা আপনার গোপনীয়তাকে গুরুত্ব দিই',
    bannerText:
      'আপনার ব্রাউজিং অভিজ্ঞতা উন্নত করতে, আপনাকে সাইন ইন রাখতে এবং প্ল্যাটফর্মটি কীভাবে ব্যবহৃত হয় তা বুঝতে Codex কুকি ব্যবহার করে। আপনি সব কুকি গ্রহণ করতে পারেন অথবা বিভাগ নির্বাচন করতে পারেন।',
    chooseLanguage: 'ভাষা নির্বাচন করুন',
    acceptAll: 'সব গ্রহণ করুন',
    rejectAll: 'সব প্রত্যাখ্যান করুন',
    moreOptions: 'আরও বিকল্প',
    savePreferences: 'পছন্দগুলি সংরক্ষণ করুন',
    saving: 'সংরক্ষণ করা হচ্ছে…',
    viewFullNotice: 'সম্পূর্ণ নোটিশ দেখুন',
    necessary: 'কঠোরভাবে প্রয়োজনীয়',
    necessaryDesc: 'সাইট কাজ করার জন্য প্রয়োজনীয়, যেমন আপনাকে সাইন ইন রাখা। এগুলো নিষ্ক্রিয় করা যায় না।',
    alwaysActive: 'সর্বদা সক্রিয়',
    functional: 'ফাংশনাল',
    functionalDesc: 'এডিটর থিম, ভাষা এবং লেআউটের মতো আপনার পছন্দগুলি মনে রাখে।',
    analytics: 'বিশ্লেষণ',
    analyticsDesc: 'প্ল্যাটফর্ম উন্নত করতে আপনি কীভাবে Codex ব্যবহার করেন তা বুঝতে সাহায্য করে।',
    advertising: 'বিজ্ঞাপন',
    advertisingDesc: 'প্রাসঙ্গিক কোডিং চ্যালেঞ্জ দেখাতে এবং প্রচারাভিযানের কার্যকারিতা পরিমাপ করতে ব্যবহৃত হয়।',
    dataItemsLabel: 'ডেটা আইটেম',
    servicesLabel: 'সক্রিয় পরিষেবা',
    retentionLabel: 'সংরক্ষণকাল',
    retentionDays: 'দিন',
    consentLabel: 'সম্মতি',
    dpoLabel: 'ডেটা সুরক্ষা কর্মকর্তা',
    withdrawLink: 'সম্মতি প্রত্যাহার করুন',
    rightsLink: 'আপনার অধিকার',
    grievanceLink: 'অভিযোগ',
    boardComplaintLink: 'বোর্ড অভিযোগ',
  },
  mr: {
    bannerTitle: 'आम्ही तुमच्या गोपनीयतेला महत्त्व देतो',
    bannerText:
      'तुमचा ब्राउझिंग अनुभव सुधारण्यासाठी, तुम्हाला साइन इन ठेवण्यासाठी आणि प्लॅटफॉर्म कसा वापरला जातो हे समजून घेण्यासाठी Codex कुकीज वापरते. तुम्ही सर्व कुकीज स्वीकारू शकता किंवा श्रेणी निवडू शकता.',
    chooseLanguage: 'भाषा निवडा',
    acceptAll: 'सर्व स्वीकारा',
    rejectAll: 'सर्व नाकारा',
    moreOptions: 'अधिक पर्याय',
    savePreferences: 'प्राधान्ये जतन करा',
    saving: 'जतन करत आहे…',
    viewFullNotice: 'संपूर्ण सूचना पहा',
    necessary: 'कडकपणे आवश्यक',
    necessaryDesc: 'साइट कार्य करण्यासाठी आवश्यक, जसे की तुम्हाला साइन इन ठेवणे. हे अक्षम केले जाऊ शकत नाहीत.',
    alwaysActive: 'नेहमी सक्रिय',
    functional: 'कार्यात्मक',
    functionalDesc: 'एडिटर थीम, भाषा आणि लेआउट सारख्या तुमच्या प्राधान्यांची आठवण ठेवते.',
    analytics: 'विश्लेषण',
    analyticsDesc: 'प्लॅटफॉर्म सुधारण्यासाठी तुम्ही Codex कसे वापरता हे समजून घेण्यास मदत करते.',
    advertising: 'जाहिरात',
    advertisingDesc: 'संबंधित कोडिंग आव्हाने दाखवण्यासाठी आणि मोहिमेची परिणामकारकता मोजण्यासाठी वापरले जाते.',
    dataItemsLabel: 'डेटा आयटम',
    servicesLabel: 'सक्रिय केलेल्या सेवा',
    retentionLabel: 'धारणा',
    retentionDays: 'दिवस',
    consentLabel: 'संमती',
    dpoLabel: 'डेटा संरक्षण अधिकारी',
    withdrawLink: 'संमती मागे घ्या',
    rightsLink: 'तुमचे हक्क',
    grievanceLink: 'तक्रार',
    boardComplaintLink: 'मंडळ तक्रार',
  },
  gu: {
    bannerTitle: 'અમે તમારી ગોપનીયતાને મહત્વ આપીએ છીએ',
    bannerText:
      'તમારા બ્રાઉઝિંગ અનુભવને વધારવા, તમને સાઇન ઇન રાખવા અને પ્લેટફોર્મનો ઉપયોગ કેવી રીતે થાય છે તે સમજવા માટે Codex કૂકીઝનો ઉપયોગ કરે છે. તમે બધી કૂકીઝ સ્વીકારી શકો છો અથવા શ્રેણીઓ પસંદ કરી શકો છો.',
    chooseLanguage: 'ભાષા પસંદ કરો',
    acceptAll: 'બધું સ્વીકારો',
    rejectAll: 'બધું નકારો',
    moreOptions: 'વધુ વિકલ્પો',
    savePreferences: 'પસંદગીઓ સાચવો',
    saving: 'સાચવી રહ્યું છે…',
    viewFullNotice: 'સંપૂર્ણ સૂચના જુઓ',
    necessary: 'સખત જરૂરી',
    necessaryDesc: 'સાઇટ કામ કરવા માટે જરૂરી, જેમ કે તમને સાઇન ઇન રાખવું. આ અક્ષમ કરી શકાતા નથી.',
    alwaysActive: 'હંમેશા સક્રિય',
    functional: 'ફંક્શનલ',
    functionalDesc: 'એડિટર થીમ, ભાષા અને લેઆઉટ જેવી તમારી પસંદગીઓ યાદ રાખે છે.',
    analytics: 'વિશ્લેષણ',
    analyticsDesc: 'પ્લેટફોર્મ સુધારવા માટે તમે Codexનો ઉપયોગ કેવી રીતે કરો છો તે સમજવામાં મદદ કરે છે.',
    advertising: 'જાહેરાત',
    advertisingDesc: 'સંબંધિત કોડિંગ પડકારો બતાવવા અને ઝુંબેશ અસરકારકતા માપવા માટે ઉપયોગ થાય છે.',
    dataItemsLabel: 'ડેટા આઇટમ્સ',
    servicesLabel: 'સક્રિય કરેલી સેવાઓ',
    retentionLabel: 'જાળવણી',
    retentionDays: 'દિવસો',
    consentLabel: 'સંમતિ',
    dpoLabel: 'ડેટા સંરક્ષણ અધિકારી',
    withdrawLink: 'સંમતિ પાછી ખેંચો',
    rightsLink: 'તમારા અધિકારો',
    grievanceLink: 'ફરિયાદ',
    boardComplaintLink: 'બોર્ડ ફરિયાદ',
  },
  pa: {
    bannerTitle: 'ਅਸੀਂ ਤੁਹਾਡੀ ਪਰਦੇਦਾਰੀ ਦੀ ਕਦਰ ਕਰਦੇ ਹਾਂ',
    bannerText:
      'ਤੁਹਾਡੇ ਬ੍ਰਾਊਜ਼ਿੰਗ ਅਨੁਭਵ ਨੂੰ ਵਧਾਉਣ, ਤੁਹਾਨੂੰ ਸਾਈਨ ਇਨ ਰੱਖਣ ਅਤੇ ਪਲੇਟਫਾਰਮ ਦੀ ਵਰਤੋਂ ਕਿਵੇਂ ਹੁੰਦੀ ਹੈ ਇਹ ਸਮਝਣ ਲਈ Codex ਕੂਕੀਜ਼ ਦੀ ਵਰਤੋਂ ਕਰਦਾ ਹੈ। ਤੁਸੀਂ ਸਾਰੀਆਂ ਕੂਕੀਜ਼ ਸਵੀਕਾਰ ਕਰ ਸਕਦੇ ਹੋ ਜਾਂ ਸ਼੍ਰੇਣੀਆਂ ਚੁਣ ਸਕਦੇ ਹੋ।',
    chooseLanguage: 'ਭਾਸ਼ਾ ਚੁਣੋ',
    acceptAll: 'ਸਭ ਸਵੀਕਾਰ ਕਰੋ',
    rejectAll: 'ਸਭ ਰੱਦ ਕਰੋ',
    moreOptions: 'ਹੋਰ ਵਿਕਲਪ',
    savePreferences: 'ਤਰਜੀਹਾਂ ਸੰਭਾਲੋ',
    saving: 'ਸੰਭਾਲਿਆ ਜਾ ਰਿਹਾ ਹੈ…',
    viewFullNotice: 'ਪੂਰਾ ਨੋਟਿਸ ਵੇਖੋ',
    necessary: 'ਬਿਲਕੁਲ ਜ਼ਰੂਰੀ',
    necessaryDesc: 'ਸਾਈਟ ਦੇ ਕੰਮ ਕਰਨ ਲਈ ਜ਼ਰੂਰੀ, ਜਿਵੇਂ ਤੁਹਾਨੂੰ ਸਾਈਨ ਇਨ ਰੱਖਣਾ। ਇਹਨਾਂ ਨੂੰ ਅਯੋਗ ਨਹੀਂ ਕੀਤਾ ਜਾ ਸਕਦਾ।',
    alwaysActive: 'ਹਮੇਸ਼ਾ ਸਰਗਰਮ',
    functional: 'ਕਾਰਜਸ਼ੀਲ',
    functionalDesc: 'ਐਡੀਟਰ ਥੀਮ, ਭਾਸ਼ਾ ਅਤੇ ਲੇਆਉਟ ਵਰਗੀਆਂ ਤੁਹਾਡੀਆਂ ਤਰਜੀਹਾਂ ਯਾਦ ਰੱਖਦਾ ਹੈ।',
    analytics: 'ਵਿਸ਼ਲੇਸ਼ਣ',
    analyticsDesc: 'ਪਲੇਟਫਾਰਮ ਨੂੰ ਬਿਹਤਰ ਬਣਾਉਣ ਲਈ ਤੁਸੀਂ Codex ਦੀ ਵਰਤੋਂ ਕਿਵੇਂ ਕਰਦੇ ਹੋ ਇਹ ਸਮਝਣ ਵਿੱਚ ਮਦਦ ਕਰਦਾ ਹੈ।',
    advertising: 'ਵਿਗਿਆਪਨ',
    advertisingDesc: 'ਸੰਬੰਧਿਤ ਕੋਡਿੰਗ ਚੁਣੌਤੀਆਂ ਦਿਖਾਉਣ ਅਤੇ ਮੁਹਿੰਮ ਦੀ ਪ੍ਰਭਾਵਸ਼ੀਲਤਾ ਮਾਪਣ ਲਈ ਵਰਤਿਆ ਜਾਂਦਾ ਹੈ।',
    dataItemsLabel: 'ਡੇਟਾ ਆਈਟਮਾਂ',
    servicesLabel: 'ਸਰਗਰਮ ਸੇਵਾਵਾਂ',
    retentionLabel: 'ਧਾਰਨ',
    retentionDays: 'ਦਿਨ',
    consentLabel: 'ਸਹਿਮਤੀ',
    dpoLabel: 'ਡੇਟਾ ਸੁਰੱਖਿਆ ਅਧਿਕਾਰੀ',
    withdrawLink: 'ਸਹਿਮਤੀ ਵਾਪਸ ਲਵੋ',
    rightsLink: 'ਤੁਹਾਡੇ ਅਧਿਕਾਰ',
    grievanceLink: 'ਸ਼ਿਕਾਇਤ',
    boardComplaintLink: 'ਬੋਰਡ ਸ਼ਿਕਾਇਤ',
  },
}
