"""create crm_customers table

Revision ID: 7dfd0b9e7e08
Revises: a1b2c3d4e5f6
Create Date: 2026-08-17 16:59:58.797800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7dfd0b9e7e08'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crm_customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('aadhar_number', sa.String(length=32), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('consent_preferences', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_crm_customers_email')
    )
    op.create_index(op.f('ix_crm_customers_email'), 'crm_customers', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crm_customers_email'), table_name='crm_customers')
    op.drop_table('crm_customers')
    # ### end Alembic commands ###
