"""R3-08 breach register: breaches, affected principals, filings, extensions

Four tables backing the Rule 7 breach workflow (see app/models/breach.py for
the content-item mapping and app/services/breach.py for the clocks):

* `breaches` - the register itself. `detected_at` and `aware_at` are separate
  columns and a CHECK constraint stops awareness preceding detection, because
  every statutory clock runs from awareness ("on becoming aware", R.7; "within
  6 hours of noticing", CERT-In Directions 2022) and a clock started too early
  is a false compliance claim.
* `breach_affected_principals` - the R.7(1) scope, kept separate from the
  filings so "we have not established who is affected" and "we know and have
  not told them" are distinguishable positions.
* `breach_notifications` - one row per filing (PRINCIPAL / BOARD / CERT_IN),
  with its deadline, its send/delivery timestamps and a SHA-256 `content_hash`
  over the canonical JSON of the structured payload.
* `breach_extension_requests` - the written request under the R.7(2)(b)
  proviso and the Board's answer to it.

Encrypted columns are emitted as their underlying `sa.String`/`sa.Text` impl,
matching e1a2b3c4d5e6's convention: `EncryptedString(n)` is a TypeDecorator
whose impl is `String(n)`, so the DDL and the model agree and `alembic check`
sees no drift.

Revision ID: b2c4f6a8d013
Revises: d1a0e5c73b21
Create Date: 2026-09-04 09:57:44.884633

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "b2c4f6a8d013"
down_revision: Union[str, None] = "d1a0e5c73b21"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breaches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('breach_ref', sa.String(length=64), nullable=False),
    sa.Column('source_app', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('aware_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nature', sa.Text(), nullable=False),
    sa.Column('extent', sa.Text(), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('likely_impact', sa.Text(), nullable=False),
    sa.Column('likely_consequences', sa.Text(), nullable=False),
    sa.Column('mitigation_measures', sa.Text(), nullable=False),
    sa.Column('safety_measures', sa.Text(), nullable=False),
    sa.Column('cause', sa.Text(), nullable=False),
    sa.Column('findings_on_actor', sa.Text(), nullable=False),
    sa.Column('remedial_measures', sa.Text(), nullable=False),
    sa.Column('contact_name', sa.String(length=256), nullable=False),
    sa.Column('contact_email', sa.String(512), nullable=False),
    sa.Column('contact_phone', sa.String(256), nullable=False),
    sa.Column('cert_in_reportable', sa.Boolean(), nullable=False),
    sa.Column('cert_in_not_reportable_reason', sa.Text(), nullable=False),
    sa.Column('affected_count', sa.Integer(), nullable=False),
    sa.Column('scope_finalised_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closure_note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("severity IN ('LOW','MEDIUM','HIGH','CRITICAL')", name='ck_breaches_severity'),
    sa.CheckConstraint("status IN ('DETECTED','CLASSIFIED','CONTAINED','NOTIFIED','CLOSED')", name='ck_breaches_status'),
    sa.CheckConstraint('aware_at IS NULL OR detected_at IS NULL OR aware_at >= detected_at', name='ck_breaches_aware_after_detected'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('breach_ref', name='uq_breaches_breach_ref')
    )
    op.create_index(op.f('ix_breaches_aware_at'), 'breaches', ['aware_at'], unique=False)
    op.create_index(op.f('ix_breaches_breach_ref'), 'breaches', ['breach_ref'], unique=False)
    op.create_index(op.f('ix_breaches_created_at'), 'breaches', ['created_at'], unique=False)
    op.create_index(op.f('ix_breaches_detected_at'), 'breaches', ['detected_at'], unique=False)
    op.create_index(op.f('ix_breaches_severity'), 'breaches', ['severity'], unique=False)
    op.create_index(op.f('ix_breaches_source_app'), 'breaches', ['source_app'], unique=False)
    op.create_index(op.f('ix_breaches_status'), 'breaches', ['status'], unique=False)
    op.create_index(op.f('ix_breaches_tenant_id'), 'breaches', ['tenant_id'], unique=False)
    op.create_table('breach_affected_principals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('breach_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('data_involved', sa.Text(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('added_by', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['breach_id'], ['breaches.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('breach_id', 'customer_id', name='uq_breach_affected_customer')
    )
    op.create_index(op.f('ix_breach_affected_principals_breach_id'), 'breach_affected_principals', ['breach_id'], unique=False)
    op.create_index(op.f('ix_breach_affected_principals_customer_id'), 'breach_affected_principals', ['customer_id'], unique=False)
    op.create_index(op.f('ix_breach_affected_principals_tenant_id'), 'breach_affected_principals', ['tenant_id'], unique=False)
    op.create_table('breach_extension_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('breach_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('requested_by', sa.String(length=64), nullable=False),
    sa.Column('requested_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('written_request_ref', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.String(length=64), nullable=False),
    sa.Column('granted_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('board_reference', sa.String(length=256), nullable=False),
    sa.Column('decision_note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status <> 'GRANTED' OR granted_until IS NOT NULL", name='ck_breach_extension_granted_has_date'),
    sa.CheckConstraint("status IN ('REQUESTED','GRANTED','REFUSED','WITHDRAWN')", name='ck_breach_extension_status'),
    sa.ForeignKeyConstraint(['breach_id'], ['breaches.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_breach_extension_requests_breach_id'), 'breach_extension_requests', ['breach_id'], unique=False)
    op.create_index(op.f('ix_breach_extension_requests_requested_at'), 'breach_extension_requests', ['requested_at'], unique=False)
    op.create_index(op.f('ix_breach_extension_requests_status'), 'breach_extension_requests', ['status'], unique=False)
    op.create_index(op.f('ix_breach_extension_requests_tenant_id'), 'breach_extension_requests', ['tenant_id'], unique=False)
    op.create_table('breach_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('breach_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('recipient_type', sa.String(length=16), nullable=False),
    sa.Column('stage', sa.String(length=16), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('notification_id', sa.Integer(), nullable=True),
    sa.Column('recipient', sa.String(512), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('clock_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('target_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline_basis', sa.String(length=256), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('filing_reference', sa.String(length=256), nullable=False),
    sa.Column('generated_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("recipient_type IN ('PRINCIPAL','BOARD','CERT_IN')", name='ck_breach_notifications_recipient_type'),
    sa.CheckConstraint("stage IN ('NOTICE','INITIAL','DETAILED')", name='ck_breach_notifications_stage'),
    sa.CheckConstraint("status IN ('PENDING','QUEUED','SENT','DELIVERED','FAILED')", name='ck_breach_notifications_status'),
    sa.ForeignKeyConstraint(['breach_id'], ['breaches.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('breach_id', 'recipient_type', 'stage', 'customer_id', name='uq_breach_notification_filing')
    )
    op.create_index(op.f('ix_breach_notifications_breach_id'), 'breach_notifications', ['breach_id'], unique=False)
    op.create_index(
        'uq_breach_notification_regulator_filing', 'breach_notifications',
        ['breach_id', 'recipient_type', 'stage'], unique=True,
        postgresql_where=sa.text('customer_id IS NULL'),
    )
    op.create_index(op.f('ix_breach_notifications_content_hash'), 'breach_notifications', ['content_hash'], unique=False)
    op.create_index(op.f('ix_breach_notifications_created_at'), 'breach_notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_breach_notifications_customer_id'), 'breach_notifications', ['customer_id'], unique=False)
    op.create_index(op.f('ix_breach_notifications_deadline_at'), 'breach_notifications', ['deadline_at'], unique=False)
    op.create_index(op.f('ix_breach_notifications_recipient_type'), 'breach_notifications', ['recipient_type'], unique=False)
    op.create_index(op.f('ix_breach_notifications_status'), 'breach_notifications', ['status'], unique=False)
    op.create_index(op.f('ix_breach_notifications_tenant_id'), 'breach_notifications', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_breach_notifications_tenant_id'), table_name='breach_notifications')
    op.drop_index(op.f('ix_breach_notifications_status'), table_name='breach_notifications')
    op.drop_index(op.f('ix_breach_notifications_recipient_type'), table_name='breach_notifications')
    op.drop_index(op.f('ix_breach_notifications_deadline_at'), table_name='breach_notifications')
    op.drop_index(op.f('ix_breach_notifications_customer_id'), table_name='breach_notifications')
    op.drop_index(op.f('ix_breach_notifications_created_at'), table_name='breach_notifications')
    op.drop_index(op.f('ix_breach_notifications_content_hash'), table_name='breach_notifications')
    op.drop_index('uq_breach_notification_regulator_filing', table_name='breach_notifications')
    op.drop_index(op.f('ix_breach_notifications_breach_id'), table_name='breach_notifications')
    op.drop_table('breach_notifications')
    op.drop_index(op.f('ix_breach_extension_requests_tenant_id'), table_name='breach_extension_requests')
    op.drop_index(op.f('ix_breach_extension_requests_status'), table_name='breach_extension_requests')
    op.drop_index(op.f('ix_breach_extension_requests_requested_at'), table_name='breach_extension_requests')
    op.drop_index(op.f('ix_breach_extension_requests_breach_id'), table_name='breach_extension_requests')
    op.drop_table('breach_extension_requests')
    op.drop_index(op.f('ix_breach_affected_principals_tenant_id'), table_name='breach_affected_principals')
    op.drop_index(op.f('ix_breach_affected_principals_customer_id'), table_name='breach_affected_principals')
    op.drop_index(op.f('ix_breach_affected_principals_breach_id'), table_name='breach_affected_principals')
    op.drop_table('breach_affected_principals')
    op.drop_index(op.f('ix_breaches_tenant_id'), table_name='breaches')
    op.drop_index(op.f('ix_breaches_status'), table_name='breaches')
    op.drop_index(op.f('ix_breaches_source_app'), table_name='breaches')
    op.drop_index(op.f('ix_breaches_severity'), table_name='breaches')
    op.drop_index(op.f('ix_breaches_detected_at'), table_name='breaches')
    op.drop_index(op.f('ix_breaches_created_at'), table_name='breaches')
    op.drop_index(op.f('ix_breaches_breach_ref'), table_name='breaches')
    op.drop_index(op.f('ix_breaches_aware_at'), table_name='breaches')
    op.drop_table('breaches')
    # ### end Alembic commands ###
