"""R2-05 data-principal rights: rights_requests, rights_request_events, nominations

Adds the three tables defined in `app/models/rights.py`:

  nominations           - s.14 / R.14(4): the individual a principal nominates
                          to exercise her rights on her death or incapacity,
                          with the nominee's own confirmation and a staff
                          activation that requires recorded evidence
  rights_requests       - ss.11-14: the register of access, correction,
                          erasure and nomination requests, with the R.14(2)
                          identity check, both SLA clocks and closure evidence
  rights_request_events - the per-request timeline the queue and the
                          principal's own view render

Table order matters: `rights_requests.nomination_id` is a foreign key into
`nominations`, so that table is created first, and dropped last.

Hand-written rather than autogenerated. `alembic/env.py` imports only
`app.models.entities`, and `entities.py` does not yet carry the
`from app.models import rights` line that would register these classes in
`Base.metadata` for autogenerate to see (that one line belongs to the lane
that owns `entities.py`). Writing the revision by hand also guarantees it has
exactly one parent while other lanes are adding migrations of their own -
`f3c4d5e6a7b8` was the single head when this was allocated.

Every CHECK constraint here is a copy of one declared in
`app/models/rights.py`, and the two must never diverge. The four that are load
bearing rather than merely tidy:

  ck_rights_requests_fulfilled_is_verified
      A request cannot reach FULFILLED without `identity_verified`. DPDP Rules
      2025 R.14(2) requires the fiduciary to verify the requester, and an
      access request fulfilled for the wrong person discloses one individual's
      entire record - contact details, consent history and the identity of
      every processor their data reached - to another. The service layer
      refuses it first; this makes it unrepresentable.

  ck_rights_requests_verified_has_evidence
      `identity_verified` without a method and a moment is a claim with no
      evidence behind it, so it cannot be stored.

  ck_rights_requests_closed_has_evidence
      No CLOSED request without `closed_at` and `closure_hash`. The same shape
      as `ck_erasure_jobs_executed_has_evidence`, for the same reason: the
      evidence is the deliverable, not a report written afterwards.

  ck_nominations_active_is_authorised
      A nomination cannot be ACTIVE without a named activator, a moment, a
      statutory ground and a non-empty evidence reference. Activation happens
      at exactly the moment the principal cannot contradict a false claim, so
      it is required to be attributable and checkable.

Both foreign keys into `consent_contexts` are ON DELETE SET NULL, and that
is load bearing rather than stylistic: `consent_contexts` is one of the record
classes the R1-06 erasure engine hard deletes, so a restricting key here would
make an erasure raise at the moment of execution - the engine an ERASURE
rights request delegates to would be broken by the very table that delegates
to it. See `app/models/rights.py::RightsRequest.verification_context_id`.

Nothing here is destructive and `downgrade()` drops only what `upgrade()`
created, so a round trip on a database that predates this revision leaves it
exactly as it was.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "c1d2e3f4a5b6"
down_revision: Union[str, None] = "f3c4d5e6a7b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ---- s.14 nominations (created first: rights_requests references it) ---
    op.create_table(
        "nominations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=True),
        sa.Column("nomination_ref", sa.String(length=32), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("nominee_name", sa.String(length=512), nullable=False),
        sa.Column("nominee_email", sa.String(length=512), nullable=False, server_default=""),
        sa.Column("nominee_email_search", sa.String(length=64), nullable=True),
        sa.Column("nominee_phone", sa.String(length=256), nullable=False, server_default=""),
        sa.Column("nominee_relationship", sa.String(length=64), nullable=False, server_default=""),
        sa.Column("status", sa.String(length=16), nullable=False, server_default="PENDING"),
        sa.Column("principal_context_id", sa.Integer(), nullable=True),
        sa.Column(
            "nominated_at", sa.DateTime(timezone=True), nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column("verification_code_hash", sa.String(length=64), nullable=True),
        sa.Column("verification_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verification_attempts", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("max_verification_attempts", sa.Integer(), nullable=False, server_default="5"),
        sa.Column("verification_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("activated_by", sa.String(length=128), nullable=True),
        sa.Column("activation_ground", sa.String(length=16), nullable=True),
        sa.Column(
            "activation_evidence_ref", sa.String(length=256), nullable=False, server_default=""
        ),
        sa.Column("activation_note", sa.Text(), nullable=False, server_default=""),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_by", sa.String(length=128), nullable=True),
        sa.Column("revocation_reason", sa.Text(), nullable=False, server_default=""),
        sa.Column("source_app", sa.String(length=128), nullable=False, server_default=""),
        sa.Column("created_by", sa.String(length=128), nullable=False, server_default=""),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["organizations.id"]),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"]),
        sa.ForeignKeyConstraint(
            ["principal_context_id"], ["consent_contexts.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint(
            "status IN ('PENDING','VERIFIED','ACTIVE','DECLINED','REVOKED')",
            name="ck_nominations_status",
        ),
        sa.CheckConstraint(
            "status NOT IN ('VERIFIED','ACTIVE') OR verified_at IS NOT NULL",
            name="ck_nominations_verified_has_timestamp",
        ),
        sa.CheckConstraint(
            "status <> 'ACTIVE' OR (activated_at IS NOT NULL AND activated_by IS NOT NULL "
            "AND activation_ground IS NOT NULL AND length(trim(activation_evidence_ref)) > 0)",
            name="ck_nominations_active_is_authorised",
        ),
        sa.CheckConstraint(
            "activation_ground IS NULL OR activation_ground IN ('DEATH','INCAPACITY')",
            name="ck_nominations_activation_ground",
        ),
        sa.CheckConstraint(
            "verification_attempts >= 0 AND max_verification_attempts > 0",
            name="ck_nominations_attempt_budget",
        ),
    )
    op.create_index(
        op.f("ix_nominations_nomination_ref"), "nominations", ["nomination_ref"], unique=True
    )
    op.create_index(op.f("ix_nominations_tenant_id"), "nominations", ["tenant_id"], unique=False)
    op.create_index(
        op.f("ix_nominations_customer_id"), "nominations", ["customer_id"], unique=False
    )
    op.create_index(op.f("ix_nominations_status"), "nominations", ["status"], unique=False)
    op.create_index(
        op.f("ix_nominations_source_app"), "nominations", ["source_app"], unique=False
    )
    op.create_index(
        op.f("ix_nominations_nominee_email_search"), "nominations", ["nominee_email_search"],
        unique=False,
    )
    op.create_index(
        "ix_nominations_tenant_customer_status", "nominations",
        ["tenant_id", "customer_id", "status"], unique=False,
    )

    # ---- ss.11-14 rights requests -----------------------------------------
    op.create_table(
        "rights_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=True),
        sa.Column("reference_no", sa.String(length=32), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("request_type", sa.String(length=16), nullable=False),
        sa.Column("channel", sa.String(length=16), nullable=False, server_default="PORTAL"),
        sa.Column("status", sa.String(length=16), nullable=False, server_default="RECEIVED"),
        sa.Column("request_detail", sa.Text(), nullable=False, server_default=""),
        sa.Column("requested_changes", sa.Text(), nullable=False, server_default="{}"),
        sa.Column("applied_changes", sa.Text(), nullable=False, server_default="{}"),
        sa.Column(
            "received_at", sa.DateTime(timezone=True), nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acknowledgement_hours", sa.Integer(), nullable=False, server_default="72"),
        sa.Column("acknowledgement_due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("response_days", sa.Integer(), nullable=False, server_default="90"),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "identity_verified", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
        sa.Column("verification_method", sa.String(length=32), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verification_context_id", sa.Integer(), nullable=True),
        sa.Column("verification_note", sa.String(length=256), nullable=False, server_default=""),
        sa.Column("assigned_to", sa.String(length=128), nullable=False, server_default=""),
        sa.Column("fulfilled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fulfilled_by", sa.String(length=128), nullable=False, server_default=""),
        sa.Column("resolution_summary", sa.Text(), nullable=False, server_default=""),
        sa.Column("rejection_reason", sa.String(length=48), nullable=True),
        sa.Column("rejection_basis", sa.Text(), nullable=False, server_default=""),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_by", sa.String(length=128), nullable=False, server_default=""),
        sa.Column("closure_hash", sa.String(length=64), nullable=True),
        sa.Column("erasure_job_id", sa.Integer(), nullable=True),
        sa.Column("nomination_id", sa.Integer(), nullable=True),
        sa.Column("package_hash", sa.String(length=64), nullable=True),
        sa.Column("source_app", sa.String(length=128), nullable=False, server_default=""),
        sa.Column("created_by", sa.String(length=128), nullable=False, server_default=""),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["organizations.id"]),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"]),
        sa.ForeignKeyConstraint(
            ["verification_context_id"], ["consent_contexts.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["erasure_job_id"], ["erasure_jobs.id"]),
        sa.ForeignKeyConstraint(["nomination_id"], ["nominations.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint(
            "request_type IN ('ACCESS','CORRECTION','ERASURE','NOMINATION')",
            name="ck_rights_requests_type",
        ),
        sa.CheckConstraint(
            "status IN ('RECEIVED','ACKNOWLEDGED','VERIFYING','IN_PROGRESS',"
            "'FULFILLED','REJECTED','CLOSED')",
            name="ck_rights_requests_status",
        ),
        sa.CheckConstraint(
            "channel IN ('PORTAL','STAFF','EMAIL','PHONE','POST','OTHER')",
            name="ck_rights_requests_channel",
        ),
        sa.CheckConstraint(
            "response_days > 0 AND response_days <= 90",
            name="ck_rights_requests_response_days",
        ),
        sa.CheckConstraint(
            "acknowledgement_hours > 0 AND acknowledgement_hours <= 2160",
            name="ck_rights_requests_acknowledgement_hours",
        ),
        sa.CheckConstraint(
            "status <> 'FULFILLED' OR identity_verified",
            name="ck_rights_requests_fulfilled_is_verified",
        ),
        sa.CheckConstraint(
            "identity_verified = false OR "
            "(verified_at IS NOT NULL AND verification_method IS NOT NULL)",
            name="ck_rights_requests_verified_has_evidence",
        ),
        sa.CheckConstraint(
            "verification_method IS NULL OR "
            "verification_method IN ('EMAIL_OTP','FIDUCIARY_ASSERTED')",
            name="ck_rights_requests_verification_method",
        ),
        sa.CheckConstraint(
            "status <> 'CLOSED' OR (closed_at IS NOT NULL AND closure_hash IS NOT NULL)",
            name="ck_rights_requests_closed_has_evidence",
        ),
        sa.CheckConstraint(
            "status <> 'REJECTED' OR rejection_reason IS NOT NULL",
            name="ck_rights_requests_rejected_has_reason",
        ),
        sa.CheckConstraint(
            "rejection_reason IS NULL OR rejection_reason IN ("
            "'IDENTITY_NOT_ESTABLISHED','RETENTION_REQUIRED_BY_LAW','LEGAL_HOLD',"
            "'PURPOSE_STILL_SERVED','NOT_A_DATA_PRINCIPAL','DUPLICATE',"
            "'WITHDRAWN_BY_PRINCIPAL','OTHER')",
            name="ck_rights_requests_rejection_reason",
        ),
    )
    op.create_index(
        op.f("ix_rights_requests_reference_no"), "rights_requests", ["reference_no"], unique=True
    )
    op.create_index(
        op.f("ix_rights_requests_tenant_id"), "rights_requests", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_rights_requests_customer_id"), "rights_requests", ["customer_id"], unique=False
    )
    op.create_index(
        op.f("ix_rights_requests_request_type"), "rights_requests", ["request_type"], unique=False
    )
    op.create_index(
        op.f("ix_rights_requests_status"), "rights_requests", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_rights_requests_received_at"), "rights_requests", ["received_at"], unique=False
    )
    op.create_index(
        op.f("ix_rights_requests_due_at"), "rights_requests", ["due_at"], unique=False
    )
    op.create_index(
        op.f("ix_rights_requests_identity_verified"), "rights_requests", ["identity_verified"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rights_requests_fulfilled_at"), "rights_requests", ["fulfilled_at"], unique=False
    )
    op.create_index(
        op.f("ix_rights_requests_rejection_reason"), "rights_requests", ["rejection_reason"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rights_requests_closure_hash"), "rights_requests", ["closure_hash"], unique=False
    )
    op.create_index(
        op.f("ix_rights_requests_erasure_job_id"), "rights_requests", ["erasure_job_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rights_requests_nomination_id"), "rights_requests", ["nomination_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rights_requests_source_app"), "rights_requests", ["source_app"], unique=False
    )
    op.create_index(
        "ix_rights_requests_tenant_status_due", "rights_requests",
        ["tenant_id", "status", "due_at"], unique=False,
    )
    op.create_index(
        "ix_rights_requests_tenant_type", "rights_requests", ["tenant_id", "request_type"],
        unique=False,
    )

    # ---- the per-request timeline -----------------------------------------
    op.create_table(
        "rights_request_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.Integer(), nullable=False),
        sa.Column("from_status", sa.String(length=16), nullable=False, server_default=""),
        sa.Column("to_status", sa.String(length=16), nullable=False, server_default=""),
        sa.Column("event", sa.String(length=48), nullable=False),
        sa.Column("note", sa.Text(), nullable=False, server_default=""),
        sa.Column("actor_username", sa.String(length=128), nullable=False, server_default="system"),
        sa.Column(
            "visible_to_principal", sa.Boolean(), nullable=False, server_default=sa.true()
        ),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.ForeignKeyConstraint(["request_id"], ["rights_requests.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_rights_request_events_request_id"), "rights_request_events", ["request_id"],
        unique=False,
    )
    op.create_index(
        "ix_rights_request_events_request_created", "rights_request_events",
        ["request_id", "created_at"], unique=False,
    )


def downgrade() -> None:
    op.drop_index("ix_rights_request_events_request_created", table_name="rights_request_events")
    op.drop_index(
        op.f("ix_rights_request_events_request_id"), table_name="rights_request_events"
    )
    op.drop_table("rights_request_events")

    op.drop_index("ix_rights_requests_tenant_type", table_name="rights_requests")
    op.drop_index("ix_rights_requests_tenant_status_due", table_name="rights_requests")
    for index in (
        "ix_rights_requests_source_app",
        "ix_rights_requests_nomination_id",
        "ix_rights_requests_erasure_job_id",
        "ix_rights_requests_closure_hash",
        "ix_rights_requests_rejection_reason",
        "ix_rights_requests_fulfilled_at",
        "ix_rights_requests_identity_verified",
        "ix_rights_requests_due_at",
        "ix_rights_requests_received_at",
        "ix_rights_requests_status",
        "ix_rights_requests_request_type",
        "ix_rights_requests_customer_id",
        "ix_rights_requests_tenant_id",
        "ix_rights_requests_reference_no",
    ):
        op.drop_index(op.f(index), table_name="rights_requests")
    op.drop_table("rights_requests")

    op.drop_index("ix_nominations_tenant_customer_status", table_name="nominations")
    for index in (
        "ix_nominations_nominee_email_search",
        "ix_nominations_source_app",
        "ix_nominations_status",
        "ix_nominations_customer_id",
        "ix_nominations_tenant_id",
        "ix_nominations_nomination_ref",
    ):
        op.drop_index(op.f(index), table_name="nominations")
    op.drop_table("nominations")
