"""R1-14 children and guardian consent: age assurance, guardian consents, Fourth Schedule exemptions

Adds the three tables defined in `app/models/guardian.py` for DPDP Act s.9 and
DPDP Rules 2025 R.10-R.12 with the Fourth Schedule:

  principal_age_assurances - F-01: one age-assurance finding per Customer,
                             with the child flag every enforcement point reads
  guardian_consents        - F-02/F-03: verifiable parental (s.9(1)/R.10) and
                             lawful-guardian (R.11) consent, with its evidence
  tenant_child_exemptions  - F-05: the narrow, per-tenant R.12 exemption
                             register

Written by hand rather than autogenerated, for the same reason
`c1d2e3f4a5b6` was: it guarantees exactly one parent while other lanes are
adding migrations of their own. `c1d2e3f4a5b6` was the single head when this
was allocated (verified with `alembic heads`).

Unlike that revision, the models here ARE registered in `Base.metadata` -
`app/models/__init__.py` imports `app.models.guardian`, which it can do
because nothing in that module imports `entities.py` (see the docstring
there). So `alembic check` compares these tables against the models, and every
column, index and constraint below has to match `app/models/guardian.py`
exactly.

Every CHECK constraint here is a copy of one declared in that module and the
two must never diverge. The five that are load bearing rather than tidy:

  ck_age_assurances_self_declared_is_not_verified
      A pre-ticked "I am 18+" box cannot be stored as a verified age
      assurance. R.10(1) requires due diligence, and the demo sites' existing
      self-declaration is the gap F-01 is about - recording it honestly as
      unverified is the fix, and this makes the honest record the only
      representable one.

  ck_guardian_consents_verified_has_evidence
      No VERIFIED guardian consent without a verifier, a moment, an evidence
      reference, an evidence hash, and the finding that the consenting person
      is an adult. The three questions a challenged fiduciary is asked -
      who consented, how were they verified, when - are answered by columns,
      and a row that cannot answer them is unwritable. Same shape as
      ck_rights_requests_fulfilled_is_verified.

  ck_guardian_consents_virtual_token_verified_has_moment
      The Digital Locker route (R.10(2)(c)) is an INTERFACE in this build with
      no integration behind it. This constraint is what stops an unimplemented
      integration being quietly treated as a completed one: a VERIFIED
      virtual-token row with no moment of actual token confirmation cannot be
      stored, whatever the service layer is later persuaded to do.

  ck_guardian_consents_lawful_guardian_is_appointed
      R.11: a lawful guardian is lawful because a court, a designated
      authority or a local level committee appointed them. An unappointed
      "guardian" is a stranger asserting authority over a person with
      disability.

  ck_child_exemptions_purposes_not_empty / _obligations_not_empty
      A Fourth Schedule exemption with an empty purpose list would apply to
      everything - the blanket switch R.12 is not. Postgres refuses to store
      it. `json_array_length` is used rather than a trigger because the
      columns are JSON and the check is a pure function of the value.

Encrypted columns (`EncryptedString`/`EncryptedText`/`EncryptedJSON` in the
models) are created as plain VARCHAR/TEXT here, exactly as every prior
migration in this tree does: the encryption is a SQLAlchemy TypeDecorator, so
what reaches Postgres is ciphertext text and the column type is the text type
that holds it. The widths are the models' widths.

Nothing here is destructive and `downgrade()` drops only what `upgrade()`
created, in reverse dependency order.

Revision ID: c3f4a5b6c7d8
Revises: c1d2e3f4a5b6
Create Date: 2026-09-04
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "c3f4a5b6c7d8"
down_revision: Union[str, None] = "c1d2e3f4a5b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ----------------------------------------------------------------- #
    # F-01: principal_age_assurances
    # ----------------------------------------------------------------- #
    op.create_table(
        "principal_age_assurances",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=True),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("is_child", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column(
            "is_person_with_disability",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
        sa.Column("assurance_method", sa.String(length=32), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        # EncryptedString(64): ISO-8601 date, stored as ciphertext.
        sa.Column("date_of_birth", sa.String(length=64), nullable=True),
        sa.Column(
            "assurance_reference", sa.String(length=256), nullable=False, server_default=sa.text("''")
        ),
        sa.Column("token_issuer", sa.String(length=128), nullable=True),
        sa.Column("assured_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("assured_by", sa.String(length=128), nullable=True),
        # EncryptedJSON -> TEXT ciphertext.
        sa.Column("details", sa.Text(), nullable=False, server_default=sa.text("'{}'")),
        sa.Column("source_app", sa.String(length=128), nullable=False, server_default=sa.text("''")),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["organizations.id"]),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("customer_id", name="uq_principal_age_assurances_customer"),
        sa.CheckConstraint(
            "assurance_method IN ('SELF_DECLARED','DECLARED_DATE_OF_BIRTH',"
            "'FIDUCIARY_HELD_RECORD','IDENTITY_DOCUMENT','VIRTUAL_TOKEN')",
            name="ck_age_assurances_method",
        ),
        sa.CheckConstraint(
            "is_verified = false OR assurance_method <> 'SELF_DECLARED'",
            name="ck_age_assurances_self_declared_is_not_verified",
        ),
        sa.CheckConstraint(
            "is_verified = false OR (assured_at IS NOT NULL AND assured_by IS NOT NULL)",
            name="ck_age_assurances_verified_has_evidence",
        ),
        sa.CheckConstraint(
            "assurance_method <> 'VIRTUAL_TOKEN' OR "
            "(token_issuer IS NOT NULL AND length(trim(token_issuer)) > 0)",
            name="ck_age_assurances_virtual_token_has_issuer",
        ),
    )
    op.create_index(
        "ix_principal_age_assurances_tenant_id", "principal_age_assurances", ["tenant_id"]
    )
    op.create_index(
        "ix_principal_age_assurances_customer_id", "principal_age_assurances", ["customer_id"]
    )
    op.create_index("ix_principal_age_assurances_is_child", "principal_age_assurances", ["is_child"])
    op.create_index(
        "ix_principal_age_assurances_is_person_with_disability",
        "principal_age_assurances",
        ["is_person_with_disability"],
    )
    op.create_index(
        "ix_principal_age_assurances_source_app", "principal_age_assurances", ["source_app"]
    )
    op.create_index(
        "ix_age_assurances_tenant_is_child", "principal_age_assurances", ["tenant_id", "is_child"]
    )

    # ----------------------------------------------------------------- #
    # F-02 / F-03: guardian_consents
    # ----------------------------------------------------------------- #
    op.create_table(
        "guardian_consents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=True),
        sa.Column("reference_no", sa.String(length=32), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column(
            "guardian_type", sa.String(length=16), nullable=False, server_default=sa.text("'PARENT'")
        ),
        sa.Column("verification_method", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False, server_default=sa.text("'PENDING'")),
        sa.Column("guardian_name", sa.String(length=512), nullable=False),
        sa.Column(
            "guardian_email", sa.String(length=512), nullable=False, server_default=sa.text("''")
        ),
        sa.Column("guardian_email_search", sa.String(length=64), nullable=True),
        sa.Column(
            "guardian_phone", sa.String(length=256), nullable=False, server_default=sa.text("''")
        ),
        sa.Column(
            "guardian_is_adult", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
        sa.Column("guardian_customer_id", sa.Integer(), nullable=True),
        sa.Column("guardian_context_id", sa.Integer(), nullable=True),
        sa.Column("guardian_identity_reference", sa.String(length=256), nullable=True),
        sa.Column("guardian_date_of_birth", sa.String(length=64), nullable=True),
        sa.Column("virtual_token_issuer", sa.String(length=128), nullable=True),
        sa.Column("virtual_token_reference", sa.String(length=512), nullable=True),
        sa.Column("virtual_token_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("appointment_authority", sa.String(length=32), nullable=True),
        sa.Column(
            "appointment_reference",
            sa.String(length=256),
            nullable=False,
            server_default=sa.text("''"),
        ),
        sa.Column("appointment_date", sa.Date(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_by", sa.String(length=128), nullable=True),
        sa.Column("verification_note", sa.Text(), nullable=False, server_default=sa.text("''")),
        sa.Column("evidence_ref", sa.String(length=64), nullable=True),
        sa.Column("evidence_hash", sa.String(length=64), nullable=True),
        sa.Column("rejection_reason", sa.String(length=48), nullable=True),
        sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejected_by", sa.String(length=128), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_by", sa.String(length=128), nullable=True),
        sa.Column("revocation_reason", sa.Text(), nullable=False, server_default=sa.text("''")),
        sa.Column("source_app", sa.String(length=128), nullable=False, server_default=sa.text("''")),
        sa.Column("created_by", sa.String(length=128), nullable=False, server_default=sa.text("''")),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["organizations.id"]),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"]),
        sa.ForeignKeyConstraint(["guardian_customer_id"], ["customers.id"]),
        # ON DELETE SET NULL, and that is load bearing rather than stylistic:
        # `consent_contexts` is one of the record classes the R1-06 erasure
        # engine hard deletes, so a restricting key here would make erasing
        # an adult raise at the moment of execution.
        sa.ForeignKeyConstraint(
            ["guardian_context_id"], ["consent_contexts.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint(
            "guardian_type IN ('PARENT','LAWFUL_GUARDIAN')", name="ck_guardian_consents_type"
        ),
        sa.CheckConstraint(
            "verification_method IN ('EXISTING_VERIFIED_ACCOUNT',"
            "'VOLUNTARILY_PROVIDED_DETAILS','VIRTUAL_TOKEN')",
            name="ck_guardian_consents_method",
        ),
        sa.CheckConstraint(
            "status IN ('PENDING','VERIFIED','REJECTED','REVOKED')",
            name="ck_guardian_consents_status",
        ),
        sa.CheckConstraint(
            "status <> 'VERIFIED' OR ("
            "verified_at IS NOT NULL AND verified_by IS NOT NULL "
            "AND guardian_is_adult AND evidence_ref IS NOT NULL "
            "AND evidence_hash IS NOT NULL)",
            name="ck_guardian_consents_verified_has_evidence",
        ),
        sa.CheckConstraint(
            "verification_method <> 'EXISTING_VERIFIED_ACCOUNT' "
            "OR guardian_customer_id IS NOT NULL",
            name="ck_guardian_consents_existing_account_is_linked",
        ),
        sa.CheckConstraint(
            "status <> 'VERIFIED' OR verification_method <> 'VOLUNTARILY_PROVIDED_DETAILS' "
            "OR (guardian_date_of_birth IS NOT NULL AND guardian_identity_reference IS NOT NULL)",
            name="ck_guardian_consents_voluntary_has_identity_and_age",
        ),
        sa.CheckConstraint(
            "verification_method <> 'VIRTUAL_TOKEN' OR "
            "(virtual_token_issuer IS NOT NULL AND length(trim(virtual_token_issuer)) > 0)",
            name="ck_guardian_consents_virtual_token_has_issuer",
        ),
        sa.CheckConstraint(
            "status <> 'VERIFIED' OR verification_method <> 'VIRTUAL_TOKEN' "
            "OR virtual_token_verified_at IS NOT NULL",
            name="ck_guardian_consents_virtual_token_verified_has_moment",
        ),
        sa.CheckConstraint(
            "guardian_type <> 'LAWFUL_GUARDIAN' OR ("
            "appointment_authority IS NOT NULL "
            "AND length(trim(appointment_reference)) > 0)",
            name="ck_guardian_consents_lawful_guardian_is_appointed",
        ),
        sa.CheckConstraint(
            "appointment_authority IS NULL OR appointment_authority IN "
            "('COURT','DESIGNATED_AUTHORITY','LOCAL_LEVEL_COMMITTEE')",
            name="ck_guardian_consents_appointment_authority",
        ),
        sa.CheckConstraint(
            "status <> 'REJECTED' OR rejection_reason IS NOT NULL",
            name="ck_guardian_consents_rejected_has_reason",
        ),
    )
    op.create_index("ix_guardian_consents_tenant_id", "guardian_consents", ["tenant_id"])
    op.create_index(
        "ix_guardian_consents_reference_no", "guardian_consents", ["reference_no"], unique=True
    )
    op.create_index("ix_guardian_consents_customer_id", "guardian_consents", ["customer_id"])
    op.create_index("ix_guardian_consents_status", "guardian_consents", ["status"])
    op.create_index(
        "ix_guardian_consents_guardian_email_search", "guardian_consents", ["guardian_email_search"]
    )
    op.create_index(
        "ix_guardian_consents_guardian_customer_id", "guardian_consents", ["guardian_customer_id"]
    )
    op.create_index("ix_guardian_consents_source_app", "guardian_consents", ["source_app"])
    op.create_index(
        "ix_guardian_consents_tenant_customer_status",
        "guardian_consents",
        ["tenant_id", "customer_id", "status"],
    )

    # ----------------------------------------------------------------- #
    # F-05: tenant_child_exemptions
    # ----------------------------------------------------------------- #
    op.create_table(
        "tenant_child_exemptions",
        sa.Column("id", sa.Integer(), nullable=False),
        # NOT NULL, unlike every other tenant_id in this migration: an
        # exemption belonging to no tenant would apply to all of them.
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("exemption_class", sa.String(length=48), nullable=False),
        sa.Column(
            "schedule_reference", sa.String(length=128), nullable=False, server_default=sa.text("''")
        ),
        sa.Column("purpose_codes", sa.JSON(), nullable=False, server_default=sa.text("'[]'")),
        sa.Column("exempted_obligations", sa.JSON(), nullable=False, server_default=sa.text("'[]'")),
        sa.Column("conditions", sa.Text(), nullable=False, server_default=sa.text("''")),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column(
            "effective_from",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("effective_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("authorised_by", sa.String(length=128), nullable=True),
        sa.Column("authorised_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=128), nullable=False, server_default=sa.text("''")),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["organizations.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint(
            "exemption_class IN ('HEALTHCARE_PROVIDER','ALLIED_HEALTHCARE_PROVIDER',"
            "'EDUCATIONAL_INSTITUTION','CHILD_CARE_OR_CRECHE','CHILD_TRANSPORT',"
            "'SPECIFIED_PURPOSE')",
            name="ck_child_exemptions_class",
        ),
        sa.CheckConstraint(
            "json_array_length(purpose_codes) > 0",
            name="ck_child_exemptions_purposes_not_empty",
        ),
        sa.CheckConstraint(
            "json_array_length(exempted_obligations) > 0",
            name="ck_child_exemptions_obligations_not_empty",
        ),
        sa.CheckConstraint(
            "is_active = false OR (authorised_by IS NOT NULL AND authorised_at IS NOT NULL "
            "AND length(trim(schedule_reference)) > 0)",
            name="ck_child_exemptions_active_is_authorised",
        ),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_to > effective_from",
            name="ck_child_exemptions_window",
        ),
    )
    op.create_index("ix_tenant_child_exemptions_tenant_id", "tenant_child_exemptions", ["tenant_id"])
    op.create_index(
        "ix_child_exemptions_tenant_active", "tenant_child_exemptions", ["tenant_id", "is_active"]
    )


def downgrade() -> None:
    op.drop_index("ix_child_exemptions_tenant_active", table_name="tenant_child_exemptions")
    op.drop_index("ix_tenant_child_exemptions_tenant_id", table_name="tenant_child_exemptions")
    op.drop_table("tenant_child_exemptions")

    op.drop_index("ix_guardian_consents_tenant_customer_status", table_name="guardian_consents")
    op.drop_index("ix_guardian_consents_source_app", table_name="guardian_consents")
    op.drop_index("ix_guardian_consents_guardian_customer_id", table_name="guardian_consents")
    op.drop_index("ix_guardian_consents_guardian_email_search", table_name="guardian_consents")
    op.drop_index("ix_guardian_consents_status", table_name="guardian_consents")
    op.drop_index("ix_guardian_consents_customer_id", table_name="guardian_consents")
    op.drop_index("ix_guardian_consents_reference_no", table_name="guardian_consents")
    op.drop_index("ix_guardian_consents_tenant_id", table_name="guardian_consents")
    op.drop_table("guardian_consents")

    op.drop_index("ix_age_assurances_tenant_is_child", table_name="principal_age_assurances")
    op.drop_index("ix_principal_age_assurances_source_app", table_name="principal_age_assurances")
    op.drop_index(
        "ix_principal_age_assurances_is_person_with_disability",
        table_name="principal_age_assurances",
    )
    op.drop_index("ix_principal_age_assurances_is_child", table_name="principal_age_assurances")
    op.drop_index("ix_principal_age_assurances_customer_id", table_name="principal_age_assurances")
    op.drop_index("ix_principal_age_assurances_tenant_id", table_name="principal_age_assurances")
    op.drop_table("principal_age_assurances")
