"""add translations column to purpose_versions

Revision ID: cee9a14a2b1d
Revises: 7dfd0b9e7e08
Create Date: 2026-08-17 17:26:34.440853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cee9a14a2b1d'
down_revision: Union[str, None] = '7dfd0b9e7e08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'purpose_versions',
        sa.Column('translations', sa.JSON(), nullable=False, server_default=sa.text("'{}'::json")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purpose_versions', 'translations')
    # ### end Alembic commands ###
