"""R2-06 grievance register

Creates `grievances` and `grievance_events` for the DPDP s.13 grievance
redressal module.

Two things in here are deliberate rather than incidental:

* `grievances.response_days` carries the same `> 0 AND <= 90` CHECK the
  `organizations.grievance_response_days` column already has. The value is a
  SNAPSHOT of the tenant's published period taken when the grievance is
  received, so a tenant that later changes what it publishes cannot move the
  deadline of a complaint already in flight - and the ceiling has to hold on
  the snapshot too, not only on the source it was copied from.

* `reference_no` is UNIQUE and stored in the clear, while `subject`,
  `description`, `escalated_to`, `resolution_summary`, `feedback_comment`
  and `grievance_events.note` are `EncryptedText` (AES-256-GCM at the
  SQLAlchemy type level). That split is the point: the narrative of a
  complaint is among the most sensitive text this platform holds and is
  never queried, whereas the reference is a non-identifying opaque token
  that has to stay indexable because it is the handle a complainant quotes
  to the Data Protection Board.

Revision ID: d1a0e5c73b21
Revises: b8d2f0a5c417
Create Date: 2026-09-04

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

import app.core.encryption

revision: str = "d1a0e5c73b21"
down_revision: Union[str, None] = "b8d2f0a5c417"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grievances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('reference_no', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('consent_id', sa.Integer(), nullable=True),
    sa.Column('purpose_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('subject', app.core.encryption.EncryptedText(), nullable=False),
    sa.Column('description', app.core.encryption.EncryptedText(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_days', sa.Integer(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('escalated_to', app.core.encryption.EncryptedText(), nullable=False),
    sa.Column('escalation_reason', sa.String(length=64), nullable=False),
    sa.Column('escalation_notification_id', sa.Integer(), nullable=True),
    sa.Column('assigned_to', sa.String(length=128), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=128), nullable=False),
    sa.Column('resolution_summary', app.core.encryption.EncryptedText(), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('feedback_rating', sa.Integer(), nullable=True),
    sa.Column('feedback_comment', app.core.encryption.EncryptedText(), nullable=False),
    sa.Column('feedback_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_app', sa.String(length=128), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("category IN ('CONSENT_NOT_HONOURED','ACCESS_REQUEST','CORRECTION_REQUEST','ERASURE_REQUEST','NOMINATION','UNAUTHORISED_PROCESSING','EXCESSIVE_COLLECTION','DATA_ACCURACY','SECURITY_INCIDENT','NOTICE_UNCLEAR','OTHER')", name='ck_grievances_category'),
    sa.CheckConstraint("channel IN ('PORTAL','STAFF','EMAIL','PHONE','POST','OTHER')", name='ck_grievances_channel'),
    sa.CheckConstraint("status IN ('RECEIVED','ACKNOWLEDGED','IN_PROGRESS','ESCALATED','RESOLVED','CLOSED')", name='ck_grievances_status'),
    sa.CheckConstraint('feedback_rating IS NULL OR (feedback_rating >= 1 AND feedback_rating <= 5)', name='ck_grievances_feedback_rating'),
    sa.CheckConstraint('response_days > 0 AND response_days <= 90', name='ck_grievances_response_days'),
    sa.ForeignKeyConstraint(['consent_id'], ['consents.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['escalation_notification_id'], ['notifications.id'], ),
    sa.ForeignKeyConstraint(['purpose_id'], ['purposes.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grievances_category'), 'grievances', ['category'], unique=False)
    op.create_index(op.f('ix_grievances_customer_id'), 'grievances', ['customer_id'], unique=False)
    op.create_index(op.f('ix_grievances_due_at'), 'grievances', ['due_at'], unique=False)
    op.create_index(op.f('ix_grievances_escalated_at'), 'grievances', ['escalated_at'], unique=False)
    op.create_index(op.f('ix_grievances_received_at'), 'grievances', ['received_at'], unique=False)
    op.create_index(op.f('ix_grievances_reference_no'), 'grievances', ['reference_no'], unique=True)
    op.create_index(op.f('ix_grievances_resolved_at'), 'grievances', ['resolved_at'], unique=False)
    op.create_index(op.f('ix_grievances_source_app'), 'grievances', ['source_app'], unique=False)
    op.create_index(op.f('ix_grievances_status'), 'grievances', ['status'], unique=False)
    op.create_index(op.f('ix_grievances_tenant_id'), 'grievances', ['tenant_id'], unique=False)
    op.create_index('ix_grievances_tenant_status_due', 'grievances', ['tenant_id', 'status', 'due_at'], unique=False)
    op.create_table('grievance_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grievance_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=16), nullable=False),
    sa.Column('to_status', sa.String(length=16), nullable=False),
    sa.Column('event', sa.String(length=48), nullable=False),
    sa.Column('note', app.core.encryption.EncryptedText(), nullable=False),
    sa.Column('actor_username', sa.String(length=128), nullable=False),
    sa.Column('visible_to_principal', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['grievance_id'], ['grievances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_grievance_events_grievance_created', 'grievance_events', ['grievance_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_grievance_events_grievance_id'), 'grievance_events', ['grievance_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grievance_events_grievance_id'), table_name='grievance_events')
    op.drop_index('ix_grievance_events_grievance_created', table_name='grievance_events')
    op.drop_table('grievance_events')
    op.drop_index('ix_grievances_tenant_status_due', table_name='grievances')
    op.drop_index(op.f('ix_grievances_tenant_id'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_status'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_source_app'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_resolved_at'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_reference_no'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_received_at'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_escalated_at'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_due_at'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_customer_id'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_category'), table_name='grievances')
    op.drop_table('grievances')
    # ### end Alembic commands ###
