"""R3-10 Consent Manager interoperability: registry, onboarding, consent artefacts

Adds the six tables defined in `app/models/artefacts.py` (see that module's
docstring for what each one is for):

  consent_managers            - Board-registered Consent Managers (s.6(7)-(9), R.4)
  consent_manager_fiduciaries - the fiduciary onboarding model (First Schedule Part B 1)
  consent_artefacts           - one brokered consent record
  consent_artefact_events     - its immutable, HMAC-signed versions
  consent_artefact_links      - the `consents` rows each artefact stands for
  consent_manager_api_calls   - availability/latency samples for CM-06 / K-42 / K-43

Three columns are declared here as their *underlying* SQL types because the
models use the field-level encryption TypeDecorators from
`app/core/encryption.py`, which store ciphertext in an ordinary column:

  consent_managers.contact_email          EncryptedString(512) -> VARCHAR(512)
  consent_managers.disclosures            EncryptedJSON        -> TEXT
  consent_manager_fiduciaries.notes       EncryptedText        -> TEXT
  consent_artefact_events.payload         EncryptedJSON        -> TEXT

`consent_artefact_events.payload` in particular must NOT be a json/jsonb column:
it is a snapshot of a record about a person, it carries the tenant's DPO contact
(itself an encrypted column on `organizations`), and for a fiduciary reading its
own tenant it carries the principal's external id and masked email.

Hand-written rather than autogenerated, so this revision has exactly one parent
while other lanes are also adding migrations.

Revision ID: e3d5b7c91a24
Revises: b2c4f6a8d013
Create Date: 2026-09-04 00:00:00.000000

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "e3d5b7c91a24"
down_revision: Union[str, None] = "b2c4f6a8d013"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "consent_managers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cm_ref", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("board_registration_number", sa.String(length=128), nullable=False),
        sa.Column("registration_status", sa.String(length=16), nullable=False),
        sa.Column("registered_at", sa.DateTime(timezone=True), nullable=True),
        # EncryptedString(512) — ciphertext, not the address itself.
        sa.Column("contact_email", sa.String(length=512), nullable=False),
        sa.Column("website_url", sa.String(length=512), nullable=False),
        # EncryptedJSON — names of directors/promoters/shareholders are personal
        # data of those natural persons even though Part B 11 publishes them.
        sa.Column("disclosures", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "registration_status IN ('PENDING','REGISTERED','SUSPENDED','DEREGISTERED')",
            name="ck_consent_managers_registration_status",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["organizations.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_consent_managers_cm_ref"), "consent_managers", ["cm_ref"], unique=True)
    op.create_index(
        op.f("ix_consent_managers_registration_status"),
        "consent_managers",
        ["registration_status"],
        unique=False,
    )
    # Unique: one Organization authenticates exactly one Consent Manager, so a
    # key issued to that tenant can never resolve ambiguously.
    op.create_index(op.f("ix_consent_managers_tenant_id"), "consent_managers", ["tenant_id"], unique=True)

    op.create_table(
        "consent_manager_fiduciaries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("consent_manager_id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("source_app", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("allowed_purpose_codes", sa.JSON(), nullable=False),
        sa.Column("onboarded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("terminated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("onboarded_by", sa.String(length=64), nullable=False),
        # EncryptedText — free text a staff user typed.
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('PENDING','ACTIVE','SUSPENDED','TERMINATED')",
            name="ck_cm_fiduciaries_status",
        ),
        sa.ForeignKeyConstraint(["consent_manager_id"], ["consent_managers.id"]),
        sa.ForeignKeyConstraint(["tenant_id"], ["organizations.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("consent_manager_id", "tenant_id", name="uq_cm_fiduciary_identity"),
    )
    op.create_index(
        op.f("ix_consent_manager_fiduciaries_consent_manager_id"),
        "consent_manager_fiduciaries",
        ["consent_manager_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_consent_manager_fiduciaries_source_app"),
        "consent_manager_fiduciaries",
        ["source_app"],
        unique=False,
    )
    op.create_index(
        op.f("ix_consent_manager_fiduciaries_status"),
        "consent_manager_fiduciaries",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_consent_manager_fiduciaries_tenant_id"),
        "consent_manager_fiduciaries",
        ["tenant_id"],
        unique=False,
    )

    op.create_table(
        "consent_artefacts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("artefact_ref", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.String(length=256), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("source_app", sa.String(length=128), nullable=False),
        sa.Column("consent_manager_id", sa.Integer(), nullable=True),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("principal_ref", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("artefact_version", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("withdrawn_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=64), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('ACTIVE','PARTIAL','WITHDRAWN','EXPIRED')",
            name="ck_consent_artefacts_status",
        ),
        sa.ForeignKeyConstraint(["consent_manager_id"], ["consent_managers.id"]),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"]),
        sa.ForeignKeyConstraint(["tenant_id"], ["organizations.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_consent_artefacts_artefact_ref"), "consent_artefacts", ["artefact_ref"], unique=True)
    op.create_index(
        op.f("ix_consent_artefacts_consent_manager_id"), "consent_artefacts", ["consent_manager_id"], unique=False
    )
    op.create_index(op.f("ix_consent_artefacts_created_at"), "consent_artefacts", ["created_at"], unique=False)
    op.create_index(op.f("ix_consent_artefacts_customer_id"), "consent_artefacts", ["customer_id"], unique=False)
    op.create_index(op.f("ix_consent_artefacts_principal_ref"), "consent_artefacts", ["principal_ref"], unique=False)
    op.create_index(op.f("ix_consent_artefacts_source_app"), "consent_artefacts", ["source_app"], unique=False)
    op.create_index(op.f("ix_consent_artefacts_status"), "consent_artefacts", ["status"], unique=False)
    op.create_index(op.f("ix_consent_artefacts_tenant_id"), "consent_artefacts", ["tenant_id"], unique=False)

    op.create_table(
        "consent_artefact_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("artefact_id", sa.Integer(), nullable=False),
        sa.Column("event_ref", sa.String(length=64), nullable=False),
        sa.Column("artefact_version", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=16), nullable=False),
        # EncryptedJSON, deliberately not sa.JSON — see this migration's docstring.
        sa.Column("payload", sa.Text(), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("signature", sa.Text(), nullable=False),
        sa.Column("signature_alg", sa.String(length=32), nullable=False),
        sa.Column("actor", sa.String(length=64), nullable=False),
        sa.Column("source_app", sa.String(length=128), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "event_type IN ('CREATED','UPDATED','WITHDRAWN','EXPIRED')",
            name="ck_consent_artefact_events_type",
        ),
        sa.ForeignKeyConstraint(["artefact_id"], ["consent_artefacts.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("artefact_id", "artefact_version", name="uq_artefact_event_version"),
    )
    op.create_index(
        op.f("ix_consent_artefact_events_artefact_id"), "consent_artefact_events", ["artefact_id"], unique=False
    )
    op.create_index(
        op.f("ix_consent_artefact_events_event_ref"), "consent_artefact_events", ["event_ref"], unique=True
    )
    op.create_index(
        op.f("ix_consent_artefact_events_occurred_at"), "consent_artefact_events", ["occurred_at"], unique=False
    )

    op.create_table(
        "consent_artefact_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("artefact_id", sa.Integer(), nullable=False),
        sa.Column("consent_id", sa.Integer(), nullable=False),
        sa.Column("purpose_id", sa.Integer(), nullable=False),
        sa.Column("purpose_code", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("withdrawn_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("status IN ('ACTIVE','WITHDRAWN')", name="ck_consent_artefact_links_status"),
        sa.ForeignKeyConstraint(["artefact_id"], ["consent_artefacts.id"]),
        sa.ForeignKeyConstraint(["consent_id"], ["consents.id"]),
        sa.ForeignKeyConstraint(["purpose_id"], ["purposes.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("artefact_id", "consent_id", name="uq_artefact_link_identity"),
    )
    op.create_index(
        op.f("ix_consent_artefact_links_artefact_id"), "consent_artefact_links", ["artefact_id"], unique=False
    )
    op.create_index(
        op.f("ix_consent_artefact_links_consent_id"), "consent_artefact_links", ["consent_id"], unique=False
    )
    op.create_index(
        op.f("ix_consent_artefact_links_purpose_id"), "consent_artefact_links", ["purpose_id"], unique=False
    )
    op.create_index(op.f("ix_consent_artefact_links_status"), "consent_artefact_links", ["status"], unique=False)

    op.create_table(
        "consent_manager_api_calls",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("consent_manager_id", sa.Integer(), nullable=True),
        sa.Column("tenant_id", sa.Integer(), nullable=True),
        sa.Column("endpoint", sa.String(length=128), nullable=False),
        sa.Column("method", sa.String(length=8), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["consent_manager_id"], ["consent_managers.id"]),
        sa.ForeignKeyConstraint(["tenant_id"], ["organizations.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_consent_manager_api_calls_consent_manager_id"),
        "consent_manager_api_calls",
        ["consent_manager_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_consent_manager_api_calls_endpoint"), "consent_manager_api_calls", ["endpoint"], unique=False
    )
    op.create_index(
        op.f("ix_consent_manager_api_calls_occurred_at"), "consent_manager_api_calls", ["occurred_at"], unique=False
    )
    op.create_index(
        op.f("ix_consent_manager_api_calls_outcome"), "consent_manager_api_calls", ["outcome"], unique=False
    )
    op.create_index(
        op.f("ix_consent_manager_api_calls_tenant_id"), "consent_manager_api_calls", ["tenant_id"], unique=False
    )


def downgrade() -> None:
    # Dropped in reverse dependency order. Note that a real deployment should
    # not reach for this: `consent_artefacts` and `consent_artefact_events` are
    # Consent Manager records under DPDP Rules First Schedule Part B 3 and 4(c)
    # with a 7-year retention floor, so dropping them destroys records that are
    # inside their statutory minimum holding period. This exists so the
    # migration is reversible in development, not as an operational procedure.
    op.drop_table("consent_manager_api_calls")
    op.drop_table("consent_artefact_links")
    op.drop_table("consent_artefact_events")
    op.drop_table("consent_artefacts")
    op.drop_table("consent_manager_fiduciaries")
    op.drop_table("consent_managers")
