"""R1-06 retention and erasure engine: policies, legal holds, erasure jobs

Adds the three tables defined in `app/models/erasure.py` (read that module's
docstring for what each is for and why the columns are what they are):

  retention_policies - the erasure *ceiling* per record class and tenant scope,
                       plus the R.8(2) notice period and the R.8(1)/Third
                       Schedule inactivity clock
  legal_holds        - a standing instruction that named data must NOT be
                       erased, which outranks both the ceiling and a
                       principal's own s.12(3) request
  erasure_jobs       - one erasure, from the moment it becomes due through its
                       authorisation and its 48-hour notice to the evidence
                       that it happened

and one column on an existing table:

  customers.last_interaction_at - the zero point of the R.8(1) + Third Schedule
                       three-year clock, deliberately separate from
                       `updated_at` (which moves for writes the principal had
                       nothing to do with; see the column's own comment).

Two columns are declared as their *underlying* SQL types because the models
use the field-level encryption TypeDecorators from `app/core/encryption.py`,
which store ciphertext in an ordinary column:

  legal_holds.reason   EncryptedText -> TEXT

The CHECK constraints are not decoration. Three of them carry a legal
requirement that must hold even for a row written straight into the database
by a script or a future migration:

  ck_retention_policies_notice_hours       >= 48, because DPDP Rules 2025
      R.8(2) states a minimum ("at least forty-eight hours"), so a longer
      notice is configurable and a shorter one is not representable.
  ck_erasure_jobs_executed_has_evidence    an EXECUTED job must carry
      executed_at and evidence_hash - the DoD ("an erasure_jobs row as
      evidence") as a database constraint rather than an application promise.
  ck_erasure_jobs_executed_is_authorised   an EXECUTED job must name who
      authorised it. A row that reached EXECUTED with no authoriser is exactly
      the silent background deletion this engine refuses to perform.

The default `retention_policies` rows are NOT seeded here. They carry long
statutory-basis prose that belongs in exactly one place
(`app/services/erasure.py::ensure_default_policies`), and a copy in a
migration would be a second source of truth that drifts; that function is
idempotent and is called before any path that reads a policy.

Hand-written rather than autogenerated, so this revision has exactly one
parent while other lanes are also adding migrations.

**Parent note.** This revision was allocated `down_revision = "e3d5b7c91a24"`,
which was the single head at the time. Another lane's `f4d5e6a7b8c9`
(banner_events, R2-07) landed on that same parent two minutes earlier, which
made two heads - and two heads make `alembic upgrade head` fail outright, so
`tests/conftest.py` (which runs it in-process at session start) takes the
entire suite down for every lane at once. Chaining this revision onto
`f4d5e6a7b8c9` instead restores a single linear head without touching the
other lane's file. Nothing else about this revision changes; if the lanes are
ever reordered, this is the only line that needs to move.

Revision ID: f1a2b3c4d5e6
Revises: f4d5e6a7b8c9
Create Date: 2026-09-04 00:00:00.000000

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "f1a2b3c4d5e6"
down_revision: Union[str, None] = "f4d5e6a7b8c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_RECORD_CLASS_IN = (
    "('principal_personal_data','directory_record','consent_contexts','notifications')"
)


def upgrade() -> None:
    op.add_column(
        "customers",
        sa.Column("last_interaction_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index(
        op.f("ix_customers_last_interaction_at"), "customers", ["last_interaction_at"],
        unique=False,
    )

    op.create_table(
        "retention_policies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=True),
        sa.Column("policy_ref", sa.String(length=64), nullable=False),
        sa.Column("record_class", sa.String(length=64), nullable=False),
        sa.Column("scope", sa.String(length=128), nullable=False, server_default="*"),
        sa.Column("retention_days", sa.Integer(), nullable=True),
        sa.Column("inactivity_days", sa.Integer(), nullable=True),
        sa.Column(
            "pre_erasure_notice_hours", sa.Integer(), nullable=False, server_default="48"
        ),
        sa.Column("action", sa.String(length=16), nullable=False, server_default="ANONYMISE"),
        sa.Column("legal_basis_for_retention", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("notes", sa.Text(), nullable=False, server_default=""),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column("updated_by", sa.String(length=64), nullable=False, server_default="system"),
        sa.ForeignKeyConstraint(["tenant_id"], ["organizations.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("record_class", "scope", name="uq_retention_policies_class_scope"),
        sa.CheckConstraint(
            f"record_class IN {_RECORD_CLASS_IN}", name="ck_retention_policies_record_class"
        ),
        sa.CheckConstraint("action IN ('ERASE','ANONYMISE')", name="ck_retention_policies_action"),
        sa.CheckConstraint(
            "pre_erasure_notice_hours >= 48", name="ck_retention_policies_notice_hours"
        ),
        sa.CheckConstraint(
            "retention_days IS NULL OR retention_days > 0",
            name="ck_retention_policies_retention_days",
        ),
        sa.CheckConstraint(
            "inactivity_days IS NULL OR inactivity_days > 0",
            name="ck_retention_policies_inactivity_days",
        ),
        sa.CheckConstraint(
            "length(trim(legal_basis_for_retention)) > 0",
            name="ck_retention_policies_legal_basis_present",
        ),
    )
    op.create_index(
        op.f("ix_retention_policies_policy_ref"), "retention_policies", ["policy_ref"], unique=True
    )
    op.create_index(
        op.f("ix_retention_policies_record_class"), "retention_policies", ["record_class"],
        unique=False,
    )
    op.create_index(
        op.f("ix_retention_policies_tenant_id"), "retention_policies", ["tenant_id"], unique=False
    )

    op.create_table(
        "legal_holds",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=True),
        sa.Column("hold_ref", sa.String(length=64), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.Column("record_class", sa.String(length=64), nullable=True),
        # EncryptedText -> TEXT: the reason a hold exists routinely names the
        # person and the proceeding.
        sa.Column("reason", sa.Text(), nullable=False, server_default=""),
        sa.Column("legal_basis", sa.String(length=512), nullable=False),
        sa.Column("placed_by", sa.String(length=64), nullable=False),
        sa.Column(
            "placed_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("released_by", sa.String(length=64), nullable=True),
        sa.Column("release_reason", sa.Text(), nullable=False, server_default=""),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(["tenant_id"], ["organizations.id"]),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint(
            f"record_class IS NULL OR record_class IN {_RECORD_CLASS_IN}",
            name="ck_legal_holds_record_class",
        ),
        sa.CheckConstraint(
            "length(trim(legal_basis)) > 0", name="ck_legal_holds_legal_basis_present"
        ),
    )
    op.create_index(op.f("ix_legal_holds_hold_ref"), "legal_holds", ["hold_ref"], unique=True)
    op.create_index(op.f("ix_legal_holds_tenant_id"), "legal_holds", ["tenant_id"], unique=False)
    op.create_index(
        op.f("ix_legal_holds_customer_id"), "legal_holds", ["customer_id"], unique=False
    )
    op.create_index(
        "ix_legal_holds_tenant_active", "legal_holds", ["tenant_id", "is_active", "customer_id"],
        unique=False,
    )

    op.create_table(
        "erasure_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=True),
        sa.Column("job_ref", sa.String(length=64), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("purpose_id", sa.Integer(), nullable=True),
        sa.Column("policy_id", sa.Integer(), nullable=True),
        sa.Column("trigger", sa.String(length=32), nullable=False),
        sa.Column("trigger_ref", sa.String(length=160), nullable=False),
        sa.Column("action", sa.String(length=16), nullable=False, server_default="ANONYMISE"),
        sa.Column("status", sa.String(length=16), nullable=False, server_default="PROPOSED"),
        sa.Column("authorised_by", sa.String(length=64), nullable=True),
        sa.Column("authorised_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("authorisation_basis", sa.Text(), nullable=False, server_default=""),
        sa.Column("notice_required", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("notice_hours", sa.Integer(), nullable=False, server_default="48"),
        sa.Column("notice_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notification_ids", sa.JSON(), nullable=False, server_default="[]"),
        sa.Column("execute_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("executed_by", sa.String(length=64), nullable=True),
        sa.Column("records_erased", sa.JSON(), nullable=False, server_default="{}"),
        sa.Column("records_retained", sa.JSON(), nullable=False, server_default="{}"),
        sa.Column("processor_alert_ids", sa.JSON(), nullable=False, server_default="[]"),
        sa.Column("anonymised_ref", sa.String(length=64), nullable=True),
        sa.Column("evidence_hash", sa.String(length=64), nullable=True),
        sa.Column("blocked_reason", sa.Text(), nullable=False, server_default=""),
        sa.Column("hold_id", sa.Integer(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_by", sa.String(length=64), nullable=True),
        sa.Column("cancel_reason", sa.Text(), nullable=False, server_default=""),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("source_app", sa.String(length=128), nullable=False, server_default=""),
        sa.Column("created_by", sa.String(length=64), nullable=False, server_default="system"),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False, server_default=""),
        sa.Column("details", sa.JSON(), nullable=False, server_default="{}"),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["organizations.id"]),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"]),
        sa.ForeignKeyConstraint(["purpose_id"], ["purposes.id"]),
        sa.ForeignKeyConstraint(["policy_id"], ["retention_policies.id"]),
        sa.ForeignKeyConstraint(["hold_id"], ["legal_holds.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "customer_id", "trigger_ref", name="uq_erasure_jobs_customer_trigger"
        ),
        sa.CheckConstraint(
            "trigger IN ('WITHDRAWAL','RIGHTS_REQUEST','RETENTION','INACTIVITY','MANUAL')",
            name="ck_erasure_jobs_trigger",
        ),
        sa.CheckConstraint("action IN ('ERASE','ANONYMISE')", name="ck_erasure_jobs_action"),
        sa.CheckConstraint(
            "status IN ('PROPOSED','SCHEDULED','NOTIFIED','BLOCKED','EXECUTED','CANCELLED','FAILED')",
            name="ck_erasure_jobs_status",
        ),
        sa.CheckConstraint(
            "status <> 'EXECUTED' OR (executed_at IS NOT NULL AND evidence_hash IS NOT NULL)",
            name="ck_erasure_jobs_executed_has_evidence",
        ),
        sa.CheckConstraint(
            "status <> 'EXECUTED' OR authorised_by IS NOT NULL",
            name="ck_erasure_jobs_executed_is_authorised",
        ),
    )
    op.create_index(op.f("ix_erasure_jobs_job_ref"), "erasure_jobs", ["job_ref"], unique=True)
    op.create_index(op.f("ix_erasure_jobs_tenant_id"), "erasure_jobs", ["tenant_id"], unique=False)
    op.create_index(
        op.f("ix_erasure_jobs_customer_id"), "erasure_jobs", ["customer_id"], unique=False
    )
    op.create_index(op.f("ix_erasure_jobs_trigger"), "erasure_jobs", ["trigger"], unique=False)
    op.create_index(
        op.f("ix_erasure_jobs_trigger_ref"), "erasure_jobs", ["trigger_ref"], unique=False
    )
    op.create_index(op.f("ix_erasure_jobs_status"), "erasure_jobs", ["status"], unique=False)
    op.create_index(
        op.f("ix_erasure_jobs_evidence_hash"), "erasure_jobs", ["evidence_hash"], unique=False
    )
    op.create_index(
        op.f("ix_erasure_jobs_created_at"), "erasure_jobs", ["created_at"], unique=False
    )
    op.create_index(
        "ix_erasure_jobs_status_execute_after", "erasure_jobs", ["status", "execute_after"],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index("ix_erasure_jobs_status_execute_after", table_name="erasure_jobs")
    op.drop_index(op.f("ix_erasure_jobs_created_at"), table_name="erasure_jobs")
    op.drop_index(op.f("ix_erasure_jobs_evidence_hash"), table_name="erasure_jobs")
    op.drop_index(op.f("ix_erasure_jobs_status"), table_name="erasure_jobs")
    op.drop_index(op.f("ix_erasure_jobs_trigger_ref"), table_name="erasure_jobs")
    op.drop_index(op.f("ix_erasure_jobs_trigger"), table_name="erasure_jobs")
    op.drop_index(op.f("ix_erasure_jobs_customer_id"), table_name="erasure_jobs")
    op.drop_index(op.f("ix_erasure_jobs_tenant_id"), table_name="erasure_jobs")
    op.drop_index(op.f("ix_erasure_jobs_job_ref"), table_name="erasure_jobs")
    op.drop_table("erasure_jobs")

    op.drop_index("ix_legal_holds_tenant_active", table_name="legal_holds")
    op.drop_index(op.f("ix_legal_holds_customer_id"), table_name="legal_holds")
    op.drop_index(op.f("ix_legal_holds_tenant_id"), table_name="legal_holds")
    op.drop_index(op.f("ix_legal_holds_hold_ref"), table_name="legal_holds")
    op.drop_table("legal_holds")

    op.drop_index(op.f("ix_retention_policies_tenant_id"), table_name="retention_policies")
    op.drop_index(op.f("ix_retention_policies_record_class"), table_name="retention_policies")
    op.drop_index(op.f("ix_retention_policies_policy_ref"), table_name="retention_policies")
    op.drop_table("retention_policies")

    op.drop_index(op.f("ix_customers_last_interaction_at"), table_name="customers")
    op.drop_column("customers", "last_interaction_at")
