"""R1-09 re-consent on material change: change log, campaigns, cookie policy versions

Adds the three tables defined in `app/models/reconsent.py`:

  policy_change_log      - one row per publication of a versioned artefact,
                           MATERIAL or not, with the per-field diff and the
                           reasoning behind the classification
  re_consent_campaigns   - the drive started by one material change; K-09's
                           numerator and denominator both live here
  cookie_policy_versions - P-03: the cookie policy, versioned like everything
                           else a principal is shown

and three columns on `consents`:

  re_consent_required      - read by services/decision_engine.py, which
                             refuses to ALLOW while it is set. Not a UI hint.
  re_consent_requested_at  - deliberately NOT the existing `requested_at`,
                             which already means "when request_consent first
                             moved this row to REQUESTED". Two clocks, two
                             columns.
  re_consent_campaign_id   - the campaign that flagged it.

`re_consent_required` is created NOT NULL with a server default of false, so
every consent that predates this migration is unflagged and nothing that was
previously allowed is silently blocked by the schema change itself. A block
only ever arrives from an actual material publication.

**Parent note.** This revision was allocated `down_revision = "f2b3c4d5e6a7"`,
but that id already belongs to an existing, long-merged migration
(`f2b3c4d5e6a7_add_scheduler_and_kpi_tables.py`, which already has a child in
`a3c4d5e6f7b8`). Chaining to it would fork the history into two heads and
`alembic upgrade head` would fail outright for every lane. It is chained to
the head that actually exists instead - R1-06's `f1a2b3c4d5e6`, from this same
lane - which keeps a single linear head. If the intended parent was a
different lane's not-yet-written revision, this is the only line that needs to
move.

Hand-written rather than autogenerated, so this revision has exactly one
parent while other lanes are also adding migrations.

Revision ID: f3c4d5e6a7b8
Revises: f1a2b3c4d5e6
Create Date: 2026-09-04 00:00:00.000000

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "f3c4d5e6a7b8"
down_revision: Union[str, None] = "f1a2b3c4d5e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "re_consent_campaigns",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=True),
        sa.Column("campaign_ref", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=16), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("entity_code", sa.String(length=128), nullable=False, server_default=""),
        sa.Column("from_version", sa.Integer(), nullable=True),
        sa.Column("to_version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False, server_default="OPEN"),
        sa.Column("reason", sa.Text(), nullable=False, server_default=""),
        sa.Column("consents_flagged", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("notifications_queued", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("fresh_consents", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("started_by", sa.String(length=64), nullable=False, server_default="system"),
        sa.Column(
            "started_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_reason", sa.Text(), nullable=False, server_default=""),
        sa.Column("source_app", sa.String(length=128), nullable=False, server_default=""),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False, server_default="{}"),
        sa.ForeignKeyConstraint(["tenant_id"], ["organizations.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint(
            "status IN ('OPEN','COMPLETED','CANCELLED')", name="ck_re_consent_campaigns_status"
        ),
    )
    op.create_index(
        op.f("ix_re_consent_campaigns_campaign_ref"), "re_consent_campaigns", ["campaign_ref"],
        unique=True,
    )
    op.create_index(
        op.f("ix_re_consent_campaigns_tenant_id"), "re_consent_campaigns", ["tenant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_re_consent_campaigns_entity_id"), "re_consent_campaigns", ["entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_re_consent_campaigns_status"), "re_consent_campaigns", ["status"], unique=False
    )

    op.create_table(
        "policy_change_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=True),
        sa.Column("change_ref", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=16), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("entity_code", sa.String(length=128), nullable=False, server_default=""),
        sa.Column("from_version", sa.Integer(), nullable=True),
        sa.Column("to_version", sa.Integer(), nullable=False),
        sa.Column("materiality", sa.String(length=16), nullable=False),
        sa.Column("changed_fields", sa.JSON(), nullable=False, server_default="{}"),
        sa.Column("materiality_basis", sa.Text(), nullable=False, server_default=""),
        sa.Column("overridden_by", sa.String(length=64), nullable=True),
        sa.Column("override_justification", sa.Text(), nullable=False, server_default=""),
        sa.Column("affected_consents", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("campaign_id", sa.Integer(), nullable=True),
        sa.Column("actor_username", sa.String(length=64), nullable=False, server_default="system"),
        sa.Column("source_app", sa.String(length=128), nullable=False, server_default=""),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["organizations.id"]),
        sa.ForeignKeyConstraint(["campaign_id"], ["re_consent_campaigns.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint(
            "entity_type IN ('PURPOSE','POLICY','NOTICE','COOKIE_POLICY')",
            name="ck_policy_change_log_entity_type",
        ),
        sa.CheckConstraint(
            "materiality IN ('MATERIAL','NARROWING','COSMETIC')",
            name="ck_policy_change_log_materiality",
        ),
        # A downgrade with no justification is the whole failure mode the
        # override columns exist to prevent.
        sa.CheckConstraint(
            "overridden_by IS NULL OR length(trim(override_justification)) > 0",
            name="ck_policy_change_log_override_justified",
        ),
    )
    op.create_index(
        op.f("ix_policy_change_log_change_ref"), "policy_change_log", ["change_ref"], unique=True
    )
    op.create_index(
        op.f("ix_policy_change_log_tenant_id"), "policy_change_log", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_policy_change_log_entity_type"), "policy_change_log", ["entity_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_policy_change_log_entity_id"), "policy_change_log", ["entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_policy_change_log_materiality"), "policy_change_log", ["materiality"],
        unique=False,
    )
    op.create_index(
        op.f("ix_policy_change_log_created_at"), "policy_change_log", ["created_at"], unique=False
    )
    op.create_index(
        "ix_policy_change_log_entity", "policy_change_log",
        ["entity_type", "entity_id", "to_version"], unique=False,
    )

    op.create_table(
        "cookie_policy_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("categories", sa.JSON(), nullable=False, server_default="[]"),
        sa.Column("summary", sa.Text(), nullable=False, server_default=""),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("published_by", sa.String(length=64), nullable=False, server_default="system"),
        sa.Column(
            "published_at", sa.DateTime(timezone=True), nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column("change_log_id", sa.Integer(), nullable=True),
        sa.Column("preferences_invalidated", sa.Integer(), nullable=False, server_default="0"),
        sa.ForeignKeyConstraint(["tenant_id"], ["organizations.id"]),
        sa.ForeignKeyConstraint(["change_log_id"], ["policy_change_log.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "version_number", name="uq_cookie_policy_tenant_version"),
        sa.CheckConstraint("version_number > 0", name="ck_cookie_policy_version_positive"),
    )
    op.create_index(
        op.f("ix_cookie_policy_versions_tenant_id"), "cookie_policy_versions", ["tenant_id"],
        unique=False,
    )

    # server_default=false so every pre-existing consent is unflagged: a
    # schema change must never itself block processing that was previously
    # allowed. Only an actual material publication does that.
    op.add_column(
        "consents",
        sa.Column(
            "re_consent_required", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )
    op.add_column(
        "consents", sa.Column("re_consent_requested_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("consents", sa.Column("re_consent_campaign_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "fk_consents_re_consent_campaign_id", "consents", "re_consent_campaigns",
        ["re_consent_campaign_id"], ["id"],
    )
    op.create_index(
        op.f("ix_consents_re_consent_required"), "consents", ["re_consent_required"], unique=False
    )


def downgrade() -> None:
    op.drop_index(op.f("ix_consents_re_consent_required"), table_name="consents")
    op.drop_constraint("fk_consents_re_consent_campaign_id", "consents", type_="foreignkey")
    op.drop_column("consents", "re_consent_campaign_id")
    op.drop_column("consents", "re_consent_requested_at")
    op.drop_column("consents", "re_consent_required")

    op.drop_index(op.f("ix_cookie_policy_versions_tenant_id"), table_name="cookie_policy_versions")
    op.drop_table("cookie_policy_versions")

    op.drop_index("ix_policy_change_log_entity", table_name="policy_change_log")
    op.drop_index(op.f("ix_policy_change_log_created_at"), table_name="policy_change_log")
    op.drop_index(op.f("ix_policy_change_log_materiality"), table_name="policy_change_log")
    op.drop_index(op.f("ix_policy_change_log_entity_id"), table_name="policy_change_log")
    op.drop_index(op.f("ix_policy_change_log_entity_type"), table_name="policy_change_log")
    op.drop_index(op.f("ix_policy_change_log_tenant_id"), table_name="policy_change_log")
    op.drop_index(op.f("ix_policy_change_log_change_ref"), table_name="policy_change_log")
    op.drop_table("policy_change_log")

    op.drop_index(op.f("ix_re_consent_campaigns_status"), table_name="re_consent_campaigns")
    op.drop_index(op.f("ix_re_consent_campaigns_entity_id"), table_name="re_consent_campaigns")
    op.drop_index(op.f("ix_re_consent_campaigns_tenant_id"), table_name="re_consent_campaigns")
    op.drop_index(op.f("ix_re_consent_campaigns_campaign_ref"), table_name="re_consent_campaigns")
    op.drop_table("re_consent_campaigns")
