"""R2-07: banner impression and decision events

Revision ID: f4d5e6a7b8c9
Revises: e3d5b7c91a24
Create Date: 2026-09-04

Written by hand rather than autogenerated. The table is the only schema
change this lane makes, and `app/models/analytics.py` is not yet imported by
`app/models/entities.py` (that one line belongs to whoever owns that file),
so autogenerate would not have seen it - and would have proposed dropping
several other lanes' tables it also cannot see.

Note the rev-id: the slot originally allocated for this work, `f2b3c4d5e6a7`,
is already taken by `f2b3c4d5e6a7_add_scheduler_and_kpi_tables.py`, and its
intended parent `f1a2b3c4d5e6` does not exist on disk. This revision chains
off the real head instead.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "f4d5e6a7b8c9"
down_revision: Union[str, None] = "e3d5b7c91a24"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "banner_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=True),
        sa.Column("source_app", sa.String(length=128), nullable=False, server_default=""),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("decision", sa.String(length=32), nullable=True),
        sa.Column("surface", sa.String(length=32), nullable=False, server_default="COOKIE_BANNER"),
        sa.Column("banner_version", sa.String(length=32), nullable=False, server_default=""),
        sa.Column("language", sa.String(length=8), nullable=False, server_default="en"),
        sa.Column("page_ref", sa.String(length=128), nullable=True),
        sa.Column("session_ref", sa.String(length=64), nullable=False),
        sa.Column(
            "purposes_offered", postgresql.JSONB(astext_type=sa.Text()),
            nullable=False, server_default=sa.text("'[]'::jsonb"),
        ),
        sa.Column(
            "purposes_granted", postgresql.JSONB(astext_type=sa.Text()),
            nullable=False, server_default=sa.text("'[]'::jsonb"),
        ),
        sa.Column("time_to_decision_ms", sa.Integer(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        sa.ForeignKeyConstraint(["tenant_id"], ["organizations.id"]),
        sa.PrimaryKeyConstraint("id"),
        # An impression event must not be able to carry a decision, and a
        # decision must always name one. The Pydantic layer already refuses
        # both, but this table is the evidentiary denominator for K-02's
        # "no choice" rate and K-47's decision mix: a row that is neither
        # cleanly an impression nor cleanly a decision would silently
        # mis-attribute both, so the invariant is enforced where it cannot be
        # bypassed by a future writer that skips the schema.
        sa.CheckConstraint(
            "(event_type = 'NOTICE_SHOWN' AND decision IS NULL) OR "
            "(event_type = 'DECISION' AND decision IS NOT NULL)",
            name="ck_banner_events_decision_shape",
        ),
        sa.CheckConstraint(
            "event_type IN ('NOTICE_SHOWN','DECISION')",
            name="ck_banner_events_event_type",
        ),
        sa.CheckConstraint(
            "decision IS NULL OR decision IN ('ACCEPT_ALL','REJECT_ALL','GRANULAR','DISMISSED')",
            name="ck_banner_events_decision",
        ),
    )
    op.create_index("ix_banner_events_tenant_id", "banner_events", ["tenant_id"])
    op.create_index("ix_banner_events_source_app", "banner_events", ["source_app"])
    op.create_index("ix_banner_events_event_type", "banner_events", ["event_type"])
    op.create_index("ix_banner_events_decision", "banner_events", ["decision"])
    op.create_index("ix_banner_events_surface", "banner_events", ["surface"])
    op.create_index("ix_banner_events_banner_version", "banner_events", ["banner_version"])
    op.create_index("ix_banner_events_language", "banner_events", ["language"])
    op.create_index("ix_banner_events_occurred_at", "banner_events", ["occurred_at"])
    # The shape of every KPI query: one tenant, one period.
    op.create_index(
        "ix_banner_events_tenant_occurred", "banner_events", ["tenant_id", "occurred_at"]
    )
    # The impression -> decision join behind K-02's ignore rate and K-04.
    op.create_index(
        "ix_banner_events_session_type", "banner_events", ["session_ref", "event_type"]
    )


def downgrade() -> None:
    op.drop_index("ix_banner_events_session_type", table_name="banner_events")
    op.drop_index("ix_banner_events_tenant_occurred", table_name="banner_events")
    op.drop_index("ix_banner_events_occurred_at", table_name="banner_events")
    op.drop_index("ix_banner_events_language", table_name="banner_events")
    op.drop_index("ix_banner_events_banner_version", table_name="banner_events")
    op.drop_index("ix_banner_events_surface", table_name="banner_events")
    op.drop_index("ix_banner_events_decision", table_name="banner_events")
    op.drop_index("ix_banner_events_event_type", table_name="banner_events")
    op.drop_index("ix_banner_events_source_app", table_name="banner_events")
    op.drop_index("ix_banner_events_tenant_id", table_name="banner_events")
    op.drop_table("banner_events")
