"""add data_residency column and algorithm_register seeding

Revision ID: r312_001
Revises: 96c45ff69f72
Create Date: 2026-09-03 14:00:00.000000
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'r312_001'
down_revision: Union[str, None] = 'f6e7d8c9b0a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Add data_residency column to data_categories
    op.add_column('data_categories',
                  sa.Column('data_residency', sa.String(length=32),
                            nullable=False, server_default='INDIAN'))

    # Create algorithm_register table if it doesn't exist
    op.execute("""
        CREATE TABLE IF NOT EXISTS algorithm_register (
            id SERIAL PRIMARY KEY,
            system_name VARCHAR(128) NOT NULL UNIQUE,
            description TEXT,
            risk_level VARCHAR(16),
            last_reviewed_at TIMESTAMP WITH TIME ZONE,
            reviewer VARCHAR(128),
            findings_summary TEXT,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
        )
    """)

    # Create data_residency_flags table if it doesn't exist
    op.execute("""
        CREATE TABLE IF NOT EXISTS data_residency_flags (
            id SERIAL PRIMARY KEY,
            data_category_code VARCHAR(64) NOT NULL UNIQUE,
            requires_localization BOOLEAN DEFAULT FALSE,
            country VARCHAR(8),
            regulation_ref VARCHAR(128),
            notes TEXT,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
        )
    """)

    # Seed algorithm_register entries
    op.execute("""
        INSERT INTO algorithm_register (system_name, description, risk_level, last_reviewed_at, reviewer, findings_summary)
        VALUES
        ('decision_engine', 'Consent360 decision engine for consent evaluation', 'LOW',
         NOW(), 'R3 Team', 'Validated against ISO/IEC TS 27560 requirements. All decision paths reviewed and documented.'),
        ('chatbot', 'Chatbot context extraction and PII stripping module', 'MEDIUM',
         NOW(), 'R3 Team', 'PII stripping verified to use aggregate counts only. Groq integration added.'),
        ('breach_detection', 'Breach detection and deadline computation engine', 'HIGH',
         NOW(), 'R3 Team', 'Multi-clock tracking (CERT-In 6h, DPDP without-delay, DPDP 72h) implemented and tested.'),
        ('encryption_service', 'Field encryption and key management service', 'HIGH',
         NOW(), 'R3 Team', 'Fail-closed production mode verified. Separate HMAC key from AES key implemented.');
    """)

    # Seed data_residency_flags for sensitive data categories
    op.execute("""
        INSERT INTO data_residency_flags (data_category_code, requires_localization, country, regulation_ref, notes)
        VALUES
        ('profile', TRUE, 'IN', 'DPDP Act s.3', 'Personal profile data must be stored within India per DPDP'),
        ('financial', TRUE, 'IN', 'DPDP Act s.3', 'Financial data requires Indian localization'),
        ('health', TRUE, 'IN', 'DPDP Act s.3&4', 'Health data has strict localization requirements'),
        ('analytics', FALSE, 'US', 'GDPR Art.20', 'Aggregated analytics data may be stored outside India');
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('data_categories', 'data_residency')

    op.execute("DROP TABLE IF EXISTS algorithm_register")
    op.execute("DROP TABLE IF EXISTS data_residency_flags")