export interface BannerCopy {
  bannerTitle: string
  bannerText: string
  chooseLanguage: string
  acceptAll: string
  rejectAll: string
  savePreferences: string
  viewFullNotice: string
  close: string
  dataItemsLabel: string
  servicesLabel: string
  retentionLabel: string
  retentionDays: string
  consentLabel: string
  dpoLabel: string
  withdrawLink: string
  rightsLink: string
  grievanceLink: string
  boardComplaintLink: string
  noPurposes: string
}

// Falls back to English whenever the visitor's chosen language has no entry here,
// so the banner never renders blank for an unsupported language.
export const BANNER_COPY: Record<string, BannerCopy> = {
  en: {
    bannerTitle: 'Privacy & Consent Preferences',
    bannerText:
      'We use cookies and data processing to provide you with a better experience. You can manage your consent preferences below. Required purposes are always enabled.',
    chooseLanguage: 'Choose language',
    acceptAll: 'Accept All',
    rejectAll: 'Reject All',
    savePreferences: 'Save Preferences',
    viewFullNotice: 'View full notice',
    close: 'Close',
    dataItemsLabel: 'Data items',
    servicesLabel: 'Services enabled',
    retentionLabel: 'Retention',
    retentionDays: 'days',
    consentLabel: 'Consent',
    dpoLabel: 'Data Protection Officer',
    withdrawLink: 'Withdraw consent',
    rightsLink: 'Your rights',
    grievanceLink: 'Grievance',
    boardComplaintLink: 'Board complaint',
    noPurposes: 'No consent purposes available. Connect to Consent360 to manage preferences.',
  },
  hi: {
    bannerTitle: 'गोपनीयता और सहमति प्राथमिकताएं',
    bannerText:
      'हम आपको बेहतर अनुभव देने के लिए कुकीज़ और डेटा प्रोसेसिंग का उपयोग करते हैं। आप नीचे अपनी सहमति प्राथमिकताएं प्रबंधित कर सकते हैं। आवश्यक उद्देश्य हमेशा सक्षम रहते हैं।',
    chooseLanguage: 'भाषा चुनें',
    acceptAll: 'सभी स्वीकार करें',
    rejectAll: 'सभी अस्वीकार करें',
    savePreferences: 'प्राथमिकताएं सहेजें',
    viewFullNotice: 'पूरा नोटिस देखें',
    close: 'बंद करें',
    dataItemsLabel: 'डेटा आइटम',
    servicesLabel: 'सक्षम सेवाएं',
    retentionLabel: 'प्रतिधारण',
    retentionDays: 'दिन',
    consentLabel: 'सहमति',
    dpoLabel: 'डेटा संरक्षण अधिकारी',
    withdrawLink: 'सहमति वापस लें',
    rightsLink: 'आपके अधिकार',
    grievanceLink: 'शिकायत',
    boardComplaintLink: 'बोर्ड शिकायत',
    noPurposes: 'कोई सहमति उद्देश्य उपलब्ध नहीं है। प्राथमिकताएं प्रबंधित करने के लिए Consent360 से कनेक्ट करें।',
  },
  ta: {
    bannerTitle: 'தனியுரிமை & சம்மத விருப்பங்கள்',
    bannerText:
      'உங்களுக்கு சிறந்த அனுபவத்தை வழங்க நாங்கள் குக்கீகள் மற்றும் தரவு செயலாக்கத்தைப் பயன்படுத்துகிறோம். கீழே உங்கள் சம்மத விருப்பங்களை நிர்வகிக்கலாம். தேவையான நோக்கங்கள் எப்போதும் இயக்கத்தில் இருக்கும்.',
    chooseLanguage: 'மொழியைத் தேர்ந்தெடுக்கவும்',
    acceptAll: 'அனைத்தையும் ஏற்கவும்',
    rejectAll: 'அனைத்தையும் நிராகரிக்கவும்',
    savePreferences: 'விருப்பங்களைச் சேமிக்கவும்',
    viewFullNotice: 'முழு அறிவிப்பைக் காண்க',
    close: 'மூடு',
    dataItemsLabel: 'தரவு உருப்படிகள்',
    servicesLabel: 'இயக்கப்பட்ட சேவைகள்',
    retentionLabel: 'தக்கவைப்பு',
    retentionDays: 'நாட்கள்',
    consentLabel: 'சம்மதம்',
    dpoLabel: 'தரவுப் பாதுகாப்பு அதிகாரி',
    withdrawLink: 'சம்மதத்தை விலக்கிக்கொள்',
    rightsLink: 'உங்கள் உரிமைகள்',
    grievanceLink: 'குறை தீர்வு',
    boardComplaintLink: 'குழு புகார்',
    noPurposes: 'சம்மத நோக்கங்கள் எதுவும் இல்லை. விருப்பங்களை நிர்வகிக்க Consent360 உடன் இணைக்கவும்.',
  },
  te: {
    bannerTitle: 'గోప్యత & సమ్మతి ప్రాధాన్యతలు',
    bannerText:
      'మీకు మెరుగైన అనుభవాన్ని అందించడానికి మేము కుకీలు మరియు డేటా ప్రాసెసింగ్‌ను ఉపయోగిస్తాము. మీరు దిగువ మీ సమ్మతి ప్రాధాన్యతలను నిర్వహించవచ్చు. అవసరమైన ప్రయోజనాలు ఎల్లప్పుడూ ప్రారంభించబడి ఉంటాయి.',
    chooseLanguage: 'భాషను ఎంచుకోండి',
    acceptAll: 'అన్నింటినీ ఆమోదించండి',
    rejectAll: 'అన్నింటినీ తిరస్కరించండి',
    savePreferences: 'ప్రాధాన్యతలను సేవ్ చేయండి',
    viewFullNotice: 'పూర్తి నోటీసును చూడండి',
    close: 'మూసివేయండి',
    dataItemsLabel: 'డేటా అంశాలు',
    servicesLabel: 'ప్రారంభించబడిన సేవలు',
    retentionLabel: 'నిలుపుదల',
    retentionDays: 'రోజులు',
    consentLabel: 'సమ్మతి',
    dpoLabel: 'డేటా రక్షణ అధికారి',
    withdrawLink: 'సమ్మతిని ఉపసంహరించుకోండి',
    rightsLink: 'మీ హక్కులు',
    grievanceLink: 'ఫిర్యాదు',
    boardComplaintLink: 'బోర్డు ఫిర్యాదు',
    noPurposes: 'సమ్మతి ప్రయోజనాలు అందుబాటులో లేవు. ప్రాధాన్యతలను నిర్వహించడానికి Consent360కి కనెక్ట్ చేయండి.',
  },
  kn: {
    bannerTitle: 'ಗೌಪ್ಯತೆ ಮತ್ತು ಸಮ್ಮತಿ ಆದ್ಯತೆಗಳು',
    bannerText:
      'ನಿಮಗೆ ಉತ್ತಮ ಅನುಭವವನ್ನು ನೀಡಲು ನಾವು ಕುಕೀಗಳು ಮತ್ತು ಡೇಟಾ ಸಂಸ್ಕರಣೆಯನ್ನು ಬಳಸುತ್ತೇವೆ. ಕೆಳಗೆ ನಿಮ್ಮ ಸಮ್ಮತಿ ಆದ್ಯತೆಗಳನ್ನು ನಿರ್ವಹಿಸಬಹುದು. ಅಗತ್ಯ ಉದ್ದೇಶಗಳು ಯಾವಾಗಲೂ ಸಕ್ರಿಯವಾಗಿರುತ್ತವೆ.',
    chooseLanguage: 'ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
    acceptAll: 'ಎಲ್ಲವನ್ನೂ ಸ್ವೀಕರಿಸಿ',
    rejectAll: 'ಎಲ್ಲವನ್ನೂ ತಿರಸ್ಕರಿಸಿ',
    savePreferences: 'ಆದ್ಯತೆಗಳನ್ನು ಉಳಿಸಿ',
    viewFullNotice: 'ಪೂರ್ಣ ಸೂಚನೆಯನ್ನು ವೀಕ್ಷಿಸಿ',
    close: 'ಮುಚ್ಚಿ',
    dataItemsLabel: 'ಡೇಟಾ ಐಟಂಗಳು',
    servicesLabel: 'ಸಕ್ರಿಯಗೊಳಿಸಿದ ಸೇವೆಗಳು',
    retentionLabel: 'ಧಾರಣ',
    retentionDays: 'ದಿನಗಳು',
    consentLabel: 'ಸಮ್ಮತಿ',
    dpoLabel: 'ಡೇಟಾ ಸಂರಕ್ಷಣಾ ಅಧಿಕಾರಿ',
    withdrawLink: 'ಸಮ್ಮತಿಯನ್ನು ಹಿಂಪಡೆಯಿರಿ',
    rightsLink: 'ನಿಮ್ಮ ಹಕ್ಕುಗಳು',
    grievanceLink: 'ಕುಂದುಕೊರತೆ',
    boardComplaintLink: 'ಬೋರ್ಡ್ ದೂರು',
    noPurposes: 'ಯಾವುದೇ ಸಮ್ಮತಿ ಉದ್ದೇಶಗಳು ಲಭ್ಯವಿಲ್ಲ. ಆದ್ಯತೆಗಳನ್ನು ನಿರ್ವಹಿಸಲು Consent360 ಗೆ ಸಂಪರ್ಕಿಸಿ.',
  },
  ml: {
    bannerTitle: 'സ്വകാര്യതയും സമ്മത മുൻഗണനകളും',
    bannerText:
      'നിങ്ങൾക്ക് മെച്ചപ്പെട്ട അനുഭവം നൽകാൻ ഞങ്ങൾ കുക്കികളും ഡാറ്റാ പ്രോസസ്സിംഗും ഉപയോഗിക്കുന്നു. നിങ്ങളുടെ സമ്മത മുൻഗണനകൾ ചുവടെ നിയന്ത്രിക്കാം. ആവശ്യമായ ഉദ്ദേശ്യങ്ങൾ എപ്പോഴും സജീവമായിരിക്കും.',
    chooseLanguage: 'ഭാഷ തിരഞ്ഞെടുക്കുക',
    acceptAll: 'എല്ലാം സ്വീകരിക്കുക',
    rejectAll: 'എല്ലാം നിരസിക്കുക',
    savePreferences: 'മുൻഗണനകൾ സംരക്ഷിക്കുക',
    viewFullNotice: 'പൂർണ്ണ അറിയിപ്പ് കാണുക',
    close: 'അടയ്ക്കുക',
    dataItemsLabel: 'ഡാറ്റാ ഇനങ്ങൾ',
    servicesLabel: 'സജീവമാക്കിയ സേവനങ്ങൾ',
    retentionLabel: 'നിലനിർത്തൽ',
    retentionDays: 'ദിവസങ്ങൾ',
    consentLabel: 'സമ്മതം',
    dpoLabel: 'ഡാറ്റാ സംരക്ഷണ ഓഫീസർ',
    withdrawLink: 'സമ്മതം പിൻവലിക്കുക',
    rightsLink: 'നിങ്ങളുടെ അവകാശങ്ങൾ',
    grievanceLink: 'പരാതി',
    boardComplaintLink: 'ബോർഡ് പരാതി',
    noPurposes: 'സമ്മത ഉദ്ദേശ്യങ്ങളൊന്നും ലഭ്യമല്ല. മുൻഗണനകൾ നിയന്ത്രിക്കാൻ Consent360-ലേക്ക് കണക്റ്റ് ചെയ്യുക.',
  },
  bn: {
    bannerTitle: 'গোপনীয়তা ও সম্মতি পছন্দসমূহ',
    bannerText:
      'আপনাকে আরও ভালো অভিজ্ঞতা দিতে আমরা কুকি এবং ডেটা প্রসেসিং ব্যবহার করি। আপনি নিচে আপনার সম্মতি পছন্দ পরিচালনা করতে পারেন। প্রয়োজনীয় উদ্দেশ্যগুলি সর্বদা সক্রিয় থাকে।',
    chooseLanguage: 'ভাষা নির্বাচন করুন',
    acceptAll: 'সব গ্রহণ করুন',
    rejectAll: 'সব প্রত্যাখ্যান করুন',
    savePreferences: 'পছন্দগুলি সংরক্ষণ করুন',
    viewFullNotice: 'সম্পূর্ণ নোটিশ দেখুন',
    close: 'বন্ধ করুন',
    dataItemsLabel: 'ডেটা আইটেম',
    servicesLabel: 'সক্রিয় পরিষেবা',
    retentionLabel: 'সংরক্ষণকাল',
    retentionDays: 'দিন',
    consentLabel: 'সম্মতি',
    dpoLabel: 'ডেটা সুরক্ষা কর্মকর্তা',
    withdrawLink: 'সম্মতি প্রত্যাহার করুন',
    rightsLink: 'আপনার অধিকার',
    grievanceLink: 'অভিযোগ',
    boardComplaintLink: 'বোর্ড অভিযোগ',
    noPurposes: 'কোনো সম্মতি উদ্দেশ্য উপলব্ধ নেই। পছন্দ পরিচালনা করতে Consent360-এর সাথে সংযুক্ত করুন।',
  },
  mr: {
    bannerTitle: 'गोपनीयता आणि संमती प्राधान्ये',
    bannerText:
      'तुम्हाला उत्तम अनुभव देण्यासाठी आम्ही कुकीज आणि डेटा प्रक्रिया वापरतो. तुम्ही खाली तुमची संमती प्राधान्ये व्यवस्थापित करू शकता. आवश्यक उद्देश नेहमी सक्रिय असतात.',
    chooseLanguage: 'भाषा निवडा',
    acceptAll: 'सर्व स्वीकारा',
    rejectAll: 'सर्व नाकारा',
    savePreferences: 'प्राधान्ये जतन करा',
    viewFullNotice: 'संपूर्ण सूचना पहा',
    close: 'बंद करा',
    dataItemsLabel: 'डेटा आयटम',
    servicesLabel: 'सक्रिय केलेल्या सेवा',
    retentionLabel: 'धारणा',
    retentionDays: 'दिवस',
    consentLabel: 'संमती',
    dpoLabel: 'डेटा संरक्षण अधिकारी',
    withdrawLink: 'संमती मागे घ्या',
    rightsLink: 'तुमचे हक्क',
    grievanceLink: 'तक्रार',
    boardComplaintLink: 'मंडळ तक्रार',
    noPurposes: 'कोणतेही संमती उद्देश उपलब्ध नाहीत. प्राधान्ये व्यवस्थापित करण्यासाठी Consent360 शी कनेक्ट करा.',
  },
  gu: {
    bannerTitle: 'ગોપનીયતા અને સંમતિ પસંદગીઓ',
    bannerText:
      'તમને વધુ સારો અનુભવ આપવા માટે અમે કૂકીઝ અને ડેટા પ્રોસેસિંગનો ઉપયોગ કરીએ છીએ. તમે નીચે તમારી સંમતિ પસંદગીઓ સંચાલિત કરી શકો છો. જરૂરી હેતુઓ હંમેશા સક્રિય રહે છે.',
    chooseLanguage: 'ભાષા પસંદ કરો',
    acceptAll: 'બધું સ્વીકારો',
    rejectAll: 'બધું નકારો',
    savePreferences: 'પસંદગીઓ સાચવો',
    viewFullNotice: 'સંપૂર્ણ સૂચના જુઓ',
    close: 'બંધ કરો',
    dataItemsLabel: 'ડેટા આઇટમ્સ',
    servicesLabel: 'સક્રિય કરેલી સેવાઓ',
    retentionLabel: 'જાળવણી',
    retentionDays: 'દિવસો',
    consentLabel: 'સંમતિ',
    dpoLabel: 'ડેટા સંરક્ષણ અધિકારી',
    withdrawLink: 'સંમતિ પાછી ખેંચો',
    rightsLink: 'તમારા અધિકારો',
    grievanceLink: 'ફરિયાદ',
    boardComplaintLink: 'બોર્ડ ફરિયાદ',
    noPurposes: 'કોઈ સંમતિ હેતુઓ ઉપલબ્ધ નથી. પસંદગીઓ સંચાલિત કરવા માટે Consent360 સાથે જોડાઓ.',
  },
  pa: {
    bannerTitle: 'ਪਰਦੇਦਾਰੀ ਅਤੇ ਸਹਿਮਤੀ ਤਰਜੀਹਾਂ',
    bannerText:
      'ਤੁਹਾਨੂੰ ਬਿਹਤਰ ਅਨੁਭਵ ਦੇਣ ਲਈ ਅਸੀਂ ਕੂਕੀਜ਼ ਅਤੇ ਡੇਟਾ ਪ੍ਰੋਸੈਸਿੰਗ ਦੀ ਵਰਤੋਂ ਕਰਦੇ ਹਾਂ। ਤੁਸੀਂ ਹੇਠਾਂ ਆਪਣੀਆਂ ਸਹਿਮਤੀ ਤਰਜੀਹਾਂ ਦਾ ਪ੍ਰਬੰਧਨ ਕਰ ਸਕਦੇ ਹੋ। ਲੋੜੀਂਦੇ ਉਦੇਸ਼ ਹਮੇਸ਼ਾ ਸਰਗਰਮ ਰਹਿੰਦੇ ਹਨ।',
    chooseLanguage: 'ਭਾਸ਼ਾ ਚੁਣੋ',
    acceptAll: 'ਸਭ ਸਵੀਕਾਰ ਕਰੋ',
    rejectAll: 'ਸਭ ਰੱਦ ਕਰੋ',
    savePreferences: 'ਤਰਜੀਹਾਂ ਸੰਭਾਲੋ',
    viewFullNotice: 'ਪੂਰਾ ਨੋਟਿਸ ਵੇਖੋ',
    close: 'ਬੰਦ ਕਰੋ',
    dataItemsLabel: 'ਡੇਟਾ ਆਈਟਮਾਂ',
    servicesLabel: 'ਸਰਗਰਮ ਸੇਵਾਵਾਂ',
    retentionLabel: 'ਧਾਰਨ',
    retentionDays: 'ਦਿਨ',
    consentLabel: 'ਸਹਿਮਤੀ',
    dpoLabel: 'ਡੇਟਾ ਸੁਰੱਖਿਆ ਅਧਿਕਾਰੀ',
    withdrawLink: 'ਸਹਿਮਤੀ ਵਾਪਸ ਲਵੋ',
    rightsLink: 'ਤੁਹਾਡੇ ਅਧਿਕਾਰ',
    grievanceLink: 'ਸ਼ਿਕਾਇਤ',
    boardComplaintLink: 'ਬੋਰਡ ਸ਼ਿਕਾਇਤ',
    noPurposes: 'ਕੋਈ ਸਹਿਮਤੀ ਉਦੇਸ਼ ਉਪਲਬਧ ਨਹੀਂ ਹਨ। ਤਰਜੀਹਾਂ ਦਾ ਪ੍ਰਬੰਧਨ ਕਰਨ ਲਈ Consent360 ਨਾਲ ਜੁੜੋ।',
  },
}
